gigasecond/cases_test.go
gigasecond/example.go
gigasecond/gigasecond_test.go

- cases_test.go regenerated with new cases from x-common.
- flexibility added in gigasecond_test.go to parse full times.
- testVersion bumped to 2 to reflect new test cases.
This was a small change to the test program just to handle the new data.  The example needed no changes other than bumping testVersion.  Existing solutions should similarly continue to work.

gigasecond:  use full time test cases

---

clock/clock_test.go

Proposed alternative to PR https://github.com/exercism/xgo/pull/121.  TestVersion is unchanged because this change is in comments and error messages only.  It cannot affect whether any existing solution passes or fails.  (Update:  Mm, well, not strictly true.  The logic was rewritten a little, but it should pass and fail exactly the same.)

clock: add test program comments, improve failure message

---

config.json
custom-set/example_gen.go
gen/gen.go
gigasecond/example_gen.go

When I wrote the template-based data converter for gigasecond, I realized that much of it was not specific to gigasecond and could be reused.  Custom-set turned out to be able to use most of this code without change.  This PR collects the common code into a package that can be used across exercises.
The other exercise with json test data currently is clock.  It was the first generator I wrote and doesn't use templates.  If this PR is accepted, a good test of it will be to replace the clock generation code with a template and a call to this new package.
None of this affects what the solver sees btw.  It's all for the xgo developer.

code gen function usable across exercises

---

bob/bob_test.go
bob/cases_test.go
bob/example.go
bob/example_gen.go
leap/cases_test.go
leap/example.go
leap/example_gen.go
leap/leap_test.go

Use common test data, also add TestVersion.  Leap example needed no change except TestVersion, Bob example needed a tweak to handle a couple of the new test cases.

bob, leap: use common test data

---

README.md

This adds a small section explaining how we use `testVersion` to avoid confusion when the problems evolve.

Explain testVersion in the README

---

.travis.yml
config.json
ledger/example.go
ledger/ledger.go
ledger/ledger_test.go

This is my first attempt at a refactoring exercise, as we discussed on the exercism mailing list.
Have kept this unsquashed in order to make it easier to understand how I've gone from the example to the exercise. Will squash after review.
I'm not sure where in the line of exercises this should go, added to the end of config.json just to make travis work.
Because this exercise has two versions (ledger.go and example.go) that should (and do) both pass the tests I had to use a build flag. To test example.go and not ledger.go you need to run `go test -example`. I've changed .travis.yml to do this automatically.
Note that it's not really desirable to test ledger.go automatically as it contains a race condition which leads to tests failing if it's triggered. The race is very race (I haven't …

Ledger refactoring exercise

---

ledger/example.go

Just saw this style in another go package, it's much clearer than the nested
if-then-else's.

 Make sorting in ledger example somewhat clearer

---

robot-simulator/example.go
tournament/example.go
triangle/example.go

Typed constants are harder to use in wrong places.

Use typed constants whenever applicable

---

config.json
tree-building/example.go
tree-building/tree.go
tree-building/tree_test.go

This is an implementation of exercism/x-common#60.
The interesting part here is that converting a list of id/parent pairs to a tree when using a language with mutable arrays, can be quite efficient: most of the algorithm is linear, only the sorting of children isn't but even that has good complexity. There is also a much more simplistic way which is more than quadratic.
To illustrate this, these are the benchmark results from the example (fast algorithm):
```
BenchmarkTwoTree              50          23799606 ns/op
BenchmarkTenTree            1000           2653044 ns/op
BenchmarkShallowTree        1000           2955220 ns/op
```
and these are from the exercise file (slow algorithm):
```
BenchmarkTwoTree               1        10763446466 ns/op
BenchmarkTenTree              10 …
```

Add tree-building refactoring test

---

bank-account/bank_account_test.go
custom-set/custom_set_test.go

One changes a format verb, and the other an error text

Two minor fixes to the testcases of the Go exercises

---

prime-factors/example.go
prime-factors/primefactors_test.go

Also other small changes: Add testVersion, remove sort and instead document
that the solver must return factors in increasing order, and fix benchmark
to time all test cases.
First of three PRs to address 32 bit environments.  This one should be non-controversial.  The API will now use int64s instead of ints.

prime-factors:  Use int64 so things work in 32 bit environments.

---

largest-series-product/example.go
largest-series-product/largest_series_product_test.go

API left incompletely specified for now.  This is controversial, see discussion at Issue https://github.com/exercism/xgo/issues/157 and PR https://github.com/exercism/xgo/pull/158.
With this change the test program compiles with GOARCH=386 (previously it did not complile) and the example program is updated to pass tests with GOARCH=386.
The old example would still compile against this test program.  It would compile and pass tests in 64 bit environments, but would fail tests in 32 bit environments -- one of the test cases overflows 32 bits.
This PR allows -- but does not compel -- the solver to write an int-size safe program.  If they return int rather than int64 they can face nitpicking.  Of course if they are actually testing with 32 bits they will see the test fail.
The idea is that …

largest series product: test against int64 values

---

.travis.yml

Go 1.5 simplifies cross-compiling, in this case building and testing for a 32 bit architecture on the Travis 64 bit VM.
Third of three PRs to validate that the test programs all run in a 32 bit environment.

add tip GOARCH=386 to build matrix, bump to 1.4.2

---

gen/gen.go

In git v2.2.1 the command 'git show --oneline HEAD' includes the diff in addition to the SHA and the commit subject (not the full message). This breaks the generate command, as it expects a single line of output.
Here's the output of `git show --oneline HEAD` in this branch:
```plain
$ git show --oneline HEAD
89d4a14 Return just the x-commit SHA and subject in gen
diff --git a/gen/gen.go b/gen/gen.go
index 380289c..98f6c2a 100644
--- a/gen/gen.go
+++ b/gen/gen.go
@@ -58,7 +58,7 @@ func getPath(jFile string) (jPath, jOri, jCommit string) {
if jPath = os.Getenv("EXTEST"); jPath > "" {
return jPath, "local file", "" // override
}
-       c := exec.Command("git", "show", "--oneline", "HEAD")
+       c := exec.Command("git", "log", "-1", "--oneline")
c.Dir = "../../../exercism/x-common"
ori, …
```

Return just the x-commit SHA and subject in gen

---

secret-handshake/example.go
secret-handshake/secret_handshake_test.go

Nothing in the [README] seems to indicate that numbers larger than 32
wouldn't be in the set of potential handshakes.
[README]: https://github.com/exercism/x-common/blob/master/secret-handshake.md
Practically speaking, a sophisticated attacker could brute-force so few
combinations (31 codes each with 8 possible handshakes = 248), so we'd
want to ensure that larger numbers with seemingly no relation to the
significant binary bits would also be possible codes.
Seriously though, am I missing something in this problem? @kytrinyx @soniakeys

Update large number test to increase security

---

README.md
gen/gen.go

I'm not convinced I have made the right assumptions here, so this is more of a tentative suggestion than anything else.
This makes it possible to generate test cases either from a problem directory, or from the root of the repository. E.g. both of the following now work:
cd xgo
go run leap/example_gen.go
and
cd xgo/leap
go run example_gen.go
This clarifies the assumption about where the x-common repository is, making it relative to the gen/gen.go file rather than relative to the present working directory.
The test_cases.go file is generated to the directory containing the example_gen.go file.

Generate test cases more flexibly

---

config.json
counter/counter_test.go
counter/example.go
counter/impl1.go
counter/impl2.go
counter/impl3.go
counter/impl4.go
counter/interface.go
counter/maker.go

I'm a bit worried about the exercism cli tool here. I seem to recall that it stops the user accidentally submitting the test file, but in this case the file with the "_test.go" name is the submission.

Add "counter", a write-the-test-suite exercise

---

bracket-push/bracket-push_test.go

I am adding these two tests because they rule out some incorrect solutions that would have been accepted by the previous set of tests. This would be the class of solution that simply counts the number of open/close brackets and makes sure they're equal. This includes my own solution. I only realized my mistake after looking at others' solutions. These tests would have helped me realize my mistake before submitting.
NOTE: This exercise is also in the javascript track (see http://x.exercism.io/problems/bracket-push ) -- therefore I have opened https://github.com/exercism/xjavascript/pull/118

Add two bracket-push tests

---

.travis.yml

move configlet out of build matrix, exclude 1.4 rather than include tip, and enable container-based build.
This was all started with an attempt to add a stub solution to one of the problems.  It didn't build because there was a separate install step running that wasn't needed.  I disabled that then noticed the other things could be updated.

don't do install step, update go version numbers, add comments,

---

.travis.yml
paasio/paasio_test.go

also reduce paasio concurrency a bit to pass with -race.
-race makes sense with a couple of exercises now using concurrency.  (This doesn't have to go ahead of ledger, it could wait its turn.)

travis.yml: 1.4.2, also try -race.

---

circular-buffer/circular_buffer_test.go
circular-buffer/example.go

This test is useful to make sure implementations don't drop items from
non-full buffers when using Overwrite.

circular-buffer: Test overwrite on non-full buffer

---

clock/clock.go

Leap is currently first in config.json order, clock is second.  So this is still rather verbose although a little different than leap.

clock: add stub file

---

raindrops/cases_test.go
raindrops/example.go
raindrops/example_gen.go
raindrops/raindrops.go
raindrops/raindrops_test.go

Yay for common test cases.  Thanks @mikeyjcat!  I thought I was making a stub for an exercise that didn't have common test cases but then I saw they were done.  Had to add test version as well, it's too easy.  This stub eliminates most of the comments relative to leap, clock, and gigasecond.  It does provide complete package and TestVersion lines.

raindrops: common test cases, test version, stub

---

bob/bob.go
circular-buffer/circular_buffer.go
crypto-square/crypto_square.go
custom-set/custom_set.go
food-chain/food_chain.go
gigasecond/gigasecond.go
hamming/hamming.go
paasio/paasio.go
tournament/tournament.go
triangle/triangle.go

There were 8 left, these were all done minimally, including bob and hamming.  Those two appear as first exercises in some tracks but are not listed that early in Go's config.json so I left them minimal.
Also in this commit are some little changes to the stubs for gigasecond and triangle.  Strangely, they were causing error messages.  The build constraint keeps the stubs from being tested, but the top of the file must be parsed to see the build constraint.  It appears that the go tool prints error messages from the partial parse, although it (properly) doesn't then act on the errors.  Originally I had deliberately left some incomplete lines in the stubs not wanting to give too much away and hadn't noticed the error messages in the build log.  In this commit though I fixed/removed stuff …

issue-148: add remaining stubs

---

react/example.go
react/react_test.go

Two commits, the first a small refactor (but does add a small bit of extra functionality) and the second adding new tests. Much more detail provided in the individual commit messages.

React tests

---

leap/leap.go

I just nitpicked three solutions in a row where they had
left the comments in place.
I'm attempting to move the instructions about deleting closer to where
they're writing code, and then also yelling loudly in all caps.
It might help.

Tweak stock comments in leap stub solution

---

ledger/example.go
ledger/ledger.go
ledger/ledger_test.go

The discussion we had in #195 indicates that Unicode introduces a whole
host of issues that are better suited for their own exercise. Let's keep
the ledger exercise focused on refactoring. This avoids a potential
source of confusion of "why is it cutting at 24 instead of 22?"
ledger test version is bumped for this.

ledger: remove multibyte characters

---

config.json
pov/example.go
pov/pov_test.go

I like graph algorithms so I kind of liked this exercise until now implemented in just Clojure and Haskell.  I used the same test cases.  I added some paragraphs of explanation in the test program.  And I kept the API as flexible as I could, allowing solvers to define their own graph representation.  Also I split the tests into two parts.  Part one is just to create the graph and code a method for inspecting the graph.  Code-wise, this is a significant part of the exercise and yet it's not even the part advertised as the crux of the exercise.  Since part two is the interesting re-rooting algorithm, I did a few more things to try to simplify part one.  The test program promises to build a graph that is tree, to build it from the bottom up, and to pass the root to the the re-rooting method. …

add exercise pov

---

triangle/triangle_test.go

As reported in #207, the triangle tests can be solved by a trivial empty
implementation that simply sets all four triangle types equal to one
another. We should prevent false positives, and we can do so by checking
that Equ != Iso, etc.
I verified that 1) the trivial solution fails the new test, and 2) the
example solution passes the test.
Fixes #207

triangle: Ensure no pair of triangle types are equal

---

clock/clock_test.go

This commit fixes a few typos in the `clock_test` file. It also adds backticks around a function name to distinguish it from plain words in the documentation.

Fix a few typos in the `clock_test` file

---

scrabble-score/example.go
scrabble-score/scrabble_score_test.go

The package name should not have an underscore.
I also added a comment to the Score function, for the sake of completeness.

Fix style violations in scrabble-score

---

bracket-push/bracket_push_test.go
bracket-push/example.go

The package name should not have an underscore.
The test file name should only have underscores, not a mix of hyphens and underscores.
Constants should be mixedCaps.
The constants that the reference solution invents should not be exported.
I also gave the constants a prefix for readability.
This change is not backwards compatible due to the change of the package name, so I added a TestVersion.

Fix style violations in bracket push

---

error-handling/common.go
error-handling/error_handling_test.go
error-handling/example.go

Go package names should not have underscores.

Fix package name in error-handling exercise

---

gigasecond/example.go
gigasecond/gigasecond.go
gigasecond/gigasecond_test.go

After providing a bunch of feedback to solutions to this exercise, I realized that
the whole birthday thing is a distraction. The time.Duration bit is interesting.
Closes #214.

Remove birthday from gigasecond.

---

bob/bob_test.go
circular-buffer/circular_buffer_test.go
clock/clock_test.go
crypto-square/crypto_square_test.go
custom-set/custom_set_test.go
gigasecond/gigasecond_test.go
hamming/hamming_test.go
largest-series-product/largest_series_product_test.go
leap/leap_test.go
ledger/ledger_test.go
meetup/meetup_test.go
paasio/paasio_test.go
prime-factors/primefactors_test.go
raindrops/raindrops_test.go
react/react_test.go
rna-transcription/rna_transcription_test.go
roman-numerals/roman_numerals_test.go
tournament/tournament_test.go
word-count/word_count_test.go

These were a bit confusing, and it seems easier to simply git log -p within the file
we're interested in.

Delete the SHA1 for retired testVersions

---

exercises/bob/example_gen.go
exercises/clock/example_gen.go
exercises/custom-set/example_gen.go
exercises/gigasecond/example_gen.go
exercises/hamming/example_gen.go
exercises/leap/example_gen.go
exercises/meetup/example_gen.go
exercises/raindrops/example_gen.go
exercises/rna-transcription/example_gen.go
exercises/roman-numerals/example_gen.go
exercises/word-count/example_gen.go

In d895e12bc457dad8c024ad457380ade2a5f55aa9 we moved all exercises to
the exercises subdirectory. So, whereas the `gen` directory used to be
one directory above a given generator file, now it is two directories
above. So we need ../../gen rather than ../gen

import ../../gen in all generators rather than ../gen

---

exercises/triangle/example.go
exercises/triangle/triangle.go
exercises/triangle/triangle_test.go

These are degenerate triangles since they're really just lines, but
they're still good enough under the triangle inequality (which
explicitly allows a+b == c) so let's go ahead and test for them.
Test for isosceles and scalene added. Equilateral is impossible.
Closes #231

triangle: Allow triangles where a+b == c

---

exercises/triangle/example.go

I know examples don't need to be the best code, but
* this was bugging me while I was looking at the example code for #231 so I decided to fix it
* even if the code is unabashedly not the best, I say there's still no harm in increasing readability (which I argue this does)

Triangle cleanup

---

exercises/paasio/interface.go

As discussed in #143, since the tests are going so far as to ensure that
the counters are still accurate in the face of concurrent operations, it
is wise to document these guarantees as well. This also clarifies that
there need be no guarantees on interleaving of Read/Write calls, another
discussion point in #143.

paasio: Document required concurrency guarantees

---

exercises/triangle/triangle.go

If someone chooses to use iota for the triangle kinds, then it makes sense to have
NaT represented as 0.

triangle: reorder constants in stub file

---

exercises/clock/clock_test.go

The benchmark was forcing the clock type to be an alias to int.
It's more interesting if we leave the implementation open.
This tweaks the benchmark so that other implementations of clock
aren't a compiler error.
Fixes #238

clock: make benchmark implementation non-specific

---

exercises/paasio/example.go
exercises/paasio/paasio.go
exercises/paasio/paasio_test.go

Because it doesn't look good to have commented-out code in examples, nor required interfaces that aren't even getting tested.

paasio: Actually test ReadWriteCounter

---

exercises/hello-world/hello_test.go
exercises/leap/leap_test.go
exercises/poker/poker_test.go
exercises/react/react_test.go
exercises/tournament/tournament_test.go
exercises/tree-building/tree_test.go
exercises/word-search/word_search_test.go

Since both test version constants are unexported, it doesn't make sense to specify
that the one in the test suite is 'internal'.

Remove redundant word in instructions

---

README.md

Since #249 was merged, stub files no longer have build constraints. This
means an attempt to run `go test` without removing the build constraints
will fail. So instead, we should direct contributors to run the script
that moves the stub files aside.

README: use bin/test-without-stubs in test instructions

---

exercises/sum-of-multiples/sum_of_multiples_test.go

Clarify the discrepancy between the Go implementation and the current README.
This fixes #256.

sum-of-multiples: add clarifying comment

---

exercises/clock/cases_test.go

The existing test suite was not rigorous enough in testing the equality
of two clock values. Specifically, it was unable to compare two clocks
where the times were offset by 24 hours. For example,
clock{0, 1}
clock{0, 1441}
Since there are 1440 minutes in a 24 hour period, the time on the second
clock should be wrapped around, making it equal to the first.
This new test will catch this situation.

Add additional equality test to clock exercise

---

README.md

Works for both kytrinyx and me; we both clone outside of our GOPATH, so
can remove that from the instructions.
Closes #263

README: No need to clone to GOPATH

---

exercises/diffie-hellman/diffie_hellman_test.go

We wouldn't want students to copy those directly and be confused when
they don't work.
Closes #265

diffie-hellman: remove extra commas in expected signatures

---

exercises/clock/cases_test.go
exercises/clock/clock_test.go
exercises/clock/example.go

The canonical inputs/outputs in clock.json were expanded
recently to handle multiple rollovers in either direction, and
to test more edge cases in the equality tests.
This also bumps the test version.

clock: regenerate test cases

---

exercises/scrabble-score/example.go
exercises/scrabble-score/scrabble_score_test.go

A history:
* 1d941e524d25b40d3e8ab452dc1a945423da897b: MULTIBILLIONAIRE
* 9541d7b7b835fb98eef32c281a8931f34b73322b: oxyphenbutazone
(because multibillionaire was too long!)
* But since MULTIBILLIONAIRE was our only word with capital letters, now
we've lost the capability to test solutions for them! So let's bring
it back by putting OXYPHENBUTAZONE in all caps!
Test version is bumped for this.
Closes #270

scrabble-score: capitalize oxyphenbutazone

---

exercises/binary/binary_test.go
exercises/binary/example.go

* alphabetic characters at beginning, middle, end
* invalid digits
Test version is added (was previously unversioned)
Tested by ensuring that a solution that never errors gets a test
failure:
```
--- FAIL: TestParseBinary (0.00s)
binary_test.go:50: ParseBinary(foo101) returned 5 and no error.  Expected an error.
```
Tested by ensuring that a solution that always errors gets a test
failure:
```
--- FAIL: TestParseBinary (0.00s)
binary_test.go:46: ParseBinary(1) returned error "hard drive on fire, cannot convert to binary right now".  Error not expected.
```
Closes #271

binary: Add tests for invalid inputs

---

exercises/hamming/example.go
exercises/hamming/hamming.go
exercises/hamming/hamming_test.go

Tested by first making the example `Distance` return an `*int` instead
of an `error` (without changing the test).
The test passed, indicating that the additional line in the test is
necessary.
Then, the line was added to the test, which caused a compilation error
as hoped. So this is correctly checking that the `err` return value is
indeed an `error`. This is the standard technique in Go for asserting
that a value implements an interface.
This arises out of discussion in #275. This will be an example that will
be used when providing guidance on how to enact the changes for other
exercises.

hamming: Check that err is an error

---

exercises/circular-buffer/circular_buffer.go
exercises/crypto-square/crypto_square.go
exercises/custom-set/custom_set.go
exercises/food-chain/food_chain.go
exercises/paasio/paasio.go
exercises/tournament/tournament.go

As part of discussion in #279, we discovered that these exercises have
three-line stub files that aren't particularly useful (just a package
name and test version).
If we suppose that the purpose of stub files is to help out newcomers to
Go, and that we gradually ease them off of stub files, it seems less
useful to have stub files for exercises that come late in the track. By
that time, students should be able to figure out package names and test
versions themselves.
Affects:
circular-buffer
crypto-square
custom-set
food-chain
paasio
tournament
Closes #279

remove unnecessary stub files

---

.travis.yml

Individual commit messages have more detail. The short of is that we now test:
Required:
* 1.6.1
* 1.5.4
Can fail:
* 1.4.3
* tip

Travis versions

---

bin/test-without-stubs

Otherwise Travis will falsely report test success when instead the test
was failing.
~~We don't immediately exit though; we need to run the cleanup first. This
is noted in a code comment.~~
(Updated to use `trap` instead)
This script was introduced in fa897488609899b977adf95c693f3535c6315321
as part of #249 an initiative to not have build constraints which were
confusing to students.
Luckily we have not had any test failures since then, but it would be
good to restore the right behavior.

test-without-stubs: Signal failure if a test failed

---

.travis.yml

We removed build tags in #249 so it wouldn't make sense for Travis
comments to continue to reference them. It's still true that we can't
use the default install script, so this commit updates the comment to
explain why (our stub/starter files).

travis: we don't install because stubs, not build tags

---

.travis.yml

https://golang.org/doc/devel/release.html#go1.6.minor says it was
released on April 20

travis: 1.6.1 -> 1.6.2

---

config.json

As of https://github.com/exercism/x-common/issues/80 we'd like to keep
the scope of Exercism focused, and counter is the single exercise that
falls under the write-the-test-suite category.

config.json: deprecate counter

---

.gitignore

beam is for Erlang, which has nothing to do with Go.
First discovered in
https://github.com/exercism/xrust/pull/129#discussion_r64982860
Closes #325

gitignore: rm beam

---

exercises/bank-account/bank_account_test.go

Hi, 
the comment of this exercise is wrong. It suggests to declare the function Deposit with a _uint64_ variable in input, but it should be _int64_ instead.
If the function Deposit is implemented using _uint64_ the execution of the test file (specifically at lines 131, 138, 264 where the function is called with a negative variable) causes
>  constant -3 overflows uint64
This is also documented in the [Golang specification](https://golang.org/ref/spec#Constant_expressions):
> uint(-1)     // -1 cannot be represented as a uint
This PR is just a simple fix to the comment :) .

fix comment in bank-account exercise which suggests a wrong input format

---

exercises/clock/clock.go

After reworking clock tests in 0c4961d test version in stub file was not upgraded. This PR fixes that.

clock: bump test version in stub file

---

exercises/grade-school/grade_school_test.go

When I solved the `grade-school` problem it took me a while to piece together the required API from the tests.
For `Grade` the tests construct literals with `{2, []string{"Aimee"}}` so we need to make it a `struct{int, []string}` but the names of the fields are up to the dev.
For `School` we need the methods documented here but the actual type for `School` is flexible so I didn't include it; I just included a placeholder to say you need to have a type named `School` (line 7). I think this could be more clear but I'm not sure what would be best here.

grade-school: Add the minimum required API

---

exercises/binary-search-tree/binary_search_tree_test.go

The fields are accessed directly by the tests so they have to be named just like this. Some people put `left` and `right` on the same line as `left, right *SearchTreeData` but it doesn't really matter.

binary-search-tree: Add Minimum Required API

---

exercises/triangle/example.go
exercises/triangle/triangle_test.go

[A solution I came across](http://exercism.io/submissions/f48a48bf39da400b88da10b148022fd4) suggests a check for
triangle equilaterality that can produce false positives.
The newly added testcase triggers this.

triangle: Add testcase to catch faulty shortcut

---

exercises/allergies/allergies_test.go
exercises/allergies/example.go

Fixes #374.
The `indexOf` function is still using `int` but I don’t know if it’s necessary to change that to `uint`.

allergies: Use unsigned integers (close #374)

---

config.json
exercises/variable-length-quantity/example.go
exercises/variable-length-quantity/variable_length_quantity_test.go

I'm not sure if that shouldn't move this exercise as a problem. I feel that the problem should be more defined so people understand the goal of the exercise.

new exercise to encode/decode variable length quantity

---

exercises/palindrome-products/example.go
exercises/palindrome-products/palindrome_products_test.go

First Hacktoberfest PR. Always wanted to contribute to exercism. 
This should fix #301

Improved error handling behavior for palindrome products test

---

config.json
exercises/acronym/acronym_test.go
exercises/acronym/example.go

This example adds excercise for converting a long name into
three letter acronyms
Fixes https://github.com/exercism/xgo/issues/382
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Acronym: Add acronym excercise

---

exercises/gigasecond/gigasecond_test.go

The PR #222 removed the Birthday variable from the test code, however the comment was not
removed. I got stuck for a few minutes trying to figure out if I needed to pass the variable into the testrunner before I found the PR. This commit simply removes the comment from the test class.

Gigasecond exercise - removes irrelevant comment from test

---

docs/TESTS.md

Both github and http://exercism.io/languages/go/tests renders the placeholder `<regexp>` incorrectly when unquoted. This adds backquotes around the raw text which should fix both.
Specifically, github omits it entirely, and excercism adds `</regexp>` after the period. It seems that the MD renderer is trying to be a bit too helpful by "closing" the "open html tag".

TESTS.md: Make bracketed placeholder render correctly

---

.travis.yml
bin/test-without-stubs
exercises/robot-simulator/defs.go

These are standard tools and it's good to ensure that we are in keeping
with their guidance.
In particular, note that we had a long-standing formatting inconsistency
in the binary exercise's test suite, only recently fixed via
bd156a4b2958e13212480d9755b5bb50b3abd5be. I've since discovered that
that inconsistency was introduced by me, in #274.
In addition, #317 was a problem reported by `go vet`. It seems good to
automatically check for those to prevent any similar errors.
Here is what happens if `bob/example.go` has `yelling != nil` added:
```
example.go:22: comparison of function yelling != nil is always true
please follow the 'go vet' suggestions in exercises/bob
```
Here is what happens if `bob.go` has a few extra spaces added:
```
please run 'go fmt' on exercises/bob
```

test-without-stubs: run go fmt and go vet

---

exercises/food-chain/food_chain_test.go

When the tests for this exercise fail, they print whole verses and all
of the song to the terminal. This can be helpful insofar as the desired
solution is shown in its entirety, which serves as a reference as well
as providing a sense of achievement when the length of the generated
output grows. On the other hand, the overall length of the test output
makes it difficult to spot errors. A lot of scrolling and manual
proof-reading may be required, which makes solving the exercise tedious.
This commit changes the tests to analyze the solution line by line and
append a helpful hint at the bottom of the output of each failed test,
where it can be seen without scrolling. Only the first difference is
highlighted, as a missing line would generate a lot of output otherwise.
Example output: …

food-chain: highlight differences in test output

---

exercises/food-chain/example.go
exercises/food-chain/food_chain_test.go

The current test for the Verses function checks for two consecutive
verses (1 and 2). There are multiple ways to interpret the function
signature and satisfy the test, all observed in submitted solutions:
* Verses(start, end int) string
- return consecutive verses from start to end
* Verses(verses ...int) string
- return n (possibly non-consecutive) verses
* Verses(a, b int) string
- join two (possibly non-consecutive) verses
This commit changes the tested function arguments to cover two non-
consecutive verses (1 and 3). With the change, only the first solution
returning consecutive verses is accepted. The test version is bumped to
keep existing exercise solutions valid.

food-chain: resolve ambiguity in verses test

---

exercises/nucleotide-count/example.go
exercises/nucleotide-count/nucleotide_count_test.go

* use reflect.DeepEqual, instead of custom
* return error if invalid nucleotide
* add comments here and there

nucleotide-count: Some cleaning

---

exercises/house/house_test.go

The description at the top of `house_test.go` can be confusing
and ultimately distracting from the problem at hand. this commit
attempts to replace the (unnecessarily) academic language with
something plainer and more to the point.
I noticed I'm not the only one who had this issue:
http://exercism.io/submissions/3b5b6003f03248f6a402859df52b6381

modify house-test.go comments

---

exercises/acronym/acronym_test.go
exercises/acronym/example.go

I found it very irritating, that the `abbreviate` function name was all lowercase instead of beginning with a cap and [others seem to agree](https://github.com/exercism/xgo/issues/382#issuecomment-253994632), given that this is the main function of the package.
This changes the casing to `Abbreviate`.

Fix case of abbreviate function to be capitalized

---

exercises/house/example.go
exercises/house/house_test.go

Remove `Embed()` function, and enable a non-recursive solution. The test
file still suggests using recursion as a method for solving this
problem, and both recursive and non-recursive solutions are documented
in the `example.go` file. Reading suggestions for recursion in Go have
also been added.
Because of this change a test version number and test have been added.
An extra error check has also been added to the Song() test, https://github.com/bordeltabernacle/xgo/blob/re-implement-house/exercises/house/house_test.go#L130-L134, to check
for the number of verses in the solution. This is to avoid unhelpful test
failure messages when a whole verse is missing, such as:
```
house_test.go:156: Song() line 77 = "", want ""
```
now reads:
```
house_test.go:139: Song() has 11 verses, want 12 …
```

house: re-implement exercise, fixes #242

---

exercises/word-count/cases_test.go
exercises/word-count/example.go
exercises/word-count/word_count.go
exercises/word-count/word_count_test.go

I noticed the test cases for the Go word-count exercises weren't challenging compared to C# and Python (mainly missing apostrophe cases). They were behind the meta cases so I updated them as well as the example to pass.

Update test cases for word-count to match latest meta

---

config.json

We added all-your-base in #404 but forgot to deprecate all the
base-conversion exercises!
According to https://github.com/exercism/x-common/issues/279,
all-your-base is meant to deprecate all of these.

config.json: Deprecate all base-conversions

---

exercises/luhn/example.go
exercises/luhn/luhn_test.go

original PR instigating the changes: https://github.com/exercism/x-common/pull/474

luhn: update tests. fixes #435

---

README.md

In https://github.com/exercism/x-common/pull/125, the x-common
CONTRIBUTING guide was created.
After that, the x-api contributing guide was gutted in
https://github.com/exercism/x-api/commit/a157350c6c9025314be8fbbaf82b90810bd9204e
This means that it doesn't really make sense to link to the x-api
contributing guide anymore - it has very little relevant information for
contributing to this track.
Consider that the template for a new track repository has been updated
so that they link to the x-common CONTRIBUTING guide too, not x-api:
https://github.com/exercism/x-template/commit/5f9143266d05b29317638f45f1cabaccb860e6ca

README: Link to x-common, not x-api, CONTRIBUTING guide

---

exercises/leap/cases_test.go
exercises/leap/example.go
exercises/leap/example_gen.go
exercises/leap/leap.go
exercises/leap/leap_test.go

the filepath needed used by example_gen.go was changed in #224
the test cases were changed in this commit:
https://github.com/exercism/x-common/pull/463

leap: update example_gen.go & test cases

---

README.md
exercises/bob/example_gen.go
exercises/clock/example_gen.go
exercises/connect/example_gen.go
exercises/custom-set/example_gen.go
exercises/gigasecond/example_gen.go
exercises/hamming/example_gen.go
exercises/largest-series-product/example_gen.go
exercises/meetup/example_gen.go
exercises/raindrops/example_gen.go
exercises/rna-transcription/example_gen.go
exercises/roman-numerals/example_gen.go
exercises/word-count/example_gen.go

reference: #447 
README details on generating tests also updated to reflect moving
exercises into exercises subdirectory

update all example_gen.go files and README.md

---

exercises/nucleotide-count/nucleotide_count_test.go

Improve the running time for 'go test -bench .'
by removing StartTimer/StopTimer references.
StopTimer and StartTimer are for excluding startup costs
from a benchmark, but for this benchmark there is no
startup overhead logic to exclude, and the running time
is severely increased by the timer operations.
The observed improvement for the example
is roughly 9x from about 14 seconds to about 1.5 seconds.

nucleotide-count: Decrease benchmark test runtime

---

exercises/custom-set/cases_test.go
exercises/custom-set/custom_set_test.go
exercises/custom-set/example.go
exercises/custom-set/example_gen.go
exercises/custom-set/example_slice.go

updated tests for custom-set #328
for reference:
https://github.com/exercism/x-common/pull/232
https://github.com/exercism/x-common/pull/257

custom-set: update, remove and re-order tests

---

exercises/luhn/luhn_test.go

In the user output string, the args to Fatalf have the `Expected` and
`Got` arguments swapped.

Fix bug in Luhn test output

---

exercises/grains/grains_test.go

This moves the testVersion verification to be the first test.
There is no error handling, so we do not need to adjust any calls to Error / Fatal.
See #470

grains: Ensure consistency with other exercises

---

exercises/error-handling/error_handling_test.go

Moved TestTestVersion to be the first test function.
See #470

error-handling: Ensure test versioning consistency with other exercises

---

exercises/ledger/ledger_test.go

Isolated test version test to its own function preceeding other test function.
See #470

ledger: Ensure test versioning consistency with other exercises

---

exercises/react/example.go
exercises/react/interfaces.go
exercises/react/react_test.go

This makes more sense than returning a CallbackHandle that has to then
get passed into RemoveCallback. It avoids (as in some solutions but not
all) having to cast the CallbackHandle back and forth.
The author of this commit believes this to be more idiomatic Go.

react: Return Canceler from AddCallback

---

exercises/hello-world/example.go
exercises/hello-world/hello_test.go
exercises/hello-world/hello_world.go

The introductory exercise should require as little Go knowledge as
necessary. We'd like to introduce `go test` and `testVersion` here. We
skip introducing the empty string as no string, as this is more specific
knowledge.
https://github.com/exercism/x-common/issues/520
---
I wouldn't recommend merging this until the corresponding change is made in x-common.
Let's get it ready to go before then.

hello-world: simplify to unconditional "Hello, World!"

---

.travis.yml

See individual commit messages.

travis: Upgrade Go versions (1.8 released, 1.7 -> 1.7.5), no longer test 1.6.x, 1.5.x, 1.4.x

---

exercises/series/asktoomuch_test.go
exercises/series/first_test.go
exercises/series/series_test.go

see #414, updated to make the use of strings more apparent, so `[    ]`
will now be `["", "", "", "", ""]`.
All uses of strings have also been changed to use `%q` rather than `%s` to be
consistent.
ie. `first_test.go:20: First(1, "01234") = "".  Want "0".`
rather than
ie. `first_test.go:20: First(1, 01234) = .  Want 0.`
or
ie. `first_test.go:20: First(1, 01234) = "".  Want "0".`

series: update to use `%q`

---

exercises/octal/octal_test.go

* Relocated test versioning function to start of tests
* Errorf -> fatalf
See #470

octal: Ensure test versioning consistency with other exercises

---

README.md

After reading https://github.com/exercism/discussions/issues/121 I
though it might be beneficial to add something to the README regarding
benchmarking on different machines. This led, as these things do, to a
small, opinionated rewrite of the xgo style section.

README.md: update xgo style section

---

exercises/error-handling/error_handling_test.go

from commit mesages:
remove unnecessary comments  …
see https://github.com/exercism/xgo/pull/507#pullrequestreview-21705385
fix golint complaints  …
"if block ends with a return statement, so drop this else and outdent its block"

error-handling: update test file

---

exercises/luhn/cases_test.go
exercises/luhn/example.go
exercises/luhn/example_gen.go
exercises/luhn/luhn_test.go

Add an example_gen.go testCases generator to generate the testCases from
the x-common canonical data. Generate the new testCases data and update
the example to pass the new test data. Bump the testVersion to 2.

luhn: update test files

---

exercises/accumulate/accumulate_test.go

see #414
Also removed unnecessary else block

accumulate: update tests

---

bin/test-without-stubs
exercises/beer-song/example.go
exercises/binary-search/binary_search_test.go
exercises/grade-school/grade_school_test.go
exercises/minesweeper/minesweeper_test.go

- used https://github.com/client9/misspell

test-without-stubs,exercises: Typo fixes

---

exercises/accumulate/accumulate.go

Did not find any history of accumulate.go not being here being intentional.

accumulate: add initial file with test version and function stub

---

exercises/change/change_test.go

As part of #275
Good opportunity to discuss: Do we still want to keep doing things like this to ensure that return values are of type `error`, or are we OK with assuming the student understands this by the time they get to a certain point in the track?

change: Require err to be error by calling Error

---

exercises/variable-length-quantity/example.go
exercises/variable-length-quantity/variable_length_quantity_test.go

I noticed when I did the exercise that the `size` output that the tests expect is off by one except in the first test case.

variable-length-quantity: return correct size from DecodeVarint

---

exercises/bank-account/bank_account_test.go

It's minor one, but as it may be used as scaffold for function definition.

bank-account: Fix typo in the function signature

---

exercises/luhn/.meta/gen.go
exercises/luhn/cases_test.go

Use .Header in generator template.
Change Valid => Cases to align template with latest canonical-data.json.

luhn: update generator

---

README.md
gen/gen.go

see https://github.com/exercism/xgo/pull/606#discussion_r109292703
This is a very rough WIP, but I wanted to open it up to get feedback as this is new territory for me.
As it is now, the `Gen()` function will opt to retrieve the canonical data from a local source, but if this isn't available will then try to retrieve it remotely from the x-common Github repo. Is this best? Should it try remotely first?
Feel free to recommend better methods/style etc.

gen.go: collect canonical-data.json remotely

---

exercises/bob/bob.go
exercises/clock/clock.go
exercises/gigasecond/gigasecond.go
exercises/hamming/hamming.go
exercises/raindrops/raindrops.go
exercises/triangle/triangle.go

I noticed the stub file for gigasecond had a `?` for the `testVersion` const, which I though was a bit odd in comparison to the other stub files, and then ended up with an attempt to make the stubs a little more consistent.

Update stub files

---

exercises/palindrome-products/example.go
exercises/palindrome-products/palindrome_products_test.go
exercises/roman-numerals/example.go

following on from https://github.com/exercism/xgo/issues/552#issuecomment-287762076
There are a couple of `golint` errors we can live with; `expected type, found newline`, where a stub file is asking the user to complete the type definition:
```go
// Notice it returns this type.  Pick something suitable.
type Kind
```

fix golint errors

---

gen/gen.go

this commit changes the feedback about the local source so that the full
path to the file is returned rather than just the path to the x-common
dir, for example:
from this:
`2017/04/19 12:23:36 [LOCAL] source: /home/rob/code/go/src/github.com/robphoenix/x-common`
to this:
`2017/04/19 12:23:36 [LOCAL] source: /home/rob/code/go/src/github.com/robphoenix/x-common/exercises/leap/canonical-data.json`

gen.go: be more explicit about local source

---

exercises/custom-set/.meta/gen.go
exercises/custom-set/cases_test.go
exercises/custom-set/custom_set_test.go

Use .Header in generator template.
Align template with latest canonical-data.json.
Use a OneCase struct type to contain the whole
set of possible json objects for the various
test groups.
Add istrSlice as conversion helper for .Expected.

custom-set: update generator

---

exercises/house/house_test.go

This prefixes the simple names verse and song with "expected" thus freeing up
the more obvious names to be used in the solution without causing the error that
the names are already used in the test suite.

house: change variable names in test to avoid potential collision

---

exercises/connect/.meta/gen.go
exercises/connect/cases_test.go
exercises/meetup/.meta/gen.go
exercises/meetup/cases_test.go
exercises/rna-transcription/.meta/gen.go
exercises/rna-transcription/cases_test.go
exercises/roman-numerals/.meta/gen.go
exercises/roman-numerals/cases_test.go
exercises/transpose/.meta/gen.go
exercises/transpose/cases_test.go
exercises/word-count/.meta/gen.go
exercises/word-count/cases_test.go

These 6 exercises have generators that only need 1 change to be current, that is
to use the .Header in the template:
connect
meetup
rna-transcription
roman-numerals
transpose
word-count

Update 6 exercise test case generators to use .Header

---

exercises/pascals-triangle/pascals_triangle_test.go

Added two benchmarks to the pascals triangle test.
One notable side-effect is that I moved the size of the test from hard-coded to
an independent variable so that it may be used as the size for the fixed length
test and upper bound for the incremental size test.

pascals-triangle: add benchmarks

---

exercises/hamming/.meta/gen.go
exercises/hamming/cases_test.go
exercises/hamming/example.go
exercises/hamming/hamming_test.go

For issue #632
The generated cases_test.go has a new test case from canonical-data.json,
so update the test program and example solution to bump
testVersion and targetTestVersion to 6.

hamming: update generator

---

exercises/transpose/transpose_test.go

Test for exercise transpose now correctly handles the corner case where one of actual and expected results is zero length causes the test to pass.
This issue has been reported in:
https://github.com/exercism/xgo/issues/651
I have run the tests to ensure there is no regression.

Test for exercise transpose now correctly handles corner case

---

exercises/raindrops/.meta/gen.go
exercises/raindrops/cases_test.go
exercises/raindrops/example.go
exercises/raindrops/raindrops.go
exercises/raindrops/raindrops_test.go

Resolves #637
This picks up three new test cases from canonical-data.json,
so bump testVersion/targetTestVersion in the test program, stub,
and example solution from 2 to 3.

raindrops: update generator

---

exercises/bob/.meta/gen.go
exercises/bob/bob.go
exercises/bob/bob_test.go
exercises/bob/cases_test.go
exercises/bob/example.go

Resolves #624
Test cases changed using latest canonical-data.json,
so bump testVersion/targetTestVersion in the test program, stub,
and example solution from 2 to 3.

bob: update generator

---

gen/gen.go

This has been replaced by the `Origin` field. Closes #642

gen.go: delete `Ori` field

---

exercises/series/asktoomuch_test.go
exercises/series/example.go
exercises/series/first_example.go
exercises/series/first_test.go
exercises/series/series_test.go

This exercise had a package name which was odd compared to the other
exercises in the track: it did not contain any part of the exercise name.
In fact it seems to be the name of the core concept behind the probable
solution in Go.
This also updates the test version since the test would now be in a
different package.

series: change package name to better reflect exercise name

---

exercises/phone-number/.meta/gen.go
exercises/phone-number/cases_test.go
exercises/phone-number/example.go
exercises/phone-number/phone_number_test.go

Phone number add generator

---

exercises/scrabble-score/.meta/gen.go
exercises/scrabble-score/cases_test.go
exercises/scrabble-score/example.go
exercises/scrabble-score/scrabble_score_test.go

Generate a test case array from the canonical-data.json.
Update test program to reference the array from cases_test.go.
Increment testVersion and targetTestVersion because of new test cases.
For issue #605

scrabble-score: create test case generator

---

exercises/atbash-cipher/.meta/gen.go
exercises/atbash-cipher/atbash_cipher_test.go
exercises/atbash-cipher/cases_test.go
exercises/atbash-cipher/example.go

Generate test case array from the canonical-data.json.
Update test program.
Increment testVersion and targetTestVersion.
For #605

atbash-cipher: create test case generator

---

README.md

Issue #420 asked us to consider using Example tests for some exercises.
This was discussed in #420 & #675 and resulted in implementations in #568
This commit clarifies the view of the current maintainers that example
tests are not necessarily useful as a replacement for data-driven tests,
but rather as a way to illustrate and verify the API of an exercise.
closes #420

README: clarify intentions of Example tests

---

exercises/variable-length-quantity/.meta/gen.go
exercises/variable-length-quantity/cases_test.go
exercises/variable-length-quantity/example.go
exercises/variable-length-quantity/variable_length_quantity_test.go

For #605
Generate two test case arrays, one for encode and
one for decode, from the canonical-data.json.
Update example solution to pass the tests.
The API changed to use slices in order to match
the canonical-data.json test cases.
Retain the old functions but rename to decodeInt and encodeInt
and utilize these as helpers to support the new slice based API.
Update test program to use generated test case arrays.
Increment testVersion and targetTestVersion in
example solution and test program.

variable-length-quantity: create test case generator

---

exercises/tree-building/tree_test.go

While working on the tree building exercism, I noticed that the debug output for expected and actual results was backwards.  This is fixed here.

tree-building: Fix test error output order

---

exercises/variable-length-quantity/.meta/gen.go
exercises/variable-length-quantity/cases_test.go
exercises/variable-length-quantity/example.go
exercises/variable-length-quantity/variable_length_quantity_test.go

Since it was introduced in #322, the decode function returns the number
of bytes decoded. The creator of the exercise mentioned that it was to
be consistent with the standard library's API.
Go standard library example for returning number of bytes:
https://golang.org/pkg/io/#Writer
Now, since #674, it is required that the entire input array be decoded,
or else it is an error. Now the number of bytes decoded doesn't make
much sense to return, since now it is known that it will always be the
length of the input.
Go standard library example for not returning number of bytes (decoding
everything):
https://golang.org/pkg/encoding/json/#Unmarshal
testVersion -> 4
Closes #683

variable-length-quantity: Decode: don't return/test length

---

exercises/sum-of-multiples/.meta/gen.go
exercises/sum-of-multiples/cases_test.go
exercises/sum-of-multiples/example.go
exercises/sum-of-multiples/sum_of_multiples_test.go

Generate test case array from the canonical-data.json.
Increment testVersion and targetTestVersion in
example solution and test program.
For #605.

sum-of-multiples: create test case generator

---

exercises/acronym/.meta/gen.go
exercises/acronym/acronym_test.go
exercises/acronym/cases_test.go
exercises/acronym/example.go

Generate stringTestCases array from the canonical-data.json.
Update test program to use the generated stringTestCases array.
Increment testVersion and targetTestVersion in
example solution and test program.
For #605.

acronym: create test case generator

---

exercises/secret-handshake/.meta/gen.go
exercises/secret-handshake/cases_test.go
exercises/secret-handshake/example.go
exercises/secret-handshake/secret_handshake_test.go

Generate tests array from the canonical-data.json.
Update test program to use the generated tests array.
Increment testVersion and targetTestVersion in
example solution and test program.
For #605.

secret-handshake: create test case generator

---

README.md
config.json
exercises/gigasecond/gigasecond_test.go
gen/gen.go

The leading 'x' is kind of arbitrary. Especially now that we can set
topics on the repositories, we don't need a pattern to distinguish what
is a track or not.
See https://github.com/exercism/meta/issues/1

Remove leading 'x' from repository name

---

exercises/clock/.meta/gen.go
exercises/clock/cases_test.go
gen/gen.go
gen/property.go

~~This PR should not be merged yet... but it should still be reviewed, to see how close to being mergeable it is.~~
This PR is probably ready to merge, but I'll clean up some commits and move the history to a different branch.
The question to ask is: "Would I rather write a generator using this interface than the existing one?"
---
Seeing how this looks. I'm not convinced it's better, but maybe it can be used as a starting point to make things better. That is why I say do not merge, but if we get a good idea out of it it could be.
Clock updated to 1.0.1 and I have code that works for it too, but I want to compare clock 1.0.0 code vs clock 1.0.0 code, so I reverted the 1.0.1 changes (they can be applied later)

clock: restore type-safety for different types of cases

---

exercises/perfect-numbers/perfect_numbers_test.go

As issue #712 lays out, this test makes sure that the constants created from the Classification interface, will not equal each other providing a false positive for `go test`.

Fixed perfect_number false positive and equaling types. Closes #712

---

.travis.yml

We will be adding subcommands to configlet.
For now, we've released a version of configlet which handles both the
old command:
configlet path/to/track
as well as the new command:
configlet lint path/to/track
This will let us update all the travis files to include the
subcommand before we release the version of configlet that requires
the subcommand.
See https://github.com/exercism/configlet/pull/23

Support a subcommand on configlet in CI

---

.gitignore
README.md

This allows contributors to use local .editorconfig files to bring
their editors into compliance with repo style. See tabs/spaces in #714.
Closes #722

Ignore .editorconfig file

---

exercises/bank-account/bank_account_test.go

Given that locking seems to be the solution for the problem, I think
benchmarking could be a real interesting add-on to this specific
exercise.

bank-account: add benchmarks

---

config.json

Crypto is a more accurate topic for the text encoding/decoding exercises.

config.json: Add "Cryptography" & remove "Security"

---

exercises/pangram/example.go
exercises/pangram/pangram.go
exercises/pangram/pangram_test.go

This brings the tests into consistency with the README.
Resolves #801, also see #802

pangram: Remove non-ASCII compatible test cases

---

exercises/leap/leap.go
exercises/leap/leap_test.go

In a separate pull request, I'm simplifying hello-world. That removed
the explanation of what testVersion is.
This adds it to leap exercise so that people get the explanation.

leap: explain testVersion

---

config.json
exercises/two-fer/README.md
exercises/two-fer/example.go
exercises/two-fer/example_two_fer_test.go
exercises/two-fer/two_fer.go
exercises/two-fer/two_fer_test.go

This adds the exercise that replaced the old conditional version of Hello World.
I also added the Example Test here. I considered using _only_ an example test, but figured I'd play it safe and go with what we used to have for Hello World.
I did not add the testVersion–we're going to be able to get rid of this book-keeping in the near future, and my fingers are crossed hoping that we won't need to update two-fer in the meantime.
This gives us a fairly gentle ramp-up:
- `hello-world`:, just wire everything together and get a test passing
- `two-fer`: some more explanatory comments in in the stub file and an example test
- `leap`: introduce `testVersion`

Add two-fer exercise

---

config/maintainers.json

As noted in https://github.com/exercism/go/issues/719 I cannot currently
fulfill my duties as a maintainer of this track, so it is right and
proper to mark myself as an alumnus as a result.
I will do as Katrina did in https://github.com/exercism/go/pull/797 and
submit a bio for myself. I think this is suitable for showing on the
website (by the way, Katrina's currently isn't being shown).

maintainers: add my bio as an alumnus

---

exercises/secret-handshake/secret_handshake_test.go

It would seem to be a better speed analysis of the routine if we try more than just `Handshake(31)`
This is especially true when you consider there could be two code paths, or significant overhead depending on how the reverse functionality is handled.
I suspect do not need to bump the `targetTestVersion` since the test cases remain the same.

Improve Handshake Benchmark Test

---

exercises/error-handling/.meta/description.md
exercises/error-handling/.meta/hints.md
exercises/error-handling/.meta/metadata.yml
exercises/error-handling/README.md
exercises/error-handling/common.go
exercises/error-handling/error_handling_test.go

Originally added for #703, moved the longer description for the
exercise to the README using the new `.meta/` files enabled via
`configlet` v3+. Links have been moved into markdown format, some
language has been updated as well.
Resolves #833

error-handling: move detailed exercise description to README

---

exercises/simple-cipher/.meta/description.md
exercises/simple-cipher/.meta/hints.md
exercises/simple-cipher/.meta/metadata.yml
exercises/simple-cipher/README.md
exercises/simple-cipher/simple_cipher_test.go

Clear up the expected implementation details for the simple-cipher
exercise in the README. Provide more explanation of the Vigenère
cipher. Moved README updates into .meta/ directory and regenerated the
README.
Resolves #786

simple-cipher: update README to reflect exercise implementation 

---

exercises/series/.meta/hints.md

Moved information on bonus exercise and build tags from the main test file
to the README. Also added info about the `ok bool` pattern.
Resolves #804

series: Move bonus instructions to README

---

exercises/roman-numerals/example.go
exercises/roman-numerals/roman_numerals_test.go

Removed extra test cases to bring the roman-numeral exercise into
consistency with the problem-specifications description. Bumped test
version accordingly.
Resolves #836

roman-numerals: remove non-canonical test data

---

README.md

Already found a mistake :frowning:. I neglected to fully change `exercise-slug` to `fizzbuzz`.

README: Change exercise-slug to fizzbuzz in examples

---

exercises/robot-simulator/robot_simulator_step2_test.go

The big glaring fix is the change `s/rolls/roles/`. But also, be consistent in use of the Oxford comma and tense.

robot-simulator: Update grammar and wording

---

gen/gen.go

Using Go 1.9 with test case generators breaks
the placement of the output file, cases_test.go.
Specifically, on Linux it is output to ../cases_test.go which is
relative to your current directory.
The bug is related to the fact that with Go 1.9, this line
if _, path, _, ok := runtime.Caller(2); ok {
when called from init() within a package
has a different result than 1.8.3 and earlier.
Path is returned as ```<autogenerated>``` with 1.9,
and dirExercise ends up being set to "..".
The correct solution for both new and previous Go versions
is to utilize the same technique of runtime.Caller(),
but from a known call stack position apart from the init() function.
The change moves the logic to set dirExercise
from init() into the Gen() function in order to
set a correct value for the exercise …

gen/gen.go: correct location for cases_test.go

---

config.json

I've made some changes based on discussions in #829 
This PR is mostly to continue that discussion than anything else.
Would be good to have Raindrops unlock another exercise.

[nextercism] Restructure config.json

---

.travis.yml

1.9 was released on 24 August 2017:
https://golang.org/doc/go1.9
1.8.3 was released on 24 May 2017:
https://golang.org/doc/devel/release.html#go1.8.minor
This keeps up with the policy of only testing the
current & previous release.

travis: upgrade Go version

---

exercises/word-search/.meta/gen.go
exercises/word-search/cases_test.go
exercises/word-search/word_search_test.go

word-search: create test case generator

---

exercises/anagram/.gitignore
exercises/anagram/.meta/gen.go
exercises/anagram/anagram_test.go
exercises/anagram/cases_test.go

For #605
I did not have a way to wake up #695 so I started a new one.
This generator mimics the output of the connect generator so the output is
a little nicer IMHO. I bumped the `testVersion`.

anagram: Add test generator

---

gen/gen.go

When remote problem-specifications repository is used
as the source of the canonical-data.json, and the commit entry
retrieved has a multi-line message, the generator
uses the entire multi-line message in the source comment output;
this causes a compile error in the generated cases_test.go.
Correct bug by using only the first line of the commit message
in returned string from getRemoteCommit.
Closes #874

generator: handle multi-line commit - issue #874

---

exercises/hamming/.meta/hints.md
exercises/hamming/README.md
exercises/leap/.meta/hints.md
exercises/leap/README.md

The user may encounter the `cases_test.go` first in `leap` as an
unlock or in `hamming` in core. We add a explanation of the file's
purpose in the `hamming` README and link to it in the `leap` README.
Resolves #824

Explain cases_test.go file where it may first be encountered

---

exercises/prime-factors/prime_factors_test.go

See #866 
This improves the test formatting in the case where an empty slice is wanted but a nil slice is given.
From:
```
--- FAIL: TestPrimeFactors (0.00s)
prime_factors_test.go:31: prime.Factors(1) = []; expected []
```
To:
```
--- FAIL: TestPrimeFactors (0.00s)
prime_factors_test.go:31: prime.Factors(1) = []int64(nil); expected []int64{}
```

prime-factors: improve test formatting

---

exercises/change/change_test.go

See #866
This improves the test formatting in the case where an empty slice is wanted but a nil slice is given.
From:
```
--- FAIL: TestChange (0.00s)
change_test.go:17: no coins make 0 change : Change([1 5 10 21 25], 0): expected [], actual []
```
To:
```
--- FAIL: TestChange (0.00s)
change_test.go:17: no coins make 0 change : Change([1 5 10 21 25], 0): expected []int{}, actual []int(nil)
```

change: improve error formatting

---

exercises/say/.gitignore
exercises/say/.meta/gen.go
exercises/say/cases_test.go
exercises/say/example.go
exercises/say/say_test.go

This brings the Go track in line with others. `Say` now returns `(string, bool)` so it can indicate when a value is out of range.
Part of #605.
Closes #837

say: generate tests

---

README.md

confliglet has been updated to no longer require the `metadata.yml` and
`description.md` file to both be present for either to work. Removed the
blurb describing this requirement from our README.
See: https://github.com/exercism/configlet/pull/84

README: remove configlet metadata coupling requirement

---

config.json
exercises/isbn-verifier/README.md
exercises/isbn-verifier/example.go
exercises/isbn-verifier/isbn_verifier_test.go

Dear community,
Hi, I'm Masa, opened #906.
Sorry for delaying implementation and any inconvenience I've been causing.
I didn't mean that I closed #906. I didn't know PR gets closed when I delete rerated branch.
And now I send the files again. 
I really appreciate taking your time. Thanks.
Masa

isbn-verifier: add new exercise

---

exercises/isogram/.meta/gen.go
exercises/isogram/cases_test.go
exercises/isogram/isogram_test.go

isogram: add test generator

---

exercises/run-length-encoding/.meta/gen.go
exercises/run-length-encoding/cases_test.go
exercises/run-length-encoding/run_length_encoding_test.go

Update test program to use generated test case arrays.
For #605.

run-length-encoding: create test case generator

---

exercises/perfect-numbers/.meta/gen.go
exercises/perfect-numbers/cases_test.go
exercises/perfect-numbers/example.go
exercises/perfect-numbers/perfect_numbers_test.go

Keep TestGivesPositiveRequiredError redundant test on zero
since it verifies ErrOnlyPositive.
Update example solution to use int64 for input type
since -1 test case in canonical-data.json.
For #605.

perfect-numbers: create test case generator

---

exercises/perfect-numbers/.meta/hints.md
exercises/perfect-numbers/README.md

The README fo perfect-numbers is lacking in
specific instructions regarding the required elements
needed to be compliant with the test program.
Add a .meta/hints.md which more clearly states
the expected elements of the perfect-numbers exercise.
Best if merged after #952 since it reflects a related change to int64.

perfect-numbers: add hints.md

---

exercises/isbn-verifier/.meta/gen.go
exercises/isbn-verifier/cases_test.go
exercises/isbn-verifier/example.go
exercises/isbn-verifier/isbn_verifier_test.go

Make one correction to pass the 'X is only valid as a check digit'
test case from canonical-data.json.
Output FAIL and PASS in test output.
For #605.

isbn-verifier: create test case generator

---

exercises/collatz-conjecture/.meta/gen.go
exercises/collatz-conjecture/cases_test.go
exercises/collatz-conjecture/collatz_conjecture_test.go

Make use of zero-value of expectError bool.
For #605.

collatz-conjecture: add generator

---

exercises/space-age/space_age_test.go

The expected age values are specified (in respective canonical-data.json) with 2-digit precision (e.g., 31.69), while the actual result is a float.
Instead of forcing the solution to perform an arbitrary rounding, the test code verifies the result with certain precision (currently same 2-digit, for compatibility - can be eventually added to canonical-data.json itself).
Aligned with the conclusion of the discussion in exercism/problem-specifications#880

space-age: do not force rounding of solutions

---

exercises/grains/.meta/gen.go
exercises/grains/cases_test.go
exercises/grains/grains_test.go

Make use of zero-value of expectError bool.
The test case value for the 'Total()' is retained in TestTotal()
since there wasn't an array of cases in the canonical-data.json
for the 'total' property, and there is only one valid return value.
For #605.

grains: add generator

---

exercises/prime-factors/.meta/gen.go
exercises/prime-factors/cases_test.go
exercises/prime-factors/prime_factors_test.go

Output FAIL and PASS in test output.
For #605.

prime-factors: add generator

---

exercises/all-your-base/.meta/gen.go
exercises/all-your-base/.meta/hints.md
exercises/all-your-base/README.md
exercises/all-your-base/all_your_base_test.go
exercises/all-your-base/cases_test.go
exercises/all-your-base/example.go

- with putting assumption into hints

all-your-base: add test generator

---

exercises/kindergarten-garden/kindergarten_garden_test.go

This commit fixes #975. The original `t.Skip()` call included the use of formatting directives. These were caught in the tests run against Go: tip. It looks like the formatting directives are intended and so the call was updated to use `t.Skipf()` fixing the issue.

kindergarten-garden: Use Skipf to display formatting directives

---

exercises/acronym/example.go

- because passed argument is already string

acronym: drop fmt in example

---

exercises/connect/example.go

* drop unnecessary type conversion, `len` already returns int
* don't shadow type

connect: improvements in example solution

---

config.json
exercises/armstrong-numbers/.meta/gen.go
exercises/armstrong-numbers/armstrong_test.go
exercises/armstrong-numbers/cases_test.go
exercises/armstrong-numbers/example.go

implemented exercise about 'armstrong numbers' in go . Fixes issue #969

armstrong-numbers: add exercise with generator (#969)

---

exercises/acronym/acronym.go

A previous PR (#860) introduced a duplicated definition for the Abbreviate function in the acronym exercise.

acronym: Remove duplicated function definition

---

exercises/all-your-base/.meta/gen.go
exercises/all-your-base/cases_test.go

all-your-base: update generator to new input schema

---

exercises/allergies/.meta/gen.go
exercises/allergies/cases_test.go

allergies: update generator to new input schema

---

exercises/anagram/.meta/gen.go
exercises/anagram/cases_test.go

anagram: update generator to new input schema

---

exercises/binary-search/.meta/gen.go
exercises/binary-search/cases_test.go

binary-search: update generator to new input schema

---

exercises/book-store/.meta/gen.go
exercises/book-store/cases_test.go

book-store: update generator to new input schema

---

exercises/simple-cipher/simple_cipher_test.go

Fix the reported error message in [line 99](https://github.com/exercism/go/blob/master/exercises/simple-cipher/simple_cipher_test.go#L99) where it should be `t.Fatalf` instead of `t.Fatal`

simple-cipher: fix error formatting in test

---

exercises/pig-latin/.meta/gen.go
exercises/pig-latin/cases_test.go
exercises/pig-latin/example.go
exercises/pig-latin/pig_latin_test.go

pig-latin: add generator and update example 

---

exercises/all-your-base/all_your_base_test.go

The current test for `all-your-base` compares the outputs even in the erroneous case, which won't let some correct solutions to pass. I'm changing this test to behave like other exercises: only check output in non-error test cases.

all-your-base: fix checker to ignore output in error case

---

exercises/tree-building/tree_test.go

Input with duplicate nodes should not be valid even if the nodes themselves are. 
Added one case for a generic duplicate node and another for a duplicate root node, to prevent comparison against zero value (either of ID or of Record) when checking for dupes.

tree-building: add test cases for duplicate nodes

---

exercises/atbash-cipher/.meta/gen.go
exercises/atbash-cipher/cases_test.go

atbash-cipher: update generator to new input schema

---

exercises/change/.meta/gen.go
exercises/change/cases_test.go

change: update generator to new input schema

---

exercises/collatz-conjecture/.meta/gen.go
exercises/collatz-conjecture/cases_test.go

collatz-conjecture: update generator to new input schema

---

exercises/connect/.meta/gen.go
exercises/connect/cases_test.go

connect: update generator to new input schema

---

exercises/meetup/.meta/gen.go
exercises/meetup/cases_test.go

Convert expected field in canonical-data.json to
day number to be compatible with exercise.

meetup: update generator to new input schema

---

exercises/phone-number/cases_test.go

From generator run, update cases_test.go with two
new edge test cases from canonical-data.json
with invalid area-code and exchange numbers.

phone-number: new test cases

---

exercises/bowling/.meta/gen.go
exercises/bowling/cases_test.go

bowling: update generator to new input schema

---

exercises/book-store/.meta/gen.go
exercises/book-store/.meta/hints.md
exercises/book-store/README.md
exercises/book-store/cases_test.go
exercises/book-store/example.go

Update generator for latest canonical-data.json
which uses integer expected values instead of floating point.
Update exercise to use type int for Cost output.
Add hints.md for guidance.
Update README.md.

book-store: use fixed point output

---

exercises/accumulate/accumulate_test.go
exercises/allergies/allergies_test.go
exercises/anagram/anagram_test.go
exercises/atbash-cipher/atbash_cipher_test.go
exercises/beer-song/beer_test.go
exercises/bob/bob_test.go
exercises/bracket-push/bracket_push_test.go
exercises/change/change_test.go
exercises/etl/etl_test.go
exercises/grains/grains_test.go
exercises/isogram/isogram_test.go
exercises/octal/octal_test.go
exercises/phone-number/phone_number_test.go
exercises/transpose/transpose_test.go

Initial conversation: https://github.com/exercism/go/pull/1011/files/0af38ee4b324bee573ba1debc174cfde5bde6717#r160101420

exercises: fix loop ordering in benchmarks

---

README.md

The large number of exercises in now causing throttling to kick in
when using the generator tool. This can be avoided by using a local
copy of the `problem-specification` repository. I added an emphasis on
this point.
Resolves #1025

readme: Add recommendation for local problem-spec repo

---

exercises/custom-set/.meta/gen.go
exercises/custom-set/cases_test.go

custom-set: update generator to new input schema

---

exercises/parallel-letter-frequency/.meta/hints.md
exercises/parallel-letter-frequency/README.md

An attempt to clear up some confusion as to why Go uses the term
"concurrent" where most languages use "parallel".
Resolves #1023

parallel-letter-frequency: Add parallel vs concurrent info to README

---

exercises/roman-numerals/.meta/gen.go
exercises/roman-numerals/cases_test.go

Handle new input scheme.
Pick up new test case for double-normalization.

roman-numerals: update generator for new input scheme

---

exercises/clock/.meta/gen.go
exercises/clock/cases_test.go
exercises/clock/clock_test.go
exercises/clock/example.go
exercises/clock/example_clock_test.go

The problem-specifications canonical-data.json was updated
to define separate subtract property test cases and also indicated
that the exercise should include a Subtract function.
Update generator to recognize "subtract" property separately
and output subtractTests; also update for the new "input" schema.
Update example solution to implement Subtract operation.
Update test program to call Subtract operation
in TestSubtractMinutes and add BenchmarkSubtractMinutes.

clock: extend exercise with Subtract operation

---

exercises/raindrops/README.md
exercises/space-age/.meta/hints.md
exercises/space-age/README.md
exercises/twelve-days/README.md

Moved information about not having stubs available to two locations:
`raindrops` and `space-age`, either may be the first encounter of a no
stub exercise. The former on the core track the latter as a bonus
exercise. Also removed the no stub info from `twelve days`. Also added
a `hints.md` style notice for `space-age` and regenerated the READMEs
for `raindrops` and `space-age`.
Resolves #1049, see also #1048.

exercises: move no stub information to first encounter exercise's README

---

exercises/clock/clock_test.go

This fix is for an incorrect error message in the TestSubtractMinutes test.
See issue #1052

clock: fix incorrect test error message

---

exercises/armstrong-numbers/README.md

In preparation for [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) we're updating Configlet—our Exercism track linter—to require that we generate the exercise README. This is because in v2 we will not be generating READMEs on the fly, but deliver the README as defined in the directory for each implementation.
I'm going to go ahead and merge this as soon as the build passes, as this is janitorial work rather than a language-specific change.
See https://github.com/exercism/configlet/issues/116 for more details.

armstrong-numbers: Generate missing exercise README

---

exercises/reverse-string/.meta/gen.go
exercises/reverse-string/cases_test.go
exercises/reverse-string/reverse_string_test.go

Add reverseTestCase type in generator output to be
used in the test program.
Since file cases_test.go is generated from
problem-specifications/exercises/reverse-string/canonical-data.json,
add an additional test case for UTF-8 within the test program.
Resolves #1068

reverse-string: add UTF-8 multibyte test case

---

exercises/simple-linked-list/linked_list_test.go

Running go test -bench on this exercise is taking
far too much time (several minutes).
Improve the benchmark routines by
doing the list creation outside the loop
and using ResetTimer; this applies to routines
BenchmarkNewList,
BenchmarkListSize,
BenchmarkListToArray, and
BenchmarkListReverse.
For BenchmarkListPush and BenchmarkListPop,
use an inner loop to measure 100 instances
of the respective Push or Pop operations.
This approach reduces the overhead runtime in relation
to the operations being measured.
Resolves #1073

simple-linked-list: improve benchmark runtime

---

exercises/paasio/paasio_test.go

When looking at solutions to the paasio exercise I found many that accessed the counter variables (n, nops) without locking the mutex. So even though the increment of the two variables was protected, reading them consistently had a data race. So here is a testcase that checks that {ReadCount,WriteCount} returns consistent values if several go routines read/write in parallel.

paasio: test for unprotected access to counters

---

exercises/crypto-square/crypto_square_test.go
exercises/crypto-square/example.go

The exercise description inside the readme calls for padding with
trailing spaces on the last n chunks if the message does not perfectly
fill the calculated rectangle.  This commit fixes the testcases and the
example implementation.
Fixes: https://github.com/exercism/go/issues/1086

crypto-square: add spaces if text does not fill rectangle

---

exercises/dominoes/.meta/gen.go
exercises/dominoes/.meta/hints.md
exercises/dominoes/README.md
exercises/dominoes/cases_test.go
exercises/dominoes/dominoes_test.go
exercises/dominoes/example.go

The correct spelling is "Domino" for the singular and "Dominoes" for the plural.
This patch changes the spelling in the code and documentation without changing the functionality at all.

Spelling Dominoe -> Domino

---

config.json

The tree structure of exercises is only allowed to be two exercises
deep. Ours was unlimited. I moved any unlocked deeper than core to be
unlocked by its root core exercise.
Resolves #1093

config.json: Flatten exercise tree

---

exercises/all-your-base/cases_test.go
exercises/word-count/cases_test.go
exercises/yacht/cases_test.go

The commit headers in the cases_test.go of three exercises are updated.
all-your-base also receives an inputDigits change with no impact.

Generator cases commit updates for all-your-base, word-count, and yacht

---

exercises/bank-account/bank_account_test.go

Member functions should receive Pointers, so the don't receive a copy
of the actual bank account.
I started with the boilerplate from `bank_account_tests.go` and wondered why my tests failed:
```go
➜ bank-account$ go test
--- FAIL: TestSeqOpenDepositClose (0.00s)
bank_account_test.go:77: Account 'a' opened with initial balance of 10.
bank_account_test.go:88: Deposit of 20 accepted to account 'a'
bank_account_test.go:95: a.Close() returned payout = 10, want 30.
--- FAIL: TestMoreSeqCases (0.00s)
bank_account_test.go:113: Account 'a' opened with initial balance of 10.
bank_account_test.go:120: Account 'z' opened with initial balance of 0.
bank_account_test.go:151: Withdrawal of 3 accepted from account 'a'
bank_account_test.go:161: a.Balance() = 10, want 7
```

Fix misleading comments abount member function

---

.travis.yml

For travis-ci, the 1.x is picking up version 1.11beta1 instead of 1.10.3.
The go fmt changes for 1.11beta1 is breaking all PRs
because of the STATIC_CHECKERS using 1.11beta1 since
it has a go fmt change that exercise scrabble-score fails on.
Use 1.10.x instead of 1.x to avoid 1.11beta1 in the short term.
TODO: revisit any necessary 'go fmt' changes for STATIC_CHECKERS
after version 1.11 releases.

.travis.yml: use go version 1.10.x

---

exercises/triangle/triangle.go

Correct comments in stub file to reference the correct package and function name. 
This closes #1123

triangle: Fix references to twofer in stub comments

---

exercises/protein-translation/example.go
exercises/protein-translation/protein_translation_test.go

Here's my initial pass at a solution for #1132 
Since protein-translation is unlocked by scrabble-score, I thought it was fair game to keep the tests for `FromCodon`, but include the error logic in the tests (and, of course, the example solution). I drew heavily from the golang standard library in designing the solution, but who knows what I may have mangled along the way 😄

protein-translation: add errors logic

---

exercises/two-fer/two_fer.go

Not sure if this was intentional, but adding missing parameter name to exercise file.

two-fer: add param name to stub function

---

exercises/list-ops/listops_test.go

Fixes small naming issue : #1145 .

list-ops: Corrected name of test case

---

exercises/tree-building/tree_building.go

This fix adds a duplicate check for the failing "duplicate node" test case.
Without this fix, running the tests fails with:
```
go test
--- FAIL: TestMakeTreeFailure (0.00s)
tree_test.go:242: Build for test case "duplicate node" returned 0:[1:[] 1:[]] but was expected to fail.
FAIL
exit status 1
FAIL    _/.../exercism/go/tree-building    0.011s
```

tree-building: add fix for duplicate node test

---

exercises/twelve-days/README.md

These updates where generated via configlet with the latest Exercism problem-specifications repo.
resolves #1165

twelve-days: fix punctuation issue in README

---

exercises/clock/clock_test.go

The Clock API now expects there to be a Subtract method on the custom Clock type. But the comment within clock_test.go mentions a Add method for both adding and subtracting time.

clock: add Subtract method to Clock API comment

---

exercises/phone-number/.meta/gen.go
exercises/phone-number/cases_test.go

[latest version of problem specifications](https://github.com/exercism/problem-specifications/commit/7290b84b809ccdacfa7ab674b1cb1237ca55105f#diff-2702bfb9de14559d38fdf33aab5089bf) implements 'error objects' as expected values; generator should be updated to unmarshal the new JSON with changed semantics (e.g. field "expected" can be a string or a map[string]string in case of error)

phone-number: update generator for error object

---

exercises/forth/.meta/gen.go
exercises/forth/cases_test.go

The canonical-data.json now uses a json error object
for the error expected cases instead of null.
Add IntSlice() function for OneCase to
handle the error object and return nil for an error
or return the slice of integers for the expected result.

forth: update generator for error object

---

exercises/diffie-hellman/diffie_hellman_test.go

This fixes the Travis build against Go master, which appears to be failing due to a change in either `fmt` or `math/big`.
Closes #1199

diffie-hellman: change big.Int formatting

---

exercises/isbn-verifier/isbn_verifier_test.go

There was a minor bug in the isbn-verifier tests: The test result showed pass messages for all tests, even if the tests failed. An example output would have been: 
```
--- FAIL: TestIsValidISBN (0.00s)
isbn_verifier_test.go:11: FAIL: valid isbn number
IsValidISBN("3-598-21508-8")
Expected: true, Actual: false
isbn_verifier_test.go:14: PASS: valid isbn number
```
The Pull Request fixes this problem.

Fix test to show pass messages only when passed

---

exercises/luhn/cases_test.go

I had a student submit a solution like this:
```go
if i == 1 || i%2 == 0 {
y *= 2
```
The logic for picking 'every second digit from the right' is not correct, but it works with the existing tests, because all the valid numbers have an odd number of digits. This commit adds a test case which would fail this incorrect solution, but pass for correct solutions.

luhn: Add test case for valid number with even length

---

exercises/error-handling/common.go

In case the student runs `golint` on his solution there is an error in the exercise package. Automatic tools will detect that too and blame the student.

error-handling: fix for golint

---

exercises/bank-account/bank_account_test.go

When an Account is closed we would expect the balance to be zero; this PR adds a test that fails when a closed Account has a non-zero balance. (Carried from #1171.)

bank-account: verify that closed account has zero balance

---

exercises/robot-name/bonus_example.go
exercises/robot-name/bonus_test.go
exercises/robot-name/example.go
exercises/robot-name/robot_name_test.go

I've noticed that a lot of students are unfamiliar with Go's error return conventions, and struggle a bit when required to handle an error condition. I've also noticed that practically no solutions to 'Robot Name' ever handle the case where the available robot names are exhausted (usually they just loop forever).
Changing the function signature of `Name()` to return `(string, error)` seems to me both a nice introduction to error returns, and a valuable hint that there _is_ an error condition to think about. Fixes #1191.

robot-name: have Name() return (string, error)

---

exercises/protein-translation/example.go
exercises/protein-translation/protein_translation_test.go

example.go:9:2: error var STOP should have name of the form ErrFoo
example.go:9:2: exported var STOP should have comment or be unexported
Fixes #1202.

protein-translation: fix lint errors

---

exercises/hamming/.meta/gen.go
exercises/hamming/cases_test.go
exercises/hamming/hamming_test.go

This is most students' first encounter with Go's error return conventions. Many of them are not sure what _data_ value to return in the error case, so they look at the test cases, see that the expected value is `-1`, and return that.
The test case generator was using -1 as an out-of-band value to indicate that an error was expected. To avoid misleading students, this PR changes the generator to set an `expectError` bool on the test case instead. In the error case, the 'expected' data value is now 0, although of course this is not checked (nor should it be).
This makes it really clear from the test cases what the student is expected to do in the error case: return 0 and a non-nil error.
This PR also regenerates the test cases from upstream, using the updated generator.

hamming: use 'expectError` in test cases, not -1

---

exercises/matrix/matrix_test.go

A few students have been mighty confused by test failures like this:
```
--- FAIL: TestCols (0.00s)
matrix_test.go:204: New("1 2\n10 20").Cols() = [[1 10] [2 20]], want [[1 10] [2 20]]
```
The data values are identical. But the first rule of `reflect.DeepEqual` (apart from "Do not talk about `reflect.DeepEqual`") is that its arguments must be the same type.
An example of a `Cols()` implementation which fails this test is:
```go
func (m Matrix) Cols() Matrix {
var ret Matrix
for i := 0; i < len(m); i++ {
row := make([]int, len(m))
for j, r := range m {
row[j] = r[i]
}
ret = append(ret, row)
}
return ret
}
```
This PR changes the failure message to include the actual types, making it clear that the method should return `[][]int` instead:
```
--- FAIL: TestCols (0.00s)
matrix_test.go:204: …
```

matrix: show types in reflect.DeepEqual failure output

---

config.json

Fixes #1131:
> grep is unlocked by Hamming. While a learner may be able to stumble through an ugly solution after Hamming, they'll be much more ready to write a clean solution after having mastered some of the later concepts.
> How about 'Tournament'? If you've done that, you probably know how to use a bufio.Scanner, use input records to build a data structure, and write out formatted results.

grep: move later, after 'tournament'

---

bin/test-without-stubs

Fixes the output of the Travis script.
Before:
`moving stub exercises/leap//leap.go`
After:
`moving stub exercises/leap/leap.go`
Also ensures that there will be no unexpected behavior when the `file` variable is used.

bin/test-without-stubs: Removed the redundant slash from the 'file' stub file path variable

---

exercises/two-fer/two_fer_test.go

This PR tries to add clarity to the test failure message, when the empty string is returned from the `ShareWith` function, by adding double quotes around the expected and the observed values.
Failure message before changes:
`two_fer_test.go:18: ShareWith() = , want One for you, one for me.`
Failure message before changes:
`two_fer_test.go:18: ShareWith() = "", want "One for you, one for me."`
This way the students will clearly see that their function returns empty string and where the expected string starts.
It is a questionable change, but I thought that the students (especially the new one) should not spend a lot of time trying to decipher the test output.

two-fer: Added double quotes arround the observed and the expected values in the test failure message

---

exercises/space-age/.meta/hints.md

The current test cases use a `Planet` type for specifying a planet in the exercise. However, this `Planet` isn't defined anywhere, and the test cases actually pass a string to the function. When running the tests I get the following error:
```
./cases_test.go:9: undefined: Planet
```
I think this is a mistake? The type should be a string.

Space Age: Add hint for implementing custom Planet type

---

exercises/space-age/README.md

There was a hint added to the .meta file in #1236, but the commands to add it to the readme were not run. This PR fixes it.
Fixes #1239.

add meta hint to readme

---

exercises/hamming/hamming_test.go

Executing `golangci-lint` gave me
```
hamming_test.go:36:12: Error return value of `Distance` is not checked (errcheck)
Distance(tc.s1, tc.s2)
^
```
before this change.

[hamming] Ignore error in test

---

.gitignore
.travis.yml
bin/fetch-golangci-lint
bin/test-without-stubs
exercises/error-handling/error_handling_test.go
exercises/palindrome-products/palindrome_products_test.go
exercises/poker/example.go
exercises/proverb/proverb_test.go
exercises/robot-name/bonus_test.go
exercises/robot-name/robot_name_test.go
exercises/run-length-encoding/example.go
exercises/two-bucket/example.go
exercises/two-bucket/two_bucket_test.go
exercises/yacht/example.go
gen/gen.go

I could have omitted the .travis.yml change until after consensus on the Go code lint "fixes", but I wanted to see if it could operate successfully.
The golangci-lint options used by @sebito91 in #1168 were used for starters.

Updates for golangci-lint

---

exercises/acronym/cases_test.go
exercises/armstrong-numbers/cases_test.go
exercises/binary-search/cases_test.go
exercises/change/cases_test.go
exercises/clock/cases_test.go
exercises/forth/cases_test.go
exercises/grains/cases_test.go
exercises/hamming/cases_test.go
exercises/isogram/cases_test.go
exercises/leap/cases_test.go
exercises/luhn/cases_test.go
exercises/pangram/cases_test.go
exercises/phone-number/cases_test.go
exercises/scale-generator/cases_test.go
exercises/word-count/cases_test.go
exercises/wordy/cases_test.go
exercises/yacht/cases_test.go

1. Why is this change neccesary?
Because some exercises like isogram allowed you to use a `break` a statement
inside a for loop and having all the tests pass, this can lead to some confusion
between `break` and `continue` statements that are inside a for loop.
With the current test suite one could do something like this:
```
for i, letter := range word {
letter = unicode.ToLower(letter)
if !unicode.IsLetter(letter) {
break
}
if strings.ContainsRune(word[i+1:], letter) {
return false
}
}
```
And have all the test pass.
This could be problematic as the `break` statement gives a better benchmark but
it's because of a coincidence with the test cases.
Other exercises had similar problems.
2. How does it address the issue?
The test cases for all of the exercises were updated.
3. What side …

fix: Update test cases for outdated exercises.

---

exercises/variable-length-quantity/.meta/gen.go
exercises/variable-length-quantity/cases_test.go
exercises/variable-length-quantity/variable_length_quantity_test.go

upstream problem specifications have been [updated](https://github.com/exercism/problem-specifications/commit/9cdc06462f99064ff7bd4174f9586b93e7b7318f#diff-3030cdac0a2738a37774e6e7ae38ae11) with the addition of an expected 'error' object

variable-length-quantity: update generator

---

exercises/linked-list/cases_test.go
exercises/linked-list/example.go

1. On an error, use `nil` for the return value over `int(0)`
2. In the unit tests, do not check the return value when there is an error.

LinkedList: On error, return nil, not int(0). Don't test val on error.

---

exercises/hamming/hamming_test.go

Consider this (real) solution:
```go
func Distance(a, b string) (int, error) {
// return error if strings are of different length
if len(a) != len(b) {
return 0, fmt.Errorf("unequal lengths: %q, %q", a, b)
}
if a == "" || b == "" {
return 0, nil
}
diff := 0
ar, br := []rune(a), []rune(b)
for i, r := range ar {
if r != br[i] {
diff++
}
}
return diff, nil
}
```
It contains a subtle bug: when checking if the inputs are of equal length, it checks the _string_ length, not the _rune sequence_ length. If one of the strings contains a wide character (for example `Ã`) and the other one doesn't, their lengths will be unequal and the function will bail out with an error, returning 0 for the data value.
So far, so good. But the test code doesn't handle this correctly. When the test case doesn't …

hamming: check returned error before value

---

exercises/space-age/cases_test.go
exercises/space-age/example.go

latest upstream json ( https://github.com/exercism/problem-specifications/commit/28b3dac0d8055e22280a885e156c1fd2dba20c26 ) has changed some values, with the result that a test was failing due to rounding errors
```
$ go test
--- FAIL: TestAge (0.00s)
space_age_test.go:15: PASS: age on Earth
space_age_test.go:15: PASS: age on Mercury
space_age_test.go:15: PASS: age on Venus
space_age_test.go:15: PASS: age on Mars
space_age_test.go:15: PASS: age on Jupiter
space_age_test.go:15: PASS: age on Saturn
space_age_test.go:13: FAIL: age on Uranus
Expected: 0.46
Actual: 0.45
FAIL
exit status 1
FAIL	_/home/andrea/projects/exercism-go/exercises/space-age	0.001s
```

space-age: fix Uranus period

---

exercises/twelve-days/twelve_days_test.go

Hello all,
While working on the "Twelve days" exercise I have created a small benchmark in local with the goal of testing two different approaches:
1) Creating verse by appending strings via "+" operator
2) Creating verse by creating a strings.Builder and appending via the WriteString method.
My idea is that these benchmarks could help those who would like to see the difference in performance for these and potentially other approaches. Would it make sense to you to add them in the test suite?

twelve days: add benchmark

---

exercises/clock/clock_test.go

Consider a student who is not quite ready to do `Subtract`, so the
student has `Subtract` return the same clock unaltered, then runs the
tests to see what happens. The student will see the following:
--- FAIL: TestSubtractMinutesStringless (0.00s)
clock_test.go:92: New(10, 3).Add(3) = 10:03, want 10:00
But it is not true that the test should want 10:00 after adding 3
minutes to 10:03. Instead, the test should want 10:00 after subtracting
3 minutes from 10:03.
This is also apparent from the name of the test,
TestSubtractMinutesStringless.

clock: Correct test message (Subtract, not Add)

---

.travis.yml

- replace go 1.11 with 1.13
- drop sudo since travis sticks to vm and deprecated
- drop tip support, we don't need to live at the edge

Regular travis updates 1.13

---

exercises/space-age/space_age.go

There was a missing declaration of type *Planet* in the stub file of the exercise **space-age**. Thus when running tests on downloaded exercise, the code failed to compile. This change fixes that issue.
See #1293 for more info.

space-age: add missing type in downloaded file

---

exercises/robot-name/common_test.go
exercises/robot-name/robot_name_test.go

Bonus test fails on proposed test command - `go test -tags bonus`
It's happens because we are taking all available robot names in bonus test, so base test fails
I have changed test structure - moved common parts to separate file and added exclusion build tag to base tests, so running the command `go test -tags bonus` executes only bonus test.

robot-name: change test structure for bonus fix

---

exercises/bob/cases_test.go

This PR updates the `bob` cases to reflect more inclusive language that before. For details please see: https://github.com/exercism/problem-specifications/issues/1630

bob: update cases to reflect more inclusive language

---

exercises/prime-factors/prime_factors_test.go

Fix #1295 
Simple sort implementation applied to the list of primes before testing for equality.

prime-factors: accept order-independent results

---

config.json

Closes https://github.com/exercism/research_experiment_1/issues/102.
In the issue above, it has been suggested that Go should use tabs for spacing, with a width of 4 spaces. When this is merged, the online editor for Go in the research website should respect this setting.

Set online editor config

---

README.md

because they render better on high resolution displays

Prefer SVG badges to PNGs

---

exercises/matrix/example.go
exercises/matrix/matrix_test.go

So that students can readily run benchmarks when they are trying to
improve the performance of their solution.

Add 3 benchmarks for the matrix exercise

---

exercises/sublist/cases_test.go

I've added a test case that failed my solution.
There is a case when an unfinished sublist happens at the end.

sublist: Add test case

---

exercises/variable-length-quantity/.meta/gen.go
exercises/variable-length-quantity/variable_length_quantity_test.go

Remove old and misleading comment in gen.go
As no test result expects nil it should be safe to skip checking that and
handle when error is nil despite errorExpected is true.
Closes #1328

variable_length_quantity: fix missing error handling in tests

---

exercises/concept/booleans/.meta/config.json
exercises/concept/chessboard/.meta/config.json
exercises/concept/comments/.meta/config.json
exercises/concept/conditionals/.meta/config.json
exercises/concept/constants/.meta/config.json
exercises/concept/errors/.meta/config.json
exercises/concept/lasagna/.meta/config.json
exercises/concept/maps/.meta/config.json
exercises/concept/methods/.meta/config.json
exercises/concept/numbers/.meta/config.json
exercises/concept/slices/.meta/config.json
exercises/concept/strings-package/.meta/config.json
exercises/concept/strings/.meta/config.json
exercises/concept/structs/.meta/config.json
exercises/concept/the-farm/.meta/config.json
exercises/concept/time/.meta/config.json
exercises/concept/zero-value/.meta/config.json

The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26

🤖 Flatten authors and contributors in .meta/config.json files

---

exercises/concept/booleans/.docs/instructions.md

The `## Tasks` heading should not be in `instructions.md` files.

Remove Tasks heading from instructions.md

---

exercises/practice/luhn/cases_test.go

A new positive test case with odd number of digits and non-zero first digit.
I have seen a solution which passes all the tests for Luhn containing odd number of digits and never reads the first digit.
It happens because in all such cases the first digit is zero .

Luhn: A new test case with odd number of digits

---

exercises/practice/robot-name/bonus_test.go
exercises/practice/robot-name/common_test.go

The problem description states that names should have 5 characters:
> The first time you boot them up, a random name is generated in the format of two uppercase letters followed by three digits, such as RX837 or BC811.
However, it is possible to have solutions passing both the normal tests and the bonus ones that do not respect this rule, like this solution [robot_name.zip](https://github.com/exercism/go/files/6444309/robot_name.zip)
This PR adds those checks both to the regular tests and the bonus ones. From the solutions I've tested, these checks seem to have no major impact on how long the tests take to run.
Another thing that we probably should also verify is that the name actually starts with 2 letters and 3 digits. Probably we can include this check only in the regular tests, just …

robot_name: Add checks for name length in tests

---

exercises/practice/hello-world/hello_world.go

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

exercises/concept/cars-assemble/cars_assemble_test.go

Test seems to expect the 'system under test' to be in a numbers package, but it's in a `cars` package, same as the test -- when working on this locally, the simplest thing seemed to be to remove the import and drop the qualified method names, which was in keeping with the way `savings-account` was written. There are other paths, but this is simple.

Fixing Test / Main Packaging

---

exercises/concept/elons-toys/go.mod

This dependency is not being used and so it's best to remove it.
This extra dependency is causing the test runner to fail:
```console
$ go test -json .
go: github.com/google/go-cmp@v0.5.3: missing go.sum entry; to add it:
go mod download github.com/google/go-cmp
go: github.com/google/go-cmp@v0.5.3: missing go.sum entry; to add it:
go mod download github.com/google/go-cmp
```
Removing the dependency from `go.mod` solves the issue and makes the tests run as expected.

elons-toys: remove unnecessary dependency from go.mod

---

exercises/practice/wordy/cases_test.go

Some solutions use 0 as the default value. The added test case can reject this scenario.

wordy add check of using default 0 minus number

---

exercises/concept/annalyns-infiltration/.meta/exemplar.go
exercises/concept/annalyns-infiltration/annalyns_infiltration.go

The comment of the function `CanFreePrisoner` talks about "the prisoner [...] and the other 3 characters". But there are only two other characters.
I also took the opportunity to add missing articles to make the comments more consistent ("the prisoner", "the archer", and "the knight").

Fix analyns infiltration description

---

concepts/strings/introduction.md

Fixed a fit.printf typo inside the example at the end of strings introduction. Provided example didn't work, now it does according to expected commented output

fix fmt.printf example at strings indtroduction

---

exercises/concept/cars-assemble/cars_assemble_test.go

Split from https://github.com/exercism/go/pull/1510
On my machine tests failed because of a very small float difference, this is doing a more robust float comparison

cars-assemble: Compare floats with threshold in test

---

docs/ABOUT.md
docs/LEARNING.md
exercises/shared/.docs/cli.md
exercises/shared/.docs/debug.md

Fixes #1483 
I found most of the documentation to be up-to-date. The only thing worth changing was some links, https://pkg.go.dev is the new home for package documentation in go, replacing the old https://golang.org/pkg. Although old links redirect properly, it's probably best to have the right links directly listed.
I did the same for a reference to exercism.io and converted it to the right link on exercism.org.

Update doc links

---

concepts/anonymous-functions/.meta/config.json
concepts/application-timing/.meta/config.json
concepts/bytes/.meta/config.json
concepts/channels/.meta/config.json
concepts/conditionals/.meta/config.json
concepts/context/.meta/config.json
concepts/defer/.meta/config.json
concepts/duration/.meta/config.json
concepts/empty-interface/.meta/config.json
concepts/floating-point/.meta/config.json
concepts/functions/.meta/config.json
concepts/goroutines/.meta/config.json
concepts/interfaces/.meta/config.json
concepts/iteration/.meta/config.json
concepts/mutex/.meta/config.json
concepts/nil/.meta/config.json
concepts/packages/.meta/config.json
concepts/panic/.meta/config.json
concepts/pointers/.meta/config.json
concepts/recover/.meta/config.json
concepts/reflection/.meta/config.json
concepts/runes/.meta/config.json
concepts/slices/.meta/config.json
concepts/type-assertion/.meta/config.json
concepts/type-conversion/.meta/config.json
concepts/variables/.meta/config.json
concepts/zero-values/.meta/config.json
config.json

Addresses the configlet lint issues from #1485
Namely: one missing slug and a bunch of empty author entries.

Fix configlet lint issues

---

exercises/concept/party-robot/.docs/introduction.md

Adds more examples. Explain `Sprintf` since it's required to pass the concept (unlike `Printf` and friends).
Also fixes a typo in an example while printing a floating point value.

Update introduction to Strings in Go

---

exercises/concept/annalyns-infiltration/.docs/introduction.md

annalyn-infiltration: add uses of 'true' and 'false' to examples

---

exercises/concept/annalyns-infiltration/annalyns_infiltration_test.go

The output of 'CanFreePrisoner' tests has the wrong function name mentioned. Correcting it so that the test outputs are not confusing.

Fix the typo in the test output function name

---

exercises/concept/card-tricks/.docs/instructions.md
exercises/concept/card-tricks/.meta/design.md
exercises/concept/card-tricks/.meta/exemplar.go
exercises/concept/card-tricks/card_tricks.go
exercises/concept/card-tricks/card_tricks_test.go

Fixes #1600 
None of the concepts teach about `uint8` and there is no real reason to confuse the students so we will just use `int` type everywhere in this exercise.

Have card-tricks only use int type

---

exercises/practice/matrix/.meta/example.go
exercises/practice/matrix/matrix_test.go

In the matrix exercise, the function New is expected to return a tuple with the types `*Matrix, error`.
However, in the `BenchmarkNew` test, the matrix variable defined a variable of type `Matrix`. It causes compilation errors due to type mismatch. 
This PR proposes a test code fix. It is also related to other open PR #1431.
Thanks.

Fix matrix test variable type

---

concepts/string-formatting/about.md
concepts/string-formatting/introduction.md
exercises/concept/party-robot/.docs/introduction.md

This exercise is becoming just about string formatting.
The text removed from here will be re-added in the strings concept being introduced in issue #1613
Closes #1625

Remove text generally about strings (and not fmt) from party-robot.

---

concepts/methods/about.md
concepts/methods/introduction.md
exercises/concept/elons-toys/.docs/introduction.md

This does the following changes:
* Remove main() function where not needed
* Describe how to use pointer recievers in methods as well as just giving examples
* Remove non-struct types which have not yet been explained
* Fix a small typo I spotted in the exercise.
Fixes #1626

Cleanup methods concept in the same way that we did for the exercise.

---

concepts/type-definitions/.meta/config.json
concepts/type-definitions/about.md
concepts/type-definitions/introduction.md
concepts/type-definitions/links.json
config.json
exercises/concept/chessboard/.docs/instructions.md
exercises/concept/chessboard/.docs/introduction.md
exercises/concept/chessboard/.meta/exemplar.go
exercises/concept/chessboard/chessboard.go
exercises/concept/chessboard/chessboard_test.go

Updates to `chessboard` exercise as per the tracking ticket for that exercise (#1623)
Also adds `type-definitions` concept as suggested by @junedev in #1602 and changes dependencies of exercises to accomadate.
Fixes #1604. Fixes #1601. Fixes #1602. Fixes #1603 by making it obsolete. Fixes #1623.

Chessboard updates

---

exercises/concept/cars-assemble/cars_assemble.go
exercises/concept/cars-assemble/cars_assemble_test.go

Add function name to the panic message and fix the function name typo in the test failure error message.

Cars assemble enhance test output

---

exercises/concept/cars-assemble/.docs/introduction.md

Fixes #1575
NOTE: the links are already duplicated over in the about.md file for the `numbers` concept.

Remove links from cars-assemble intro

---

exercises/concept/census/.docs/instructions.md

I was looking through the Census exercise on the site and noticed this unneeded brace and space in the example code snippet. I much have forgotten to remove it in #1500.

census: remove unneeded brace and space

---

exercises/concept/annalyns-infiltration/.docs/hints.md

* The headings for the tasks in hints.md were different to the headings
in instructions.md.
Fixes #1678

Fix headings in hints for annalyns-infiltration (#1678)

---

exercises/concept/logs-logs-logs/.docs/instructions.md

1. These methods aren't under the package `strings` so remove the prefix `strings.`
2. Fix section 2 instructions which should say `MessageLen`

Fix instructions for logs-logs-logs

---

config.json
exercises/concept/booking-up-for-beauty/.meta/design.md
exercises/concept/cars-assemble/.meta/design.md
exercises/concept/deep-thought/.meta/design.md
exercises/concept/savings-account/.meta/design.md

Now that we have some more concepts, we can set the correct perquisites for the exercise that teaches (advanced) "constants". This will move it further down in the tree. Also by removing "constants" as prerequisite for "cars assemple" (since we now cover it in basics), the concepts in cars-assemble will take the correct place in the concept tree.
I also fixed the prereqs for the `time` exercise and the currently wip errors exercise.

Some fixes for the concept tree

---

exercises/concept/welcome-to-tech-palace/.docs/hints.md

Noticed this when going trough the hints on the exercise.

welcome-to-tech-palace: Fix `strings.ReplaceAll()` link in hints

---

concepts/numbers/introduction.md

Remove links as the style guide discourages them (links should only be in the about).
Remove information that isn't needed for understanding the exercise.

Cleanup the introduction for the numbers concept.

---

.golangci.yml

Default is 1m which leads to some flaky tests

Increase timeout for golangci to 5m

---

exercises/concept/census/census_test.go

When solving Census task I've got a bit confused trying to understand test failure reason:
```
PS C:\Users\iavto\Documents\exercism_tasks\go\census> go test
--- FAIL: TestDelete (0.00s)
--- FAIL: TestDelete/no_data_collected (0.00s)
census_test.go:138: resident.Delete() = &{ 0 map[]}, want &{ 0 map[]}
--- FAIL: TestDelete/all_data_collected (0.00s)
census_test.go:138: resident.Delete() = &{ 0 map[]}, want &{ 0 map[]}
--- FAIL: TestDelete/some_data_collected (0.00s)
census_test.go:138: resident.Delete() = &{ 0 map[]}, want &{ 0 map[]}
```
The actual object seems to be the same as expected but the test failed for some reason. I browsed tests' code and found TestDelete expects the Delete method to set `Address` field to `nil` but I had it set to a new map. I changed the test output to …

census: made TestDelete to indicate wrong map value

---

concepts/conditionals-switch/about.md
concepts/conditionals-switch/introduction.md

Per the style guide we shouldn't link to external docs in the introduction, this cleans it up.
Whilst I was here I added line breaks in the paragraphs to be one sentence per line to minimise future diffs and make comparisons easier

Remove links from switch concept introduction.

---

concepts/methods/introduction.md

The style guide says that these should only be in the about docs.

Remove the links from the methods concepts introduction

---

concepts/slices/about.md
concepts/slices/introduction.md

There's a lot of good info in the about page for the concept, but it didn't cover any of the information from the introduction.
This fixes that by copying the introduciton into the about, making it a superset rather than a completely different doc

Fix slices concept about to be superset of introduction.

---

concepts/type-assertion/.meta/config.json
concepts/type-assertion/about.md
concepts/type-assertion/introduction.md
concepts/type-assertion/links.json

Fixes #1703
Partially addresses #1704

Fill in documentation for `type-assertions`

---

config.json
exercises/concept/sorting-room/.docs/hints.md
exercises/concept/sorting-room/.docs/instructions.md
exercises/concept/sorting-room/.docs/introduction.md
exercises/concept/sorting-room/.meta/config.json
exercises/concept/sorting-room/.meta/design.md
exercises/concept/sorting-room/.meta/exemplar.go
exercises/concept/sorting-room/go.mod
exercises/concept/sorting-room/sorting_room.go
exercises/concept/sorting-room/sorting_room_test.go

Part of #1645
This is not complete yet since the introduction should be filled out from details in the concepts so leaving it as "wip", but I wanted to start getting feedback.

`sorting-room`: Implement exercise to teach about `type-conversion` and `type-assertion`

---

config.json

The current implementation does not really make for an interesting exercise. There is a lack of story and the only thing the student is asked to do is to return constant values.
See https://github.com/exercism/go/blob/main/exercises/concept/savings-account/.meta/exemplar.go and https://github.com/exercism/go/blob/main/exercises/concept/savings-account/.docs/instructions.md
We can try to improve this exercise later or deprecate it in favor of another exercise.

savings-account: change status to `wip`

---

exercises/shared/.docs/debug.md

Closes https://github.com/exercism/go/issues/1694
Is this enough? It would have been enough to help me out. I hit this problem too as a total Golang noob. I didn't know how to write imports so first I wrote `import fmt` and hit a weird error about "expected string, got newline" 😁 
I think for people that wrote software before it will be obvious that the imports go at the top of the file usually, but the `fmt.Println` calls can go anywhere, right? I don't think it's necessary to spell out explicitly.

Mention `import "fmt"` in debug.md

---

concepts/runes/.meta/config.json
concepts/runes/about.md
concepts/runes/introduction.md
concepts/runes/links.json
exercises/concept/logs-logs-logs/.docs/hints.md
exercises/concept/logs-logs-logs/.docs/instructions.md
exercises/concept/logs-logs-logs/.docs/introduction.md
exercises/concept/logs-logs-logs/.meta/config.json
exercises/concept/logs-logs-logs/.meta/design.md
exercises/concept/logs-logs-logs/.meta/exemplar.go
exercises/concept/logs-logs-logs/logs.go
exercises/concept/logs-logs-logs/logs_test.go

Updating the `logs-logs-logs` exercise as a part of the September Sprint.
Closes #1594
Closes #1595
Closes #1596
Closes #1614

logs-logs-logs: update concept and exercise content

---

exercises/concept/weather-forecast/.docs/hints.md

A header mismatch between hints and the instructions: https://github.com/exercism/go/blob/main/exercises/concept/weather-forecast/.docs/instructions.md#1-document-package-weather

Fix `weather-forecast` task 1 hints not showing up

---

concepts/functions/.meta/config.json
concepts/functions/about.md
concepts/functions/introduction.md
concepts/functions/links.json
config.json
exercises/concept/lasagna-master/.docs/hints.md
exercises/concept/lasagna-master/.docs/instructions.md
exercises/concept/lasagna-master/.docs/introduction.md
exercises/concept/lasagna-master/.meta/config.json
exercises/concept/lasagna-master/.meta/design.md
exercises/concept/lasagna-master/.meta/exemplar.go
exercises/concept/lasagna-master/go.mod
exercises/concept/lasagna-master/lasagna-master.go
exercises/concept/lasagna-master/lasagna-master_test.go

This is my first attempt at something as ambitious as a full exercise and a concept, so any/all feedback and tips very gratefully received.
Specific things that I'm unsure about / have questions on:
* Fitting this concept/exercise into the existing hierarchy - I've done this somewhat, but if I add dependencies for everything that's relevant then I create cycles. Feedback welcomes from someone who has a more holistic view of the progression of concepts they think is right for the Go track.
* The concept introduction and exercise introduction are nearly identical. Is this OK/appropriate? (Should I just be using .docs/introduction.md.tpl if so?)
* .meta/design.md - this is my first attempt at one of these, I've read a few others but it's largely cargo cult.
* Should my exercise include …

Functions concept

---

exercises/concept/weather-forecast/.docs/introduction.md

Units of measurement on Exercism must be SI or SI-derived units according to the style guide: https://exercism.org/docs/building/markdown/style-guide

Weather forecast: Remove non-SI unit from examples

---

concepts/basics/about.md
concepts/basics/introduction.md
concepts/comments/about.md
concepts/comments/introduction.md
concepts/numbers/about.md
concepts/numbers/introduction.md
concepts/pointers/about.md
concepts/pointers/introduction.md
concepts/range-iteration/introduction.md
concepts/time/about.md

Fixes #1581
Note that there's still a reference right now in the functions concept, I'll address that in PR#1720 to avoid merge conflicts

Remove references to exercises from concept docs.

---

config.json
exercises/concept/census/.meta/design.md
exercises/concept/gross-store/.meta/design.md
exercises/concept/logs-logs-logs/.meta/design.md

Fixes #1749
@junedev Is this what you had in mind?
When editing I noticed some of the prerequisites in `design.md` didn't match the prerequisites in the `config.json`. I made them match by copying the pre-requisites in `config.json` and putting them in `design.md`. Let me know if I was supposed to do this. Didn't find anything against it in [the documentation](https://exercism.org/docs/building/tracks/concept-exercises). The only exercise for which I didn't do this was "logs-logs-logs", since the `design.md` file was changed just 1 day ago and I'm not sure which list of prerequisites is correct, if the one on `config.json` or the one in `design.md`.

Add pointers, range-iteration and functions prerequisites to exercises

---

exercises/practice/error-handling/.meta/config.json
exercises/practice/minesweeper/.meta/config.json
exercises/practice/paasio/.meta/config.json
exercises/practice/react/.meta/config.json
exercises/practice/robot-simulator/.meta/config.json
exercises/practice/simple-cipher/.meta/config.json

While I was looking at `simple-cipher` using the editor, I was a bit frustrated I couldn't see an extra file that I was supposed to see, so I added it to the editor. I also went ahead and checked other exercises on the track that are in a similar situation and would benefit from having other files showing up in the editor.

Add exercises' extra files to editor

---

exercises/practice/allergies/allergies_test.go

There are some solutions for this exercise that produce the right list of allergies Tom is allergic to, but do not produce them in the same order as the tests expect:
```
allergies_test.go:11: FAIL: Allergies(255): expected []string{"eggs", "peanuts", "shellfish", "strawberries", "tomatoes", "chocolate", "pollen", "cats"}, actual []string{"shellfish", "strawberries", "tomatoes", "chocolate", "pollen", "cats", "eggs", "peanuts"}
--- FAIL: TestAllergies (0.00s)
```
The `actual` list and the `expected` list contain the same elements, just ordered differently.
This PR makes the tests see if the lists have the same elements, regardless of their order. I think it's reasonable to allow for the elements to be ordered differently than the expected. The instructions mention returning a list of "all …

allergies: make tests not care about the order of elements

---

exercises/concept/booking-up-for-beauty/.docs/hints.md
exercises/concept/booking-up-for-beauty/.docs/instructions.md

Make `AnniversaryDate` instructions a bit more explicit / intuitive. As it currently stands, which specific anniversary is undefined and ambiguous.

Improve instructions for AnniversaryDate

---

concepts/pointers/about.md
concepts/pointers/introduction.md
exercises/concept/election-day/.docs/introduction.md

fix: removed doubled up wording in exercises

fix: removed doubled up wording in exercises

---

exercises/practice/matching-brackets/matching_brackets.go
exercises/practice/matrix/matrix.go
exercises/practice/matrix/matrix_test.go
exercises/practice/meetup/meetup.go
exercises/practice/meetup/meetup_test.go
exercises/practice/minesweeper/minesweeper.go
exercises/practice/ocr-numbers/.docs/instructions.append.md
exercises/practice/ocr-numbers/ocr_numbers.go
exercises/practice/ocr-numbers/ocr_numbers_test.go
exercises/practice/paasio/paasio.go
exercises/practice/palindrome-products/palindrome_products.go
exercises/practice/palindrome-products/palindrome_products_test.go
exercises/practice/pangram/pangram.go
exercises/practice/pascals-triangle/pascals_triangle.go
exercises/practice/perfect-numbers/perfect_numbers.go
exercises/practice/phone-number/phone_number.go
exercises/practice/pig-latin/pig_latin.go
exercises/practice/poker/poker.go
exercises/practice/poker/poker_test.go
exercises/practice/pov/.docs/instructions.append.md
exercises/practice/pov/pov.go
exercises/practice/pov/pov_test.go
exercises/practice/prime-factors/prime_factors.go
exercises/practice/protein-translation/protein_translation.go
exercises/practice/pythagorean-triplet/pythagorean_triplet.go
exercises/practice/pythagorean-triplet/pythagorean_triplet_test.go

Related to #1893 
We would like to add stub functions to the practice exercises so that students know what API they are expected to implement. We would also like to remove any API descriptions from test files as these may go out of sync with the code over time
This PR adds stubs for practice exercises starting with letters M through to P and updates the associated test files accordingly
The following practice exercises have been omitted (mostly because they already have stubs):
- [markdown](https://github.com/exercism/go/blob/main/exercises/practice/markdown/markdown.go)
- [nth-prime](https://github.com/exercism/go/blob/main/exercises/practice/nth-prime/nth_prime.go)
- [nucleotide-count](https://github.com/exercism/go/blob/main/exercises/practice/nucleotide-count/nucleotide_count.go)
- …

Add stub functions to practice exercises M-P

---

exercises/practice/queen-attack/queen_attack.go
exercises/practice/rail-fence-cipher/rail_fence_cipher.go
exercises/practice/react/react.go
exercises/practice/rectangles/rectangles.go
exercises/practice/reverse-string/reverse_string.go
exercises/practice/robot-name/robot_name.go
exercises/practice/robot-simulator/.docs/instructions.append.md
exercises/practice/robot-simulator/robot_simulator.go
exercises/practice/robot-simulator/robot_simulator_step2_test.go
exercises/practice/robot-simulator/robot_simulator_step3_test.go
exercises/practice/robot-simulator/robot_simulator_test.go
exercises/practice/roman-numerals/roman_numerals.go
exercises/practice/rotational-cipher/rotational_cipher.go
exercises/practice/run-length-encoding/run_length_encoding.go
exercises/practice/saddle-points/saddle_points.go
exercises/practice/say/say.go
exercises/practice/scale-generator/scale_generator.go
exercises/practice/secret-handshake/secret_handshake.go
exercises/practice/series/series.go
exercises/practice/series/series_test.go
exercises/practice/sieve/sieve.go
exercises/practice/simple-cipher/simple_cipher.go
exercises/practice/simple-linked-list/simple_linked_list.go
exercises/practice/simple-linked-list/simple_linked_list_test.go
exercises/practice/spiral-matrix/spiral_matrix.go
exercises/practice/strain/strain.go
exercises/practice/strain/strain_test.go
exercises/practice/sublist/sublist.go
exercises/practice/sum-of-multiples/sum_of_multiples.go

Related to #1893 
We would like to add stub functions to the practice exercises so that students know what API they are expected to implement. We would also like to remove any API descriptions from test files as these may go out of sync with the code over time
This PR adds stubs for practice exercises starting with letters Q through to S and updates the associated test files accordingly
The following practice exercises have been omitted because they already have stubs defined:
- [raindrops](https://github.com/exercism/go/blob/main/exercises/practice/raindrops/raindrops.go)
- [rna-transcription](https://github.com/exercism/go/blob/main/exercises/practice/rna-transcription/rna_transcription.go)
- [scrabble-score](https://github.com/exercism/go/blob/main/exercises/practice/scrabble-score/scra …

Add stub functions to practice exercises Q-S

---

exercises/concept/gross-store/gross_store_test.go

See [#1940](https://github.com/exercism/go/issues/1940).
Testing using `bill[item] = units[unit]` fails with the following:
```
=== RUN   TestAddItem
=== RUN   TestAddItem/Invalid_measurement_unit
=== RUN   TestAddItem/Valid_measurement_unit
=== RUN   TestAddItem/check_quantity_of_item_added_twice
gross_store_test.go:95: Expected peas to have quantity 6 in customer bill, found 3
gross_store_test.go:95: Expected tomato to have quantity 9 in customer bill, found 3
--- FAIL: TestAddItem (0.00s)
--- PASS: TestAddItem/Invalid_measurement_unit (0.00s)
--- PASS: TestAddItem/Valid_measurement_unit (0.00s)
--- FAIL: TestAddItem/check_quantity_of_item_added_twice (0.00s)
FAIL
exit status 1
FAIL    gross   0.001s
```
Testing with correct code `bill[item] += units[unit]` passes with the following: …

gross store: added test case for item added twice

---

exercises/concept/interest-is-interesting/interest_is_interesting_test.go

Fixes #1842 
Changed the comparison between floats to work with bigger values, as suggested by @junedev 
Also found the following options that ended up being more strict:
```go
(math.Abs(x - y) <= epsilon * math.Max(math.Abs(x), math.Abs(y)))
```
And the following one that accepted two different thresholds:
```go
((math.Abs(x-y) <= epsilonTol) || (math.Abs(x-y) <= epsilonRel*math.Max(math.Abs(x), math.Abs(y))))
```
All of the options above also worked with the tests on the Interest-is-Interesting exercise and fixed the issue, but june's suggestion accepted a wider range of values.
The solutions above were found here: http://realtimecollisiondetection.net/blog/?p=89

Interest-is-Interesting: Fix float comparison

---

exercises/concept/party-robot/party_robot_test.go

This change does the following:
* extend an existing testcase to include non-standard ASCII character values for other string parameters as well. Note that this was already being checked for the `name` parameter, but was not checked for the `direction` and `seatmate` parameters.
* add a new testcase which checks additional value scenarios for `tableNumber` (an int parameter) and `distance` (a float64 parameter)

party-robot: update tests

---

exercises/concept/vehicle-purchase/.docs/hints.md
exercises/concept/vehicle-purchase/.docs/instructions.md
exercises/concept/vehicle-purchase/.meta/exemplar.go
exercises/concept/vehicle-purchase/vehicle_purchase.go
exercises/concept/vehicle-purchase/vehicle_purchase_test.go

Replace the occurence of the word Licence with License.
closes #1965

vehicle-purchase: correct spelling of `License`. - #1965

---

exercises/concept/vehicle-purchase/.docs/instructions.md
exercises/concept/vehicle-purchase/vehicle_purchase_test.go

The test for the method at 10 years old was expecting the resell price
to be 50% of the original, not the 70% that was implied by the
instructions.
This comes from a student who commented _If it is more than 10 years old, it costs 50%. Wouldn't the above statement translate into the following? if age > 10 { rate = 0.5 }_ with the following implementation:
```go
func CalculateResellPrice(originalPrice, age float64) float64 {
var rate float64
if age < 3 {
rate = 0.8
} else if age >= 10 {
rate = 0.5
} else {
rate = 0.7
}
return originalPrice * rate
}
```
Note, I had a look at the original Javascript version. It looks like their test for 10 year was correctly expecting 70%. I went with adjusting the instructions and test in this PR as there are now existing solutions - if we changed the test …

vehicle-purchase: fix CalculateResellPrice price description (#1934)

---

exercises/practice/tournament/tournament.go
exercises/practice/transpose/transpose.go
exercises/practice/twelve-days/twelve_days.go
exercises/practice/two-bucket/two_bucket.go
exercises/practice/variable-length-quantity/variable_length_quantity.go
exercises/practice/word-count/word_count.go
exercises/practice/word-count/word_count_test.go
exercises/practice/word-search/word_search.go
exercises/practice/word-search/word_search_test.go
exercises/practice/wordy/wordy.go
exercises/practice/yacht/yacht.go
exercises/practice/zebra-puzzle/.docs/instructions.append.md
exercises/practice/zebra-puzzle/zebra_puzzle.go

Closes #1893 
We would like to add stub functions to the practice exercises so that students know what API they are expected to implement. We would also like to remove any API descriptions from test files as these may go out of sync with the code over time
This PR adds stubs for practice exercises starting with letters T through to Z and updates the associated test files accordingly
The following practice exercises have been omitted because they already have stubs defined:
- [tree-building](https://github.com/exercism/go/blob/main/exercises/practice/tree-building/tree_building.go)
- [triangle](https://github.com/exercism/go/blob/main/exercises/practice/triangle/triangle.go)
- [trinary](https://github.com/exercism/go/blob/main/exercises/practice/trinary/trinary.go) - this exercise is also …

Add stub functions to practice exercises T-Z

---

exercises/concept/vehicle-purchase/vehicle_purchase_test.go

The tests for CalculateResellPrice vary from the other tests in that it just prints whether all the tests were Pass or Fail. Its missing the following:
1. List of individual tests that were executed for the CalculateResellPrice method
2. The status at individual test level (Pass or Fail)
3. The time taken to execute the individual tests (e.g. 0.01s)

Wrapped CalculateResellPrice under Test.Run

---

exercises/concept/card-tricks/.docs/instructions.md
exercises/concept/card-tricks/card_tricks.go

The instructions and comments for PrefilledSlice method do not mention the intended behavior when the length of the slice is non-positive. However, the test suite for Prefilled slice contains a case where the length is -3. Updating the instructions to include an example and updating the comments to match the instructions.

Instructions for missed case in PrefilledSlice 

---

concepts/type-conversion/about.md
concepts/type-conversion/introduction.md
exercises/concept/sorting-room/.docs/introduction.md

Closes #1985
The documentation specifies that `strconv.Atoi` has 1 return value,
while it has 2

Docs: fix the number of return values for `strconv.Atoi` in docs

---

config.json
exercises/concept/chessboard/.meta/design.md

Learning `range-iteration` in the Chessboard exercise should happen after learning about basic for loops. However, `for-loops` was missing as prerequisite for Chessboard. (This happened because `for-loops` was created later.)

add missing prerequisite for chessboard

---

exercises/concept/booking-up-for-beauty/.docs/instructions.md

Based on the test suite, the AnniversaryDate function needs to return the current year's anniversary date in UTC timezone. However, the current instructions have no mention of any such requirement. Updating the instruction to fix this.

Included TimeZone in AnniversaryDate Instructions

---

exercises/concept/census/census_test.go

Tests must fail if the street key has explicitly set to its zero-value
Closes #1995

Check explicit zero-value for street key

---

docs/ROADMAP.md
docs/config.json

Bethany pointed out that by adding the roadmap to the docs folder and setting the right config, we can make it available on the website in the track-specific contribution guideline section. https://exercism.org/docs/tracks/go
This PR also includes some minor updates.

Make roadmap available on the website

---

exercises/concept/gross-store/.docs/instructions.md

Based on the test suite, the expectation from the AddItem function is to add the input item to the bill and if its already present, to increase its quantity by unit amount. The current instructions mention only the former part of the requirement and leave out the latter. Included an additional line to fix this.

Extended Instructions for AddItem Function

---

exercises/concept/sorting-room/.docs/hints.md

In the hints.md, it describes that we can check if this is `FancyBox`.
That is inconsistent to the type in sorting_room.go source.
I think `FancyNumber` is supposed to be the correct word in the hint.

sorting-room: Align hints.md content to sorting_room.go source

---

concepts/packages/introduction.md
concepts/string-formatting/.meta/config.json
concepts/string-formatting/about.md
concepts/string-formatting/introduction.md
concepts/string-formatting/links.json
exercises/concept/party-robot/.docs/introduction.md

I noticed that there was a mismatch in the Party Robot introduction and the concept docs for the two concepts included there. During the September sprint, some issues were addressed but in one case they were only fixed in the introduction and in the other case only in the concept docs. With this PR, I plug in the respective corrected version into the other place as well. I didn't change the content.
Additionally this PR contains
* fixing the wrong blurb of `string-formatting` concept
* add a missing links to where to read about all the formatting verbs
* removing links that did not belong into the string formatting concept anymore (they were artifacts of changing the content of that concept)
* adding h2 headers for the exercise introduction file to make it easier to read

String Formatting and Packages: Syncronize concept docs, fix blurb etc

---

exercises/concept/the-farm/.docs/instructions.md

This PR contains the following minor changes:
- Renamed `weightFodder` to `FodderAmount` when referencing the method that provides the fodder amount
- Renamed instances of `function` with `method` when referencing the `FodderAmount` method
- Included the keyword `struct` when referring to the `weightFodder` instance
- Updated the names of `WeightFodder` instances to maintain consistency between comments and function arguments (e.g. replaced `twentyFodderNoError says there are -5.0 fodder` with `negativeFiveFodder says there are -5.0 fodder`)
This PR contains the following major change:
The sequence of instructions do not reflect the sequence of cases that need to be handled by the `DivideFood` function. For example, if the amount of fodder is negative then the error returned by …

Instructions fix for The Farm

---

concepts/errors/about.md
concepts/errors/introduction.md
exercises/concept/the-farm/.docs/introduction.md

Error name should be `ErrResourceNotFound` in `if` statement, it was incorrectly showing `ErrSomethingWrong` which is not related to this specific example.

Small typo in error comparison example

---

exercises/practice/list-ops/list_ops.go

I noticed that there is a typo in the stub function when I was doing list-ops exercise.
Fix it with this small PR.

list-ops: fix typo in stub function

---

exercises/concept/sorting-room/sorting_room_test.go

Sending value `12`, while description says `11`

sorting-room: fix test description typo

---

exercises/concept/the-farm/.docs/instructions.md
exercises/concept/the-farm/.meta/exemplar.go
exercises/concept/the-farm/the_farm_test.go

Task2 asks for:
```go
// negativeFiveFodder says there are -5.0 fodder
fodder, err := DivideFood(negativeFiveFodder, 10)
// fodder == 0.0
// err.Error() == "Negative fodder"
```
When I type `return 0, errors.New("Negative fodder")`, VSCode warns out: `error strings should not be capitalized (ST1005) go-staticcheck`
Same for Task3.

the-farm: fix go-staticcheck warning

---

exercises/concept/need-for-speed/need_for_speed_test.go

Hopefully, this will make it easier for learners to understand which values refer to which fields, especially if there are multiple fields of the same type.
Originally did this only for the `Drive` function, but it might be useful in all the other places as well. Lmk if that is fine with you.
Before:
```Car{5 95 2}```
After
```Car{"speed":5, "battery":95,  "batteryDrain":2}```

Add field names to structs when failing tests for Structs tutorial

---

exercises/concept/chessboard/.meta/exemplar.go
exercises/concept/chessboard/chessboard.go

The exemplar says that ranks are accessed by values from "A" to "H",
but maps are accessed by keys.

Correct typo in Chessboard exercise

---

concepts/maps/about.md

Follow-up of #2034
Inspired by #2034, I went ahead and checked other uses where the Go word was not being capitalized properly. This particular typo seemed to be confined to the maps exercise/concept.
The command used to find these instances:
```bash
find ~/git/exercism-go -name '*.md' -type f -exec grep -n --color=auto -H ' go[ ,.]' /dev/null {} \;
```

More fixes to the "Go" word

---

exercises/concept/cars-assemble/.docs/hints.md
exercises/concept/cars-assemble/.docs/instructions.md
exercises/concept/cars-assemble/.docs/introduction.md
exercises/concept/cars-assemble/.meta/config.json
exercises/concept/cars-assemble/.meta/design.md
exercises/concept/cars-assemble/.meta/exemplar.go
exercises/concept/cars-assemble/cars_assemble.go
exercises/concept/cars-assemble/cars_assemble_test.go

Closes #1936
The `conditionals-if` and `comparison` concepts were removed from this
exercise because they are now covered by the vehicle-purhcase exercise
(added by ae2f5e7).

cars-assemble: Rework to cover only numbers & arithmetic-operators

---

exercises/concept/booking-up-for-beauty/.docs/instructions.md

FIxes: #2035 
Quick fix for `booking-up-for-beauty` exercise 5:
- changed output example to: `2020-09-15 00:00:00 +0000 UTC`
- added end note to specify returning type and that time of day doesn't matter

booking-up-for-beauty: fix instructions output for exercise 5

---

exercises/concept/cars-assemble/.docs/instructions.md

Escaping asterisks in instruction text cause it is being interpreted as special caracter.

Escape asterisks

---

exercises/practice/nucleotide-count/.docs/instructions.append.md

The link at the end of the description goes to a GitHub page that is out
of date—the link is a 404. In addition, I think it makes more sense to link
to the leap exercise on Exercism's own site rather than to a raw markdown
document on GitHub.
I've updated the link accordingly.

Fix broken link in nucleotide-count's description

---

exercises/concept/lasagna-master/.docs/hints.md
exercises/concept/lasagna-master/.docs/instructions.md

The instructions for _Lasagna Master_ say "array(s)" in several places
when referring to slices, which might be confusing given that they are
different, incompatible data structures in Go.

Lasagna Master: Fix references to "array"

---

concepts/slices/about.md

Remove index 2 value from example output as the ending index is exclusive in about.md
Fix the typo in the example output.
https://go.dev/play/p/6YZqXuuvvXa

Remove index 2 value from example output

---

exercises/practice/prime-factors/prime_factors_test.go

For this exercise, a solution that simply creates a slice with its default value fails the tests:
```go
func Factors(n int64) []int64 {
var factors []int64
for i := int64(2); i <= n; i++ {
for n%i == 0 {
factors = append(factors, i)
n /= i
}
}
return factors
}
```
```console
$ go test
--- FAIL: TestPrimeFactors (0.00s)
prime_factors_test.go:15: FAIL no factors
Factors(1) = []int64(nil);
expected []int64{}
FAIL
exit status 1
FAIL    prime   0.001s
```
In the previous solution, changing the declaration of `factors` to `factors :=  make([]int64, 0)` will make the tests pass.
This PR makes the slice comparison not care if an empty slice is created explicitly created with make, or has its `nil` default value.

prime-factors: allow empty nil slices

---

config.json

Resolves #2067 
This will make the exercise show up as "medium" instead of "easy" on the website. We can change this back once all the needed concepts are in place if someone feels this is necessary.

Increase difficulty for parallel letter frequency

---

exercises/practice/parallel-letter-frequency/.docs/instructions.append.md

This is a suggestion how to maybe address https://github.com/exercism/go/issues/1941#issuecomment-1013750311

Parallel Letter Frequency: Add hint towards benchmarks in instructions

---

concepts/runes/about.md
concepts/runes/introduction.md
exercises/concept/logs-logs-logs/.docs/hints.md
exercises/concept/logs-logs-logs/.docs/introduction.md

- Hint no. 2: Mention the conversion of `rune`s before they can be concatenated to a `string`
- Introduction: Add an import to the last example
Resolves #2070

logs-logs-logs: Add details to docs

---

concepts/type-conversion/about.md

The original example was using a type `int` and will fail with compiler error : `type int is not an expression`

Fix the type conversion example

---

exercises/concept/need-for-speed/need_for_speed_test.go

There are multiple community solutions where the _**"CanFinish"**_ method has a check to keep driving the car until the battery is less than 1. But that logic is incorrect because the car can be driven only when:
`car.battery > car.batteryDrain`.
This case does not get tested because all the test cases are such that either battery is a multiple of batteryDrained or 
`battery - (batteryDrained*some_multiple)=1`.  Hence the modification to the test case.
Here, for initial condition of,
`car: Car{
speed:        2,
batteryDrain: 6,
battery:      100,
distance:     5,
},
track: Track{
distance: 80,
}`
After car is driven completely,
`car: Car{
speed:        2,
batteryDrain: 6,
battery:      4,
distance:     37,
},`
For solutions with logic "drive car until battery is less than 1" will fail as …

Modifying a test case to verify that car cannot finish the track distance

---

exercises/concept/the-farm/the_farm_test.go

One of the tests returns 1, but in the description says it should return 5. This patch set just updates the description to say 1 instead.
```
{
description:             "Scale returns 5 with ErrScaleMalfunction for 10 cows",
weightFodder:            testWeightFodder{fodder: 5, err: ErrScaleMalfunction},
weightFodderDescription: "5 fodder, ErrScaleMalfunction",
cows:                    10,
wantAmount:              1,
wantErr:                 nil,
},
```

the-farm: fixes typo in one of the test descriptions

---

concepts/basics/about.md
concepts/basics/introduction.md

Rephrasing introduction and about, since golang.org was replaced by go.dev.
Fixes https://github.com/exercism/go/issues/2085

fix: rephrasing introduction.md and about.md since golang.org was replaced by go.dev

---

.github/workflows/exercise-tests.yml

Follow-up of: #2093
I noticed that the tests present in the "includes" section were not specifying a version of Go to run. Due to this, they were using a cached version of Go that happened to be go 1.15. This PR forces a specific version on these tests, in this case `go 1.17`, that is the same version the other tests run.
With this change, the names of some jobs would be the same, so I also made the name of the job include the architecture to disambiguate.

Fix extra tests for arch 386 running in an older version of Go

---

exercises/concept/gross-store/.docs/instructions.md

There proper format is key: value not key, value

docs(gross-store): Typo in map literal

---

exercises/practice/hamming/.docs/instructions.append.md

From the [Hamming](https://github.com/exercism/go/blob/main/exercises/practice/hamming/.docs/instructions.append.md) exercise:
> You may be wondering about the `cases_test.go` file. We explain it in the [leap exercise](https://github.com/exercism/go/blob/main/exercises/practice/leap/.docs/instructions.md).
The link leads to the `instructions.md` file which has no explanation about the `cases_test.go` and I found it very confusing.
I suggest changing it so it leads to the actual exercise on the website.

hamming: Update link leading to leap exercise

---

exercises/practice/robot-simulator/.docs/instructions.append.md

Right now these commands appear all in one line since whitespace is being ignored. This makes the text very confusing to read:
This PR fixes this by introducing a new bash code block where whitespaces are respected.

robot-simulator: Fix formatting on append instructions

---

exercises/concept/sorting-room/.docs/instructions.md
exercises/concept/sorting-room/sorting_room_test.go

Resolves #2106
Sorting room instructions: 
- fix in first sentence in Section 2 #2106
- changes to function arguments in example in Sections 2 #2106
- changes to function arguments in examples in Sections 3 and 4. #2110 
sorting_room_test.go, func TestExtractFancyNumber: 
- changed "differentFancyNumber" test case #2106
- added a new test case for "FancyNumber with invalid string"

Sorting room: instructions and test cases.

---

exercises/concept/bird-watcher/bird_watcher_test.go

This _seems_ like is a fairly minor change to make error messages in a particular `bird-watcher` test a bit easier to understand. On the other hand, it's totally possible a change like this would open the door to needing to look for any other "mutates input slice" examples. But at any rate, I wanted to raise the question as I'm going through these exercises. Thanks for creating and maintaining them!
Before this change, a mistake in the implementation, such as `i%2 == 1` instead of `i%2 == 0`, the error messages were a bit confusing for the learner (or at least for me 😃):
bird_watcher_test.go:101: FixBirdCountLog([3 1 5 2 0 5 1 1 3 5 3 1]) = [3 1 5 2 0 5 1 1 3 5 3 1]; want [4 0 6 1 1 4 2 0 4 4 4 0]
Note in the above that the *actual* input slice was `[3 0 5 1 0 4 1 0 3 4 3 0]`, and so the …

Clarify error message for bird-count

---

config.json
exercises/concept/card-tricks/.docs/hints.md
exercises/concept/card-tricks/.docs/instructions.md
exercises/concept/card-tricks/.docs/introduction.md
exercises/concept/card-tricks/.meta/config.json
exercises/concept/card-tricks/.meta/design.md
exercises/concept/card-tricks/.meta/exemplar.go
exercises/concept/card-tricks/card_tricks.go
exercises/concept/card-tricks/card_tricks_test.go

Adapted card tricks to  current concept tree progression 
Fixes #1990
* Removed the task about `PrefilledSlice` from all the relevant exercise files
* Added function `FavoriteCards` which returns a new slice filled with numbers 2,5,9. Added to docs and added a test.
* Changed `GetItem` to have only one return value. Updated tests accordingly.
* Added code in `TestSetItem` which checks that `SetItem(slice,index)` modifies the
existing slice as long as `index` is within slice bounds.
* Added a variadic function `PrependItems`.  Added to docs and added a test.
* Added the content of `concepts/variadic-functions/introductions.md` to the introduction.
* Added more info about the inbuilt `append` function to hints and instructions.
* Updated the root level `config.json` in line with #1990 …

Card Tricks: Adapt to current concept tree progression #1990

---

exercises/concept/blackjack/blackjack_test.go

Added default test case to TestParseCard. 
name: "parse invalid", card: "joker", want: 0
Related to Issue2137: https://github.com/exercism/go/issues/2137

Add missing test case for Blackjack (#2136)

---

exercises/practice/yacht/.meta/tests.toml
exercises/practice/yacht/cases_test.go

The test cases prior to this change do not require the "fives" category to be implemented. This test case ensures it is implemented.

Added test case to ensure fives is implemented

---

exercises/practice/tree-building/tree_building.go
exercises/practice/tree-building/tree_building_test.go

Fixes issue #2142 "Tree building exercise test results unclear"
* Added declaration of types `Node` and `Record` in `tree_building.go`
* Defined a `nodeEqual` method and used this for node-equality comparisons in tests

Tree-building exercise: added custom nodeEqual method, added type def

---

exercises/concept/vehicle-purchase/.docs/hints.md
exercises/concept/vehicle-purchase/.docs/instructions.md
exercises/concept/vehicle-purchase/.docs/introduction.md
exercises/concept/vehicle-purchase/.meta/exemplar.go
exercises/concept/vehicle-purchase/vehicle_purchase.go

Fixes #2147
Removed spurious link to UTF-16
Renamed "dictionary order" to "lexicographical order" in several places

Vehicle purchase exercise - removed UTF-16 ref, renamed ordering

---

concepts/regular-expressions/.meta/config.json
concepts/regular-expressions/about.md
concepts/regular-expressions/introduction.md
concepts/regular-expressions/links.json
config.json
exercises/concept/parsing-log-files/.docs/hints.md
exercises/concept/parsing-log-files/.docs/instructions.md
exercises/concept/parsing-log-files/.docs/introduction.md
exercises/concept/parsing-log-files/.meta/config.json
exercises/concept/parsing-log-files/.meta/design.md
exercises/concept/parsing-log-files/.meta/exemplar.go
exercises/concept/parsing-log-files/go.mod
exercises/concept/parsing-log-files/parsing_log_files.go
exercises/concept/parsing-log-files/parsing_log_files_test.go

Fixes #2037
* Concept regular expressions (in Go)
* Concept exercise
The first four tasks in the concept exercise are based on tasks in the corresponding C# exercise.

Regular expression concept with exercise

---

concepts/arithmetic-operators/about.md
concepts/arithmetic-operators/introduction.md
exercises/concept/cars-assemble/.docs/introduction.md
exercises/concept/election-day/.docs/hints.md
exercises/concept/party-robot/.docs/instructions.md
exercises/concept/sorting-room/.docs/hints.md

Add a "." to "e.g." to make it consistent with the other uses.

Typo: e.g.

---

exercises/concept/the-farm/.docs/instructions.md

Reference to `ErrScaleMalfunction` was missing syntax highlighting.

the-farm: add missing syntax highlighting in instructions

---

concepts/strings/.meta/config.json
concepts/strings/about.md
concepts/strings/introduction.md
exercises/concept/welcome-to-tech-palace/.docs/introduction.md
exercises/concept/welcome-to-tech-palace/.meta/config.json

Before this commit, the introduction of this exercise has been a bit confusing for learners due to its incompleteness.

add more details and examples to the introduction

---

exercises/concept/animal-magic/.meta/config.json

"Animal Magic" was kind of forked from "Roll the die" but the name was changed. Therefore the icon is not selected automatically. This PR sets the icon explicitly.

Animal Magic: Set Icon

---

exercises/concept/lasagna/lasagna_test.go

There was an error where `tt.expected` was being sent in as the `actualTimeInOven`, where it should have been `tt.time`
I also fixed a couple of typos in the test names.

Fix error in TestRemainingOvenTime, fix typos

---

exercises/practice/linked-list/.meta/example.go
exercises/practice/linked-list/linked_list.go
exercises/practice/linked-list/linked_list_test.go

Fixes #2090.
Per discussion in #2090, this PR provides a note as a hint for students to add a `Value` field to `Node`. This PR also changes the tests that access the `Val` field to favor `Value` field per track maintainer's judgement call.

Issue #2090: linked list add note for Node struct field Value

---

docs/TESTS.md
exercises/practice/bank-account/.docs/instructions.append.md

Fixes #2155.
Workflow job for Windows failed due to timeout. Cannot re-run jobs so maybe a maintainer could help out? 🙏

#2155: Clarify when an exercise is tested with the `-race` flag

---

exercises/concept/need-for-speed/.docs/instructions.md

Fixes #2105. Added some explanation for the instruction to ensure some students would take into account that the `distance` and `battery` in the test cases might not be pristine.

Fixes #2105: Need for Speed - Clarify instruction text on distance & battery condition

---

exercises/concept/expenses/.docs/instructions.md
exercises/concept/expenses/.docs/introduction.md

Replace "Output:" for "=>" in example codes.
Related issue: #2202

Fixed "Output" - Expenses exercise 

---

concepts/pointers/about.md
concepts/pointers/introduction.md
exercises/concept/election-day/.docs/introduction.md

Description
----
There's a small typo in the explanation for the "Slices and maps are already pointers" paragraph `that not` becomes `than not` :)

Fix typo in slices and maps paragraph

---

exercises/practice/clock/.docs/instructions.append.md

Description
----
Currently the links in the instructions aren't hyperlinks due to missing markdown formatting. This PR addresses that issue updating the link formatting :)

Clock: Update instructions markdown links

---

exercises/concept/logs-logs-logs/.docs/instructions.md
exercises/concept/logs-logs-logs/.docs/introduction.md
exercises/concept/logs-logs-logs/logs_logs_logs_test.go

Add more tests to cover case that is described here https://github.com/exercism/go/issues/2232
With logic from issue:
```golang
type Applications struct {
Key   rune
Value string
}
//mapping based on struct to have an as defined ordered array
var mapping = []Applications{
{ Key:   '❗', Value: "recommendation" },
{Key:   '🔍', Value: "search"},
{Key:   '☀',Value: "weather"},
}
// Application identifies the application emitting the given log.
func Application(log string) string {
for _, val := range mapping {
if strings.ContainsRune(log, val.Key) {
return val.Value
}
}
return "default"
}
```
With new tests it catches case where the first element in the variable `mapping` isn't the same as in the input log for `Application` function. …

logs-logs-logs: add more tests to better cover multiple characters case

---

concepts/functions/about.md
concepts/functions/introduction.md
exercises/concept/lasagna-master/.docs/introduction.md

I am afraid that there is a mismatch of "arguments" and "parameters" in the Functions introduction. Regarding the description above (Parameters vs. Arguments) the sentence discusses "parameters" instead of "arguments".

fix function arguments and parameters missmatch

---

exercises/concept/meteorology/.docs/instructions.md

It seemed there was a minor mistake where the wrong variable was used, compared to the outlined result

Minor mistake in exercise 3. example

---

exercises/practice/isbn-verifier/isbn_verifier_test.go

Fixes:
- made each dataset execute in a separate TC
It allows IDEs to differentiate test runs with different data. VS Code as an example below.
- removed PASS logs so only fails are displayed on `go test`
- CLI output
```
PS C:\Users\iavto\Documents\go\isbn-verifier> go test
--- FAIL: TestIsValidISBN (0.00s)
isbn_verifier_test.go:25: FAIL: valid isbn number
IsValidISBN("3-598-21508-8")
Expected: true, Actual: false
isbn_verifier_test.go:23: PASS: invalid isbn check digit
isbn_verifier_test.go:23: PASS: valid isbn number with a check digit of 10
isbn_verifier_test.go:23: PASS: check digit is a character other than X   
isbn_verifier_test.go:23: PASS: invalid character in isbn
isbn_verifier_test.go:23: PASS: X is only valid as a check digit
isbn_verifier_test.go:25: FAIL: valid isbn without …
```

isbn_verifier task: run each test dataset in a separate TC

---

exercises/concept/elons-toys/.docs/instructions.md

It seems to be not clear what does the note mean:
> Note: If a car's battery is below **its battery drain percentage**, you can't drive the car anymore.
Changed to the more clear definition. 

elons-toys: improve description for first stage

---

concepts/structs/.meta/config.json
concepts/structs/about.md
concepts/structs/introduction.md
exercises/concept/need-for-speed/.docs/instructions.md
exercises/concept/need-for-speed/.docs/introduction.md
exercises/concept/need-for-speed/.meta/config.json

Fixes #1755
Hey, I have done the following:
- adjusted the `instructions.md` to clarify the struct-initialization and the usage of constructors
- renamed variables for consistency

Need for Speed: Minor improvements (#1755)

---

exercises/concept/cars-assemble/.docs/instructions.md

Cars Assemble
For easy tracking #2202

Changed "Output" to "=>" - Cars Assemble (Fixes #2196)

---

concepts/type-assertion/about.md
concepts/type-assertion/introduction.md
exercises/concept/sorting-room/.docs/introduction.md

While reading the [Type Assertion](https://exercism.org/tracks/go/concepts/type-assertion) for the [Sorting Room](https://exercism.org/tracks/go/exercises/sorting-room) exercise I noticed that the [Type Switch example](https://exercism.org/tracks/go/concepts/type-assertion#:~:text=default%20value%22%0A%7D-,Type%20Switches,-A%20type%20switch) is using `Println` with `Printf` format strings.
```go
switch v := i.(type) {
case int:
fmt.Println("the integer %d", v)
case string:
fmt.Println("the string %s", v)
default:
fmt.Println("some type we did not handle explicitly")
}
```
This pull-request fixes that in two files and improves the example a little.

concepts/type-assertion: fix change fmt.Println to fmt.Printf and improve type switch example

---

exercises/practice/diamond/.meta/example.go
exercises/practice/diamond/.meta/gen.go
exercises/practice/diamond/.meta/tests.toml
exercises/practice/diamond/cases_test.go
exercises/practice/diamond/diamond_test.go

Hey, I have done the following steps:
- added a test-case generator for the test-cases defined in [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/diamond/canonical-data.json) in `gen.go`
- regenerated the `tests.toml` using configlet
- generated the `cases_test.go` using the `gen.go`
- added `func TestDiamond` using this test-cases
I additionally adjusted the existing tests, as they expected a `\n` at the end. Regarding to the `instructions.md` there should not be a new-line at the end, for example:
Diamond for letter 'E':
```text
····A····
···B·B···
··C···C··
·D·····D·
E·······E
·D·····D·
··C···C··
···B·B···
····A····
```
Reach out to me if this change should be reverted and a `\n` should be expected at the end.
Closes #2222

Added the test-cases from canonical-data.json to exercise diamond

---

concepts/booleans/about.md
concepts/booleans/introduction.md
concepts/strings-package/about.md
concepts/strings-package/introduction.md

Replace "Output:" for "=>" in some remaining files
Related issue: #2202

Fixed "Output" (#2202) - Some Remaining files

---

concepts/strings/about.md
concepts/strings/introduction.md
exercises/concept/welcome-to-tech-palace/.docs/instructions.md
exercises/concept/welcome-to-tech-palace/.docs/introduction.md

Changed "Output" to "=>" - Welcome To The Tech Palace
Related to #2202

Fixed "Output" - Welcome To The Tech Palace (Fixes #2156)

---

exercises/practice/bank-account/.docs/instructions.append.md

The h2 header that differentiates the problem spec instructions from the language specific one was removed with https://github.com/exercism/go/pull/2260. Now the rendered instructions on the website look strange because after "Have fun!" there is "Opening an account". https://exercism.org/tracks/go/exercises/bank-account 
This PR changes the headers so they should result in a better flow when put together with the canonical instructions.

Fix headers in bank account instructions append

---

concepts/basics/introduction.md

This does not fix an open issue, and is not strictly necessary.
I noticed as I was going through the introductory Hello World exercise that the doc comments in the instructions didn't follow the best practices that we're trying to encourage people to follow. This adds punctuation to a couple of example function comments.

Add punctuation to function comments in concept instructions

---

exercises/practice/simple-cipher/simple_cipher_test.go

- made tests to output all failed data examples instead of one only
_Before_
```
=== RUN   TestShift
simple_cipher_test.go:58: Shift(3) Encode("Go, go, gophers") = "jrWjrWjrskhuv", want "jrjrjrskhuv".
```
_Now_
```
=== RUN   TestShift
simple_cipher_test.go:58: Shift(3) Encode("Go, go, gophers") = "jrWjrWjrskhuv", want "jrjrjrskhuv".
simple_cipher_test.go:58: Shift(3) Encode("I am a panda bear.") = "lWdpWdWsdqgdWehdu", want "ldpdsdqgdehdu".
simple_cipher_test.go:58: Shift(3) Encode("Programming is AWESOME!") = "surjudpplqjWlvWdzhvrph", want "surjudpplqjlvdzhvrph". 
```
- changed Encode test error log to contain an original string instead of the one with cleared extra symbols
_Before_
```
simple_cipher_test.go:26: Caesar Encode("todayisholiday") = "wrgdlvkrolgd", want "wrgdblvkrolgdb".
``` …

improved output for simple_cipher test

---

exercises/concept/logs-logs-logs/logs_logs_logs_test.go

Fixes #2292
- added more test cases for exercise in accordance with [issue](https://github.com/exercism/go/issues/2292)
This hardcoded function was able to pass all tests.
```
func WithinLimit(log string, limit int) bool {
return limit >= len(log)-2
}
```
_Before_
```
PASS
ok      test    0.001s
```
_Now_ 
```
--- FAIL: TestWithinLimit (0.00s)
--- FAIL: TestWithinLimit/exact_limit#01 (0.00s)
main_test.go:147: WithinLimit("exercism🔍", 9) = false, want true
FAIL
exit status 1
FAIL    test    0.002s
```

Additional test cases for logs-logs-logs

---

exercises/concept/parsing-log-files/.meta/config.json
exercises/concept/parsing-log-files/parsing_log_files_test.go

Hey, when doing the exercise `parsing-log-files` I have seen that the following solution passes all tests:
```
var validLinePrefixes = map[string]struct{}{"[TRC]": {}, "[DBG]": {}, "[INF]": {}, "[WRN]": {}, "[ERR]": {}, "[FTL]": {}}
func IsValidLine(text string) bool {
_, validPrefix := validLinePrefixes[text[:5]]
return validPrefix
}
```
Therefore I have added a test case that is covering a line that is shorter than 5 characters

parsing-log-files: added test case

---

concepts/functions/about.md
concepts/functions/introduction.md
exercises/concept/lasagna-master/.docs/introduction.md

Noticed when working through the Functions concept exercise that the `functions` concept doc has a weird break in it:
<image src="https://user-images.githubusercontent.com/5923094/178777530-037c4fec-5413-4e34-a411-9308d1df5233.png" width=500px>
<br>
Added the word `statements` in place of the `s` for clarity.

[Functions Concept]: Added word statements to the return section for clarity

---

exercises/concept/census/.meta/config.json
exercises/concept/census/census_test.go

Hey, when mentoring I got the following solution:
```
// HasRequiredInfo determines if a given resident has all of the required information.
func (r *Resident) HasRequiredInfo() bool {
if r.Name == "" {
return false
}
for _, v := range r.Address{
if v != "" {
return true
}
}
return false
}
```
Instructions: In order to be counted, a resident must provide a non-zero value for their name and an address that contains a non-zero value for the `street` key.
It only checks if any key in `r.Address` is set, but not if `street` is set and this passes the tests.
Therefore I have added a test case

census: added test case

---

exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/atbash-cipher/.meta/gen.go
exercises/practice/atbash-cipher/.meta/tests.toml
exercises/practice/atbash-cipher/atbash_cipher_test.go
exercises/practice/atbash-cipher/cases_test.go

One of #2302 
Regarding to [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/atbash-cipher/canonical-data.json) there are also test cases for decoding. Do we want to add the decoding to this exercise, or is there a reason why it is no here?

atbash-cipher: updated exercise generator to new test generator

---

exercises/practice/anagram/.docs/instructions.md
exercises/practice/anagram/.meta/config.json
exercises/practice/anagram/.meta/gen.go
exercises/practice/anagram/.meta/tests.toml
exercises/practice/anagram/anagram_test.go
exercises/practice/anagram/cases_test.go

One of #2302 
Here I am not completely sure which of the test cases with `reimplements` to include. Especially for the `words are not anagrams of themselves` thing.

anagram: updated exercise generator to new test generator

---

exercises/practice/grains/.meta/config.json
exercises/practice/grains/.meta/gen.go
exercises/practice/grains/cases_test.go
exercises/practice/grains/grains_test.go

One of #2302 
I left the expected value for `TestTotal` in `grains_test.go` as this seems better than having to parse the big value `18446744073709551615`

grains: updated exercise generator to new test generator

---

exercises/concept/animal-magic/.meta/exemplar.go
exercises/concept/animal-magic/animal_magic.go
exercises/concept/annalyns-infiltration/.meta/exemplar.go
exercises/concept/annalyns-infiltration/annalyns_infiltration.go
exercises/concept/booking-up-for-beauty/.meta/exemplar.go
exercises/concept/booking-up-for-beauty/booking_up_for_beauty.go
exercises/concept/card-tricks/.meta/exemplar.go
exercises/concept/cars-assemble/.meta/exemplar.go
exercises/concept/cars-assemble/cars_assemble.go
exercises/concept/census/census_test.go
exercises/concept/chessboard/.meta/exemplar.go
exercises/concept/chessboard/chessboard.go
exercises/concept/deep-thought/.meta/exemplar.go
exercises/concept/election-day/.meta/exemplar.go
exercises/concept/election-day/election_day.go
exercises/concept/election-day/election_result.go
exercises/concept/expenses/.meta/exemplar.go
exercises/concept/expenses/expenses.go
exercises/concept/gross-store/.meta/exemplar.go
exercises/concept/interest-is-interesting/.meta/exemplar.go
exercises/concept/interest-is-interesting/interest_is_interesting.go
exercises/concept/lasagna-master/.meta/exemplar.go
exercises/concept/savings-account/.meta/exemplar.go
exercises/concept/savings-account/savings_account.go
exercises/concept/sorting-room/.meta/exemplar.go
exercises/concept/the-farm/.meta/exemplar.go

We have an exercise that explicitly teaches people to use proper punctuation for doc comments.
This adds punctuation where it's missing from doc comments in the stub files for other concept exercises.
I've also removed a doc-style comment from one of the concept exercise test files, since we don't want to implicitly encourage people to write doc comments for their tests.

Clean up doc comments in concept exercises

---

exercises/concept/annalyns-infiltration/annalyns_infiltration_test.go

In this exercise the instructions say that the prisoner MUST be
awake in order to be rescued, as if they are sleeping they'll be
startled by the rescue attempt, which will alert the guards.
Today we saw a solution that would have allowed Annalyn to rescue
a sleeping prisoner if she didn't have her dog along.
This adds a couple of extra cases for that scenario.
The exemplar correctly implements the function, and should therefore
pass the new tests.

Add missing test cases for Annalyn's Infiltration

---

exercises/concept/lasagna/lasagna.go

Instead of the total time needed to prepare + bake a lasagna, which only
depends on the amount of layers, ElapsedTime calculates the time that
has passed until a specific moment in the baking process. This matches
the function signature, as it depends on the amount of layers and the
minutes it has been in the oven so far.

lasagna: Fix ElapsedTime doc comment

---

exercises/concept/census/.meta/exemplar.go
exercises/concept/census/census_test.go

This PR adds missing test case to go [Census exercise](https://exercism.org/tracks/go/exercises/census).
1. Added `r.Address == nil` test case
2. Updated solution in exemplar.go file
Closes #2352.

Added nil test case to census exercise

---

exercises/concept/card-tricks/.meta/exemplar.go
exercises/concept/card-tricks/card_tricks.go

This gets me every time I mentor this exercise.

card-tricks: use "values" instead of "value" in `PrependItems` function

---

exercises/practice/scale-generator/.docs/instructions.md
exercises/practice/scale-generator/.meta/config.json
exercises/practice/scale-generator/.meta/example.go
exercises/practice/scale-generator/.meta/gen.go
exercises/practice/scale-generator/.meta/tests.toml
exercises/practice/scale-generator/cases_test.go
exercises/practice/scale-generator/scale_generator_test.go

One of #2302
Here I also had the refactor `example.go` as the there was a big change in the test cases: https://github.com/exercism/problem-specifications/pull/1888

scale-generator: updated exercise generator to new test generator

---

exercises/concept/interest-is-interesting/interest_is_interesting_test.go

Adding the edge case when target balance has been already reached on the first iteration.
This will make student to learn checking for edge conditions

added the edge test case for `YearsBeforeDesiredBalance()`

---

exercises/concept/census/census_test.go

fixes #2386 
scope of changes:
- added one testCase with empty name and not empty address with street
- added one testCase with empty name and not empty address with other field than street
this code fails 2 cases from TestCount/some_data_collected now (was 0 before)
```go
func Count(residents []*Resident) int {
counter := 0
for _, resident := range residents {
if len(resident.Address) != 0 {
counter += 1
}
}
return counter
}
```
If user validates all fields or refer to already written function, it should be ok.

census: add more tests for Count()

---

exercises/practice/meetup/meetup.go

The solution for the exercise was included in the stub by mistake in #2343
This reverts the stub back to not include the solution.

meetup: revert stub to not include the solution

---

exercises/concept/card-tricks/.docs/instructions.md

Add admonition for returning out-of-band value.
Closes #2323 
I've done only one other admonition before and don't remember if a link can be embedded in one.
Perhaps the link is not a good idea.

[Card Tricks] add admonition

---

exercises/concept/welcome-to-tech-palace/.docs/instructions.md

Following the others examples starting with `=> ` the previuos example was wronlgy suggesting `\n` at the start of the string.

Wrong formatted example

---

exercises/concept/animal-magic/animal_magic_test.go

Proposed test case to improve testing of GenerateWandEnergy() task of Animal Magic.
The tests currently pass if a student uses randomly generated ints and then typecasts the result to float64 which doesn't meet the requirements.
`tests` was bumped to ensure that even if a random seed is used, the test should pass. For grins, I ran the bucket test 1M times with various values for `tests` and it passed at 150. I bumped to 200 for extra margin.
Assuming no issues, I will give the same treatment to the other two tasks in the exercise.
#2417

Animal Magic: Added test case for GenerateWandEnergy()

---

exercises/concept/animal-magic/animal_magic_test.go

Potential fix for https://github.com/exercism/go/actions/runs/2851358812
I found some indications that there might be issues when calling rand.Seed to close after each other might cause issues here. Maybe leaving some more time between the calls will fix the issue that the test is flaky on windows. Worst case the test case can take 1s now which is ok imo.

Fix flaky animal magic test on windows

---

.golangci.yml
exercises/concept/animal-magic/.meta/exemplar.go
exercises/concept/animal-magic/animal_magic_test.go
exercises/practice/binary-search/binary_search_test.go
exercises/practice/custom-set/custom_set_test.go
exercises/practice/diamond/diamond_test.go
exercises/practice/diffie-hellman/.meta/example.go
exercises/practice/diffie-hellman/diffie_hellman_test.go
exercises/practice/grade-school/grade_school_test.go
exercises/practice/tree-building/tree_building_test.go

Updated test files so that `gosec` ignores `math/rand`.  Files updated based on [this CI job](https://github.com/exercism/go/runs/7734762492?check_suite_focus=true) 
For these exercises `math/rand` is better a better option than `crypto/rand` based on suggestion in PR #2416

Ignore Security Warnings for math/rand

---

exercises/concept/parsing-log-files/.docs/instructions.md

Hi 👋
I noticed that a code example in the `instructions.md` file of one of the Go exercise had semicolons (`;`) which are usually not part of the language. I made a PR to remove them.
Cheers

Remove semicolon from a Go code example

---

exercises/practice/house/.meta/config.json
exercises/practice/house/house_test.go

added usage of subtests to the house exercise

---

exercises/practice/matrix/.meta/config.json
exercises/practice/matrix/matrix_test.go

One of #2098
How to we want to handle the unused testcases?
```
// undefined
// {"\n\n", // valid?, 3 rows, 0 columns
// {"",     // valid?, 0 rows, 0 columns
```
For me the first one would be invalid, as these cases are also invalid:
```
{description: "first row empty", in: "\n3 4\n5 6", ok: false, rows: nil, cols: nil},
{description: "middle row empty", in: "1 2\n\n5 6", ok: false, rows: nil, cols: nil},
{description: "last row empty", in: "1 2\n3 4\n", ok: false, rows: nil, cols: nil},
```
The second one should be valid and a empty matrix
What do you think about this one?

added usage of subtests for exercise matrix

---

concepts/stringers/about.md
concepts/stringers/introduction.md
exercises/concept/meteorology/.docs/introduction.md

Fix `contant` typo across all files in the repo. Originally reported in https://github.com/exercism/go/pull/2233#issuecomment-1214551332

Fix 'constant' typo

---

exercises/practice/grep/grep_test.go

This commit addresses an incorrectly failing test case.
grep_test.go:68: Search("may",[-x],[midsummer-night.txt])
got: []
want: []
Although both slices are zero length, one is initialized, and one is not.
expected: []string len: 0, cap: 0, []
actual:   []string len: 0, cap: 0, nil
Added logic to test for zero length for actual and expected if DeepEqual is false.

Exercise grep : fix test case which incorrectly fails on nil slice, but expect empty slice

---

exercises/concept/animal-magic/animal_magic_test.go

Issue [#2484](https://github.com/exercism/go/issues/2484)
Add 1 to the wait time so that it never becomes 0 thereby eliminating the scenario where the seed is same as before.

Issue# 2484 - Added 1 to the waiting time

---

exercises/practice/roman-numerals/.docs/instructions.md
exercises/practice/roman-numerals/.meta/example.go
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/cases_test.go
exercises/practice/roman-numerals/roman_numerals_test.go

Adjust Instructions and Unit Tests to support maximum Roman numeral 3999
Resolves https://github.com/exercism/go/issues/2475
Adjustment to problem specification, instructions, and unit tests to support the max val 3,999 which can be expressed in Roman numerals (without getting into the "Larger number" scenarios)

Issue 2475 roman numerals max 3999

---

exercises/practice/two-fer/.meta/config.json
exercises/practice/two-fer/two_fer_test.go

One of #2098 
What is `example_two_fer_test.go` for? Can we delete it?

added usage of subtests for two-fer

---

docs/ABOUT.md

Updated the links to the official golang website.
The given links in the ABOUT.md have changed;
`golang.org` has changed to `go.dev` and `tour.golang.org` has changed to `tour.go.dev`.
This commit fixes this issue.

Updated link in docs/ABOUT.md

---

exercises/practice/queen-attack/.meta/config.json
exercises/practice/queen-attack/queen_attack_test.go

added usage of subtests for queen-attack

---

exercises/concept/booking-up-for-beauty/.docs/hints.md

Hint for `time.Parse` alone is not helpful. Even minor changes can render the time incorrect. This could be frustrating for learners.

Added Additional Hint for Processing Parts of a Date

---

exercises/practice/flatten-array/flatten_array_test.go

For the Flatten Array Exercise - Update `TestFlatten` to allow initialized zero-length slices or un-initialized(nil) slices to represent the empty slice. 
Fixes #2483

Flatten Array - Improve error message for nil slice

---

concepts/slices/about.md
concepts/slices/introduction.md
exercises/concept/card-tricks/.docs/introduction.md

Add information about merging slices with append

Update about.md in About Slices concept

---

exercises/practice/sieve/sieve_test.go

Previously any code for the Go sieve exercise which returned an empty slice would pass all the tests. This PR modifies the logic so that a test only passes with an empty slice when such an empty slice is expected by the test.
Fixes #2497

Sieve: Fix empty slice test

---

README.md
bin/fetch-golangci-lint

Fixes #2499
- update golangci-lint to version 1.49.0 (most recent release)
- update contributor documentation with correct script name for running the test suite
Credit to @mikejoh12 for discovering that tests were not working locally for M1 Macs and prompting me to dig into it further.

Update test dependencies and docs

---

exercises/practice/transpose/transpose_test.go

For the Go Transpose problem returning an empty slice in this exercise would pass all the tests. This modifies the TestTranspose function so it only passes an empty slice when such a slice is expected by the test.
Fixes #2502

Transpose: Fix empty slice test

---

exercises/concept/meteorology/.docs/instructions.md

I don't really understand why the line of code is there, maybe because of historical reasons?
To me, it makes no sense, the variable is not used anywhere. I've found it confusing when doing the exercise, so I'm proposing to delete it.

removed unnecesary line of example code in Meteorology exercise

---

config.json
exercises/practice/bottle-song/.docs/instructions.md
exercises/practice/bottle-song/.meta/config.json
exercises/practice/bottle-song/.meta/example.go
exercises/practice/bottle-song/.meta/gen.go
exercises/practice/bottle-song/.meta/tests.toml
exercises/practice/bottle-song/bottle_song.go
exercises/practice/bottle-song/bottle_song_test.go
exercises/practice/bottle-song/cases_test.go
exercises/practice/bottle-song/go.mod

Closes #2505 
As discussed in https://github.com/exercism/problem-specifications/issues/2066 we would like to replace the beer-song exercise with [bottle-song](https://github.com/exercism/problem-specifications/tree/main/exercises/bottle-song). This PR deprecates the beer-song exercise and adds a new bottle-song exercise

Deprecate beer-song and add bottle-song

---

exercises/practice/complex-numbers/.meta/example.go
exercises/practice/complex-numbers/.meta/gen.go
exercises/practice/complex-numbers/cases_test.go
exercises/practice/complex-numbers/complex_numbers.go
exercises/practice/complex-numbers/complex_numbers_test.go

The package name is the same as a [builtin "function" to create complex numbers](https://pkg.go.dev/builtin#complex).
In this particular case, this doesn't cause any problems for the exercise - the builtin function is not shadowed, but it's probably a good idea not to have package names conflict with builtins anyway.

Make "complex-numbers" package name not be the same as a builtin

---

exercises/practice/sublist/.meta/config.json
exercises/practice/sublist/.meta/example.go
exercises/practice/sublist/relations.go
exercises/practice/sublist/sublist.go

There is **still** a missing definition for the data type **Relation** of the field expected in file cases_test.go. The exercise in the current state is not solvable.
The issue was not solved by #1335 neither by #1893.

sublist: Fixes sublist exercise by adding missing Relation type.

---

exercises/concept/interest-is-interesting/interest_is_interesting_test.go

Since the wrong logic could clear the tests, I figured that some tests are missing. 
By adding two test scenarios, they covers 
> 1. balance is already the exact same as the target
> 2. result balance would be the exact same as the target
(Following code should have failed the tests, but currently passing. The correct logic should be using < instead of <=)

Add missing tests for interest_is_interesting

---

exercises/concept/election-day/.docs/instructions.md

The usage of "it" de-personifies the president, and we can't use "he" or "she" as we don't know the president's gender. The correct grammar is to use "they" in this instance.

Fix grammar

---

exercises/concept/gross-store/gross_store_test.go

The error message for the test `TestAddItem/Invalid_measurement_unit` indicated the inverse of what it was checking for.
For example, the following function adds an item to the bill with a value of 0 if the item's unit wasn't found.
```Go
func AddItem(bill, units map[string]int, item, unit string) bool {
bill[item] += units[unit]
return units[unit] != 0
}
```
Without this change, the output indicates the inverse of what it seems to intend to:
```
--- FAIL: TestAddItem (0.00s)
--- FAIL: TestAddItem/Invalid_measurement_unit (0.00s)
gross_store_test.go:91: Could not find item pasta in customer bill
gross_store_test.go:91: Could not find item onion in customer bill
gross_store_test.go:91: Could not find item pasta in customer bill
```
After the change, the output is accurate and helpful:
``` …
```

gross-store: Rephrase error to be more clear

---

exercises/concept/elons-toys/elons_toys_test.go

The test covers the case when the implementation of `CanFinish` is done in multiple steps where in one of them the result which should be a `float` is assigned to an `int`.
This PR fixes  #2548
example of incorrect solution:
```
func (car Car) CanFinish(trackDistance int) bool {
neededCycles := trackDistance / car.speed
return car.battery-(car.batteryDrain*neededCycles) >= 0
}
```
Example of correct solution:
```
func (car *Car) CanFinish(trackDistance int) bool {
return car.battery-(car.batteryDrain*trackDistance/car.speed) >= 0
}
```

elons-toys: add test for elons_toys to cover track with possible remainder

---

bin/fetch-golangci-lint

Release notes: https://github.com/golangci/golangci-lint/releases/tag/v1.50.1

Bump golangci-lint to 1.50.1

---

exercises/concept/elons-toys/elons_toys_test.go

In my previous PR #2549 by accident I chose a trackdistance that is divisible by 3, which makes this test case useless.
With those fixes, the test case does actually fix the issue #2548.

elons-toys: fix test to cover the edge case it should cover

---

exercises/concept/lasagna-master/.meta/config.json

For now, we only set this for one exercise so we can confirm it works before enabling it for more.
This will not do anything until the new version of the test runner is deployed: https://github.com/exercism/go-test-runner/pull/93

Set up lasagna master for test runner version 3

---

exercises/concept/election-day/.meta/config.json
exercises/concept/lasagna-master/.meta/config.json

I am turning task ids off again because of https://github.com/exercism/go-test-runner/issues/94. Will enable them again later then the problem is addressed.

Disable task ids

---

concepts/slices/about.md
concepts/slices/introduction.md
exercises/concept/card-tricks/.docs/introduction.md

Some typo fixes for the slices concept:
- Fixes #2585 in all places.
- Grammarly pass over the contents

Typo fixes for the slices concept

---

exercises/practice/clock/clock_test.go

Closes #2621
<details>
<summary>New test output</summary>
<pre>
$ go test
--- FAIL: TestAddMinutesStringless (0.00s)
--- FAIL: TestAddMinutesStringless/add_across_midnight (0.00s)
clock_test.go:52: New(23, 59).Add(2)
Got: "00:01" (clock.Clock{minutes:1441})
Want: "00:01" (clock.Clock{minutes:1})
--- FAIL: TestAddMinutesStringless/add_more_than_one_day_(1500_min_=_25_hrs) (0.00s)
clock_test.go:52: New(5, 32).Add(1500)
Got: "06:32" (clock.Clock{minutes:1832})
Want: "06:32" (clock.Clock{minutes:392})
--- FAIL: TestAddMinutesStringless/add_more_than_two_days (0.00s)
clock_test.go:52: New(1, 1).Add(3500)
Got: "11:21" (clock.Clock{minutes:3561})
Want: "11:21" (clock.Clock{minutes:681})
--- FAIL: TestSubtractMinutesStringless (0.00s)
--- FAIL: …

clock: improve test output for "stringless" tests

---

exercises/concept/welcome-to-tech-palace/.docs/instructions.md

I am enjoying the #12in23 challenge and in March I am pursuing the Go track. Today's early morning exercise was [Welcome To Tech Palace! ](https://exercism.org/tracks/go/exercises/welcome-to-tech-palace). Part 2, "Add a fancy border" took a little longer than expected because I tried to add leading forward strokes as in the example. It looks like these were left-overs from when the output was included as a comment, rather than a separate block of text (b1461325).
See individual commits for finer details.
An alternative would be to revert #2404 but I think this example is clearer as others were confused by the newline.

Correct expected output in Welcome To Tech Palace! - 2. Add a fancy border

---

exercises/practice/resistor-color-duo/go.mod
exercises/practice/resistor-color-trio/go.mod
exercises/practice/resistor-color/go.mod

These exercises were added after I made https://github.com/exercism/go/pull/2609 and I forgot to update that PR to also bumping the go.mod version in these new exercises too. This PR fixes that.

Update resistor color exercises go.mod to 1.18

---

exercises/practice/protein-translation/.approaches/introduction.md

Fix for wrongly defined link from intro page to switch approach.

Protein Translation switch approach link fix

---

bin/fetch-golangci-lint
exercises/practice/linked-list/linked_list_test.go

No particular reason for this upgrade other than not letting golangci-lint fall too far behind, so we can solve potential issues with updates early on instead of dealing with a lot of breaking changes at once with big updates, which potentially break a bunch of stuff at once.

Update golangci-lint to 1.52.2

---

exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.docs/introduction.md
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/cases_test.go

The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …

Sync largest-series-product docs with problem-specifications

---

exercises/practice/grep/.docs/instructions.md

Sync the grep docs from the problem specs. This reformats much of the instructions but the actual content/meaning doesn't change much.
This *does* result in much fewer example outputs.

Sync docs for the grep exercise

---

exercises/concept/gross-store/gross_store_test.go

Re-arrange the order of tests to match the order of the exercises within the UI.
I was a bit confused when I went through this exercise, I usually approach these in a TDD kind of style, where I do one step, run tests, and verify that the step is working as expected. However this exercise the tests seemed to be out of order compared to the steps.
Of note - I have no idea if this is the "right" fix, I'm only assuming that the order of the tests should also match the order of the steps for them to match within the exercism UI.

Update test order within gross_store_test.go to match order of steps

---

config.json
exercises/practice/strain/.meta/config.json
exercises/practice/strain/.meta/example.go
exercises/practice/strain/.meta/tests.toml
exercises/practice/strain/strain.go
exercises/practice/strain/strain_test.go

@andrerfcsantos suggested that "Strain" would be a good exercise for practicing generics. This PR does that.  The old version of the exercise was very clunky, with generics it makes much more sense.
I added a note on generics in the stub file so people know what they are up for. I also increased the difficultly to 4 to avoid people complaining that an easy exercise needs such an "advanced" concept.

Change strain to use generics

---

config.json

We're shortly going to be adding a generic representer, which normalises whitespace. As Go's actual representer will be better than the generic one, it makes sense to have it enabled, even if it's not perfect yet.

Turn on Representer

---

concepts/variadic-functions/about.md
concepts/variadic-functions/introduction.md
exercises/concept/card-tricks/.docs/introduction.md
exercises/practice/bob/.approaches/if-statements/content.md
exercises/practice/bob/.approaches/switch-statement/content.md
exercises/practice/clock/.approaches/clock-as-int/content.md
exercises/practice/grains/.approaches/bit-shifting/content.md
exercises/practice/isogram/.approaches/map/content.md
exercises/practice/pig-latin/.approaches/map-lookups-with-generics/content.md
exercises/practice/protein-translation/.approaches/map/content.md
exercises/practice/protein-translation/.approaches/switch/content.md
exercises/practice/rna-transcription/.approaches/map-object/content.md
exercises/practice/strain/.approaches/using-generics/content.md

In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705

Convert backtick (`) admonition fences to tildes (~)

---

exercises/practice/binary-search/.approaches/loop-with-switch/content.md
exercises/practice/binary-search/.approaches/loop-with-switch/snippet.txt

The switch statement in the loop-with-switch approach had two explicit cases and a default.
The three cases that exist are:
- equal
- less than
- greater than
If we want to have two explicit cases and a default, then it would feel more symmetrical to have the less-than and greater-than cases be defined explicitly with the equal case being the default.
However, it's hard to argue that any of the three are actually a default here.
Instead I've changed it to have three explicit cases.
Since there is an explicit return if we fall out of the `for` loop, we don't technically need the default.
Thoughts?

Tweak code example in binary-search approach

---

exercises/practice/anagram/.approaches/case-insensitive-sorting/content.md
exercises/practice/anagram/.approaches/case-insensitive-sorting/snippet.txt
exercises/practice/anagram/.approaches/config.json
exercises/practice/anagram/.approaches/frequency-counter/content.md
exercises/practice/anagram/.approaches/frequency-counter/snippet.txt
exercises/practice/anagram/.approaches/introduction.md

This pull request adds two approaches to the [Anagram](https://exercism.org/tracks/go/exercises/anagram) exercise.
- The first approach utilizes case-insensitive sorting.
- The second approach utilizes a hash map to build a frequency counter.

Anagram approaches

---

.github/workflows/exercise-tests.yml
.github/workflows/gomod-sync.yml
.github/workflows/stub-tests.yml

This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.

CI: pin GitHub Actions runners

---

exercises/practice/nucleotide-count/.approaches/introduction.md

Fixed typo in the word "nucleotide". The word was previously misspelled and thus some of the links didn't work, throwing 404 error. From forum thread: [link](https://forum.exercism.org/t/404-error-in-provided-performance-article-link-in-dig-deeper-section-of-nucleotide-count-exercise/7878)

fix typo and 404 links

---

exercises/practice/clock/.docs/instructions.append.md

The link went to a page which had been relocated. Explicitly linked to the correct section on the new page.

clock: update clock exercise instructions to point to correct receiver type documentation

---

exercises/concept/vehicle-purchase/vehicle_purchase_test.go

I've described the issue here.
https://forum.exercism.org/t/expanding-test-cases-for-vehicle-purchase-exercise-in-the-go-track/9066
(Agreed by @andrerfcsantos on [Exercism Community](https://forum.exercism.org/t/expanding-test-cases-for-vehicle-purchase-exercise-in-the-go-track/9066/7))

Add testcase for TestCalculateResellPrice

---

exercises/practice/space-age/.docs/instructions.append.md

This information no longer holds any value as the Planet type is already implemented in _space_age.go_ (line 2).
Approved by @andrerfcsantos on the [Community Forum](https://forum.exercism.org/t/go-tracks-space-age-has-obsolete-information-in-instructions/9394).

Remove obsolete information from Go track's Space Age exercise

---

exercises/practice/nucleotide-count/.approaches/introduction.md

"Performance deep dive" page: [here](https://exercism.org/tracks/go/exercises/nucleotide-count/articles/performance)

Nucleotide Count Excercise: Mistype fastest method according to "Performance deep dive" page

---

.golangci.yml

`gosec` discourages the use of `math/rand` in favor of `crypto/rand` as a more secure source for randomness. This level of concern about the randomness source security is not relevant in the track, so we are disabling this check.

Exclude insecure rand sources checks

---

exercises/practice/parallel-letter-frequency/.docs/instructions.append.md

Removes a duplicate link from the parallel-letter-frequency exercise's documentation
Would close Issue #2774.

[ISSUE-2774] Remove duplicate link from parallel-letter-frequency documentation

---

concepts/regular-expressions/introduction.md
exercises/concept/parsing-log-files/.docs/introduction.md

This PR fixes a couple typos in the Parsing Log Files instructions.md where "expressions" is plural, but the context shows that it should be singular. As discussed in the [forum](https://forum.exercism.org/t/fix-typos-in-parsing-log-files-instructions/11059), I've changed both files where this content is located.

Fix typos in regular-expressions concept instructions

---

exercises/practice/nucleotide-count/nucleotide_count_test.go

Almost all practice exercises have benchmarks, but for some reason this hadn't.

Add benchmark to Nucleotide Count

---

exercises/practice/bank-account/.meta/config.json

This removes the race test flag due to the timeouts this is apparently causing.
Forum discussion: https://forum.exercism.org/t/bank-account-potential-bug/8326/19
We should keep investigating if there are other ways we can make the use of this flag viable.

Remove race test flag from Bank Account due to timeouts

---

exercises/practice/resistor-color/.meta/gen.go
exercises/practice/resistor-color/cases_test.go

The input field is unused and causes a linter warning, which might be confusing for someone doing this exercise.

Remove unused 'input' field

---

exercises/concept/card-tricks/card_tricks_test.go

Adjusting so the test will now fail if the `index` value is greater than or equal to the size of the `slice`.

card-tricks: Check if index is >= len(slice)

---

exercises/practice/prime-factors/prime_factors_test.go

> I think this PR would be automatically closed, but wanted to leave it anyway, maybe'll figure out the forum later, but my tiny code reduction PR will be here already. 
In this PR I moved slice sorting and comparison to use standard libs `slices` package, removed helpers that we're necessary before generics were introduced. 
Value of this PR - removes code, enhances readability, showcases useful tools of stdlib :)

prime-factors: use slices package to sort and compare test cases

---

exercises/concept/bird-watcher/bird_watcher_test.go

The test cases provided in the exercise for the `BirdsInWeek` function only cover the first week and a week in the middle of the log. An edge case for a week in the end of the log is missing.

bird-watcher: Add test case for a week in the end of the log

---

exercises/concept/the-farm/.docs/instructions.md

Originally suggested by the PR: https://github.com/exercism/go/pull/2795
Recreating the PR as the original author of the PR deleted the branch.

the-farm: fix small typo

---

concepts/runes/about.md
concepts/runes/introduction.md

[Conversation](https://forum.exercism.org/t/potential-misleading-information-on-the-golang-runes-chapter/10082/11).

Single sentence per line for Runes

---

concepts/runes/about.md
concepts/runes/introduction.md
exercises/concept/logs-logs-logs/.docs/introduction.md

[Conversation](https://forum.exercism.org/t/potential-misleading-information-on-the-golang-runes-chapter/10082/11).

Describing a string as a sequence of runes is very confusing

---

exercises/concept/animal-magic/.docs/instructions.md

This PR is to clarify the range can also equal zero.
Implement a GenerateWandEnergy function. The wand energy should be a random floating point number **between 0.0 and 12.0.**
Implement a GenerateWandEnergy function. The wand energy should be a random floating point number **equal or greater than 0.0 and less than 12.0.**

Minor correction to the Anumal magic instructions markdown file

---

exercises/concept/blackjack/.docs/instructions.md

This commit will:
- make the term "figure" clear to people who have never played blackjack before

Make it clear what a figure is
