custom-set/cases_test.go
custom-set/custom_set_test.go
custom-set/example.go
custom-set/example_gen.go
custom-set/example_slice.go

addresses issue 116, slice based solutions.
slice based example added.  also now uses json test cases from x-common.
it's kind of a monster.

custom-set test program rewrite.

---

config.json
connect/connect_test.go
connect/example.go

Would appreciate some critique, I've been out of Go for a few years.
One thing I'm particularly unsure about is what's more idiomatic, the current
```go
coords := make([]coord, b.height)
for i := 0; i < b.height; i++ {
coords[i] = coord{x: 0, y: i}
}
```
or
```go
coords := make([]coord, 0, b.height)
for i := 0; i < b.height; i++ {
coords = append(coords, coord{x: 0, y: i})
}
```

Add connect exercise

---

SETUP.md

Fill in a simple SETUP.md

---

clock/clock_test.go

This confused me when making the exercise as it seemed the tests didn't expect a
a return value, which would force me to use a pointer receiver. Making the
comment more in line with what the test code actually expects should fix this.

Change clock.Add prototype in comment

---

config.json
poker/example.go
poker/poker_test.go

Add poker exercise

---

config.json
word-search/example.go
word-search/word_search_test.go

X-Common PR at exercism/x-common#65.

Add word-search exercise

---

config.json
react/example.go
react/interfaces.go
react/react_test.go

Add react exercise

---

scrabble-score/scrabble_score_test.go

Switch MultiBilliionaire for a vaid word

---

SETUP.md

This will get included in each of the READMEs that get generated.

Provide hint about running benchmarks

---

rna-transcription/cases_test.go
rna-transcription/example.go
rna-transcription/example_gen.go
rna-transcription/rna_transcription_test.go

error message arg order consistency, simplify benchmark.

rna-transcription update:  common test cases, TestVersion,

---

ledger/ledger.go

The readme for the ledger exercise claims that the current code
consistently passes the tests. Unfortunately, on my machine it
consistently does not pass the tests. Every time I try, I get this:
```
--- FAIL: TestFormatLedgerSuccess (0.00s)
ledger_test.go:267: FormatLedger for input named "credit and
debit" was expected to return...
Date_______|_Description_______________|_Change
01/01/2015_|_Buy_present_______________|______($10.00)
01/02/2015_|_Get_present_______________|_______$10.00_
...but returned...
Date_______|_Description_______________|_Change
01/02/2015_|_Get_present_______________|_______$10.00_
01/01/2015_|_Buy_present_______________|______($10.00)
```
Looking into the initial implementation, the implementation is creating
a goroutine for each line of the ledger, and the main …

ledger: Make initial implementation pass test

---

leap/leap_test.go

For https://github.com/exercism/xgo/issues/197

leap: update benchmark for fair weighting of years

---

ABOUT.md

Add ABOUT.md for Go as requested in http://exercism.io/languages/go.

Add ABOUT.md.

---

leap/leap.go

Changed `indentifies` -> `identifies` in the leap assignment.

Fixing Spelling Error

---

exercises/hello-world/hello_test.go

I had a moment to tackle this one, and it was a quick fix.

Show function argument to failure message in hello-world. Fixes #225

---

exercises/clock/clock.go
exercises/clock/clock_test.go
exercises/clock/example.go

Note, merge #239 first, this builds on top of that change.

Clock constructor

---

exercises/paasio/example.go

The "count bytes/operations" portions of the ReadCounter and
WriteCounter were completely analogous, and can be extracted.

paasio: Extract common counter code

---

docs/RESOURCES.md

Added a few links. I love what you are doing with the golang exercises, thank you!

adding resources

---

exercises/series/asktoomuch_test.go
exercises/series/example.go
exercises/series/series_test.go

More detail in individual commit messages.
Closes #329

series: rename Frist to UnsafeFirst, and supporting commits

---

exercises/accumulate/accumulate_test.go

I'm not sure if this is what you were looking for @kytrinyx @petertseng (re. #317) so do let me know if I'm wide of the mark.

improve accumulate problem's error messages

---

exercises/parallel-letter-frequency/parallel_letter_frequency_test.go

Added two benchmark tests to allow users to experiment with channel granularity and buffer depth.

Added two benchmark tests

---

exercises/allergies/allergies_test.go

Small change to sort string slices before comparing for equality.

sort slice before comparing

---

docs/LEARNING.md

Effective Go is by far the most comprehensive official best practices document
for Go. Worth to mention it in the list somewhere before the other resources.

Add Effective Go

---

exercises/word-search/example.go
exercises/word-search/word_search_test.go

Fixes: https://github.com/exercism/xgo/issues/311
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

word_search : Improved error handling behavior

---

exercises/grains/example.go
exercises/grains/grains_test.go

grains: Improve error-handling behavior (#289)

---

exercises/beer-song/beer_test.go
exercises/beer-song/example.go

1) Added versioning for beer-song test.
2) Added check for error type.
Please accept pull request.

Beer song improve err handling

---

exercises/circular-buffer/circular_buffer_test.go
exercises/circular-buffer/example.go

circular-buffer: Improve error-handling behavior #285

---

exercises/tournament/example.go
exercises/tournament/tournament_test.go

Closes #308.
I didn't add a check on line 125, seems like a slightly different case. Let me know if you do want one added there too or not!

tournament: Improve error-handling behavior

---

exercises/queen-attack/example.go
exercises/queen-attack/queen_attack_test.go

Closes #304.
Also added the test version constants and check for the versions.

queen-attack: Improve error-handling behavior

---

exercises/trinary/example.go
exercises/trinary/trinary_test.go

Closes #310.
Also added the test version constants and check for the versions.

trinary: Improve error-handling behavior

---

exercises/beer-song/beer_test.go

incorporated code review comment.

check for error type only when expecting error.

---

exercises/secret-handshake/example.go
exercises/secret-handshake/secret_handshake_test.go

secret-handshake: Use unsigned integers (close #373)

---

exercises/hexadecimal/example.go
exercises/hexadecimal/hexadecimal_test.go

Improved error handling in hexadecimal test. Please review.

Hexadecimal improve err handling

---

exercises/hamming/example.go
exercises/hamming/hamming.go
exercises/hamming/hamming_test.go

1) Added check for test version.
2) Improved error handling.
Please review.

Hamming improve err handling

---

exercises/kindergarten-garden/example.go
exercises/kindergarten-garden/kindergarten_garden_test.go

1) Added test versioning.
2) Improved error handling in TestGarden().
I don't think other tests need error type check.
Please review.

Kindergarten garden improve err handling

---

exercises/largest-series-product/example.go
exercises/largest-series-product/largest_series_product_test.go

Improved error handling for largest series product test. Please review.

Issue #294: largest-series-product: improv error handling.

---

exercises/ledger/example.go
exercises/ledger/ledger.go
exercises/ledger/ledger_test.go

ledger: Improve error-handling behavior (#295)

---

exercises/minesweeper/example.go
exercises/minesweeper/minesweeper_test.go

minesweeper: Improve error-handling behavior (#297)

---

exercises/octal/example.go
exercises/octal/octal_test.go

octal: Improve error-handling behavior (#299)

---

exercises/matrix/example.go
exercises/matrix/matrix_test.go

matrix: Improve error-handling behavior (#296)

---

exercises/saddle-points/example.go
exercises/saddle-points/saddle_points_test.go

saddle-points: Improve error-handling behavior (#307)

---

exercises/roman-numerals/example.go
exercises/roman-numerals/roman_numerals_test.go

roman-numerals: Improve error-handling behavior (#306)

---

exercises/tree-building/example.go
exercises/tree-building/tree_building.go
exercises/tree-building/tree_test.go

tree-building: Improve error-handling behavior (#309)

---

exercises/poker/example.go
exercises/poker/poker_test.go

poker: Improve error-handling behavior (#303)

---

exercises/robot-simulator/defs.go
exercises/robot-simulator/example.go
exercises/robot-simulator/robot_simulator_step2_test.go
exercises/robot-simulator/robot_simulator_step3_test.go
exercises/robot-simulator/robot_simulator_test.go

Spelling fixes
Changes to API
- func Robot() -> StartRobot()
- This function is not a robot, but rather it is starting a process that moves a robot around. This function could be called Start() or something else more descriptive
- DirAt -> Robot
- DirAt is pretty a good description as it is a Direction and a position, but isn't exactly what defines a robot in stage 2.
- Place -> Robot3
- Since this has a robot name, direction and position, Place doesn't seem like a very good description of the structure.

Robot Simulator - Update 1

---

exercises/phone-number/example.go
exercises/phone-number/phone_number_test.go

Fixes: https://github.com/exercism/xgo/issues/302
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Improved error handling behavior in phone-number

---

exercises/robot-simulator/defs.go
exercises/robot-simulator/example.go
exercises/robot-simulator/robot_simulator_step2_test.go
exercises/robot-simulator/robot_simulator_step3_test.go
exercises/robot-simulator/robot_simulator_test.go

Phase 2 involves changing the global variables X, Y and Facing (Dir) into a named struct. This is mostly to make the step 1 feel more uniform to step 2 and 3

Robot simulator - Update 2

---

exercises/variable-length-quantity/variable_length_quantity_test.go

Split TestEncodeDecodeVarint() into TestDecodeVarint() and TestEncodeVarint() making it easy to work on the exercise one function at a time.

VLQ: Tests update

---

exercises/nucleotide-count/example.go
exercises/nucleotide-count/nucleotide_count_test.go

In addition to improving error handling, I made some changes according to my taste such as map equality check, value printing, etc.
Unless well aligned, I can revert or update w.r.t your comments. Thanks!

nucleotide-count: improve error handling fixes #298

---

config.json
exercises/pangram/example.go
exercises/pangram/pangram_test.go

This PR adds exercise for determining if a sentence
is a pangram or not.
Fixes https://github.com/exercism/xgo/issues/395
Signed-off-by: Abhijeet Kasurde akasurde@redhat.com

Pangram: Add Pangram exercise

---

config.json
exercises/protein-translation/example.go
exercises/protein-translation/protein_translation_test.go

Exercise that translate RNA sequences into proteins
Fixes https://github.com/exercism/xgo/issues/400
Signed-off-by: Abhijeet Kasurde akasurde@redhat.com

Protein-translation: Add exercise for Protein Translation

---

config.json
exercises/twelve-days/example.go
exercises/twelve-days/twelve_days_test.go

Exercise that outputs the lyrics to 'The Twelve Days of Christmas'
Fixes https://github.com/exercism/xgo/issues/397
Signed-off-by: Abhijeet Kasurde akasurde@redhat.com

Twelve-days: Add exercise for Twelve Days

---

docs/LEARNING.md

docs: Extend learning resources with awesome go

---

exercises/hello-world/example.go
exercises/hello-world/hello_test.go
exercises/hello-world/hello_world.go

hello-world: Make stub golint friendly

---

exercises/TRACK_HINTS.md

What we assume to be simple, may not be for everyone

track_hints: remove the word simply

---

config.json

Control-flow(if-else statements) was recently changed to
Control-flow(conditionals)
https://github.com/exercism/x-common/pull/484

config.json: update hello-world topics

---

config.json

see: https://github.com/exercism/x-common/issues/494

config.json: add Equality to clock

---

exercises/pangram/pangram.go

Also adding stub solution for pangram as As referenced in #442

Stub for pangram problem

---

config.json

config.json: add topics to hamming exercise

---

config.json

config.json: add topics to gigasecond exercise

---

exercises/queen-attack/example.go
exercises/queen-attack/queen_attack_test.go

This PR adds some test case robustness.
Two commits are used to separate test case changes from "go fmt" changes.

Update queen attack edge cases

---

exercises/clock/clock_test.go

issue: #448
also of note: #125 & #121

clock: clarify comments

---

config.json

I don't think the dificulty needs to be changed for this. (#345)

config.json: add topics to etl

---

config.json

no change required to difficulty (#345)

config.json: add topics to scrabble_score

---

config.json

config.json: add topics to acronym

---

config.json

(#345) no change required to difficulty

config.json: add topics to raindrops

---

config.json

config.json: add topics to pangram exercise

---

config.json

bump difficulty also (see #345)

config.json: add topics to twelve-days

---

config.json

config.json: add topics to triangle, bump difficulty

---

config.json

increase difficulty rating also (#345)

config.json: add topics for parallel-letter-frequency

---

exercises/pangram/pangram_test.go

With [so many possible solutions](https://twitter.com/kytrinyx/status/826618650979352576) to this I though having a benchmark test would be useful.
I didn't think this warranted a bump in the testVersion but am happy to do so if others think otherwise.
I also checked the test consistency(#470) while I had the file open.

pangram: add benchmark test

---

exercises/word-count/word_count_test.go

word-count: move version testing into own function

---

exercises/bob/bob_test.go

bob: testversiontest isolated and moved to start of test functions

---

exercises/bracket-push/bracket_push_test.go

bracket-push: testversiontest isolated and moved to start of test functions

---

exercises/grade-school/example.go
exercises/grade-school/grade_school_test.go

Added test versioning: see #470.

grade-school: Ensure test versioning consistency with other exercises

---

exercises/gigasecond/gigasecond_test.go

Moved test version testing into its own function, first in the list of function to run, see #470.

gigasecond: Ensure test versioning consistency with other exercises

---

exercises/hamming/hamming_test.go

hamming: Ensure test versioning consistency with other exercises

---

exercises/hello-world/hello_test.go

Isolated test version testing into its own function before other test.
See #470

hello-world: Ensure test versioning consistency with other exercises

---

exercises/food-chain/food_chain_test.go

* Moved TestTestVersion to be the first test function
* Changed Errorf to Fatalf
See #470

food-chain: Ensure test versioning consistency with other exercises

---

exercises/etl/etl_test.go
exercises/etl/example.go

Added test versioning
See #470

etl: Ensure test versioning consistency with other exercises

---

exercises/diffie-hellman/diffie_hellman_test.go
exercises/diffie-hellman/example.go

Added test versioning
See #470

diffie-hellman: Ensure test versioning consistency with other exercises

---

exercises/difference-of-squares/difference_of_squares_test.go
exercises/difference-of-squares/example.go

Added test versioning
See #470

difference-of-squares: Ensure test versioning consistency with other exercises

---

exercises/diamond/diamond_test.go

* Moved TestTestVersion to be the first test function
* Changed Errorf to Fatalf
See #470

diamond: Ensure test versioning consistency with other exercises

---

exercises/hexadecimal/hexadecimal_test.go

* Moved TestTestVersion to top of the testing functions
See #470

hexadecimal: Ensure test versioning consistency with other exercises

---

exercises/hello-world/hello_world.go

hello-world: change nitpickers to reviewers

---

README.md

see https://github.com/exercism/x-common/pull/598
In #512 @kytrinyx highlighted some PR recommendations, which have now been added to the x-common CONTRIBUTING.md. This commit adds a specific link to these recommendations.

README.md: add link to Pull Request Guidelines

---

exercises/house/house_test.go

* Moved TestTestVersion to top of the testing functions
See #470

house: Ensure test versioning consistency with other exercises

---

exercises/isogram/isogram_test.go

* Moved test versioning constant to be the first declared variable
* Moved TestTestVersion to top of the testing functions
See #470

isogram: Ensure test versioning consistency with other exercises

---

exercises/leap/leap_test.go

* Isolated TestVersionTest functionality into its own function
See #470

leap: Ensure test versioning consistency with other exercises

---

exercises/matrix/matrix_test.go

* Moved TestTestFunction to top of test functions
See #470

matrix: Ensure test versioning consistency with other exercises

---

exercises/meetup/meetup_test.go

* Isolated TestTestVersion to its own function
See #470

meetup: Ensure test versioning consistency with other exercises

---

exercises/nth-prime/example.go
exercises/nth-prime/nth_prime_test.go

Added test versioning: see #470.

nth-prime: Ensure test versioning consistency with other exercises

---

README.md

this was previously missed by #516 & #519 due to being misspelled

README.md: change nitpickers to reviewers

---

exercises/minesweeper/minesweeper_test.go

* Moved TestTestFunction to top of test functions
See #470

minesweeper: Ensure test versioning consistency with other exercises

---

exercises/hello-world/hello_test.go
exercises/hello-world/hello_world.go

hello-world: add more detailed explanation about test consistency setup

---

exercises/series/example.go
exercises/series/series_test.go

Added test versioning: see #470.

series: Ensure test versioning consistency

---

exercises/TRACK_HINTS.md

the author believes this improves readability by breaking this
information out of the flow of the exercise specific information. The
link to the Go language page has also been updated.

TRACK_HINTS.md: add headers

---

exercises/strain/example.go
exercises/strain/strain_test.go

strain: add test versioning

---

exercises/ocr-numbers/example.go
exercises/ocr-numbers/ocr_numbers_test.go

ocr-numbers: add test versioning

---

exercises/paasio/paasio_test.go

* Isolated test version testing into own function
see #470

paasio: Ensure test versioning consistency with other exercises

---

exercises/strain/strain_test.go

strain: fix test order

---

exercises/strain/strain_test.go

strain: update tests

---

exercises/TRACK_HINTS.md

see https://github.com/exercism/discussions/issues/121

TRACK_HINTS.md: add note regarding benchmarks

---

exercises/paasio/paasio_test.go

paasio: Remove comment concerning test versioning constant

---

exercises/parallel-letter-frequency/example.go
exercises/parallel-letter-frequency/parallel_letter_frequency_test.go

parallel-letter-frequency: Add test versioning

---

exercises/pascals-triangle/example.go
exercises/pascals-triangle/pascals_triangle_test.go

pascals-triangle: Add test versioning

---

exercises/leap/leap.go
exercises/leap/leap_test.go

see https://github.com/exercism/xgo/issues/515#issuecomment-280173499

leap: remove unnecessary comments

---

exercises/connect/example.go

* fix lint warning
* no restate default

connect: Make more idiomatic

---

exercises/parallel-letter-frequency/parallel_letter_frequency_test.go

see https://github.com/exercism/xgo/pull/548#issuecomment-283290540

parallel-letter-frequency: re-order test file

---

exercises/perfect-numbers/perfect_numbers_test.go

* Relocated test version test function and constant to top of tests
See #470

perfect-numbers: ensure test versioning consistency with other exercises

---

exercises/kindergarten-garden/kindergarten_garden_test.go

kindergarten-garden: update test output formatting

---

exercises/phone-number/phone_number_test.go

* Isolated testversiontest to its own function
See #470

phone-number: Ensure test versioning consistency with other exercises

---

exercises/pig-latin/example.go
exercises/pig-latin/pig_latin_test.go

pig-latin: Add test versioning

---

config.json

add topics and change difficulty

config.json: update house

---

config.json

add topics and change difficulty

config.json: update secret-handshake

---

exercises/poker/poker_test.go

* Floated testtestversion function to start of tests
See #470

poker: Ensure test versioning consistency with other exercises

---

README.md
docs/TESTS.md
exercises/clock/example_clock_test.go
exercises/hello-world/hello_example_test.go

Adds example tests to hello-world and clock exercises, updating docs and readme accordingly.
see #420

Add example tests

---

exercises/pov/pov_test.go

* Isolated testversiontest into its own function
See #470

pov: Ensure test versioning consistency with other exercises

---

exercises/pythagorean-triplet/example.go
exercises/pythagorean-triplet/pythagorean_triplet_test.go

pythagorean-triplet: Add test versioning

---

config.json

accumulate: un-deprecate

---

exercises/queen-attack/queen_attack_test.go

queen-attack: Ensure test versioning consistency with other exercises

---

exercises/raindrops/raindrops_test.go

* Isolated test version testing to its own function
See #470

raindrops: Ensure test versioning consistency with other exercises

---

exercises/react/react_test.go

* Removed comments from test version function
* Moved test version function to start of test functions
See #470

react: Ensure test versioning consistency with other exercises

---

exercises/roman-numerals/roman_numerals_test.go

* Isolated test version testing to it's own function
See #470

roman-numerals: Ensure test versioning consistency with other exercises

---

exercises/saddle-points/saddle_points_test.go

* Moved TestTestVersion to start of test functions
See #470

saddle-points: Ensure test versioning consistency with other exercises

---

exercises/say/example.go
exercises/say/say_test.go

say: Add test versioning

---

exercises/scrabble-score/scrabble_score_test.go

* Isolated test version testing to its own function
See #470

scrabble-score: Ensure test versioning consistency with other exercises

---

exercises/sieve/example.go
exercises/sieve/sieve_test.go

sieve: Add test versioning

---

exercises/simple-cipher/example.go
exercises/simple-cipher/simple_cipher_test.go

simple-cipher: Add test versioning

---

exercises/sum-of-multiples/example.go
exercises/sum-of-multiples/sum_of_multiples_test.go

sum-of-multiples: Add test versioning

---

exercises/tournament/tournament_test.go

* Isolated test version test to its own function
See #470

tournament: Ensure test versioning consistency with other exercises

---

exercises/transpose/example.go
exercises/transpose/transpose_test.go

transpose: Add test versioning

---

exercises/tree-building/tree_test.go

* Moved TestTestVersion to top of tests
See #470

tree-building: Ensure test versioning consistency with other exercises

---

exercises/triangle/triangle_test.go

* Moved TestVersionTest to start of test functions
see #470

triangle: Ensure test versioning consistency with other exercises

---

exercises/trinary/trinary_test.go

trinary-test: Ensure test versioning consistency with other exercises

---

exercises/twelve-days/twelve_days_test.go

* Moved TestTestVersion to start of test functions
See #470

twelve-days: Ensure test versioning consistency with other exercises

---

exercises/hello-world/hello_world.go

hello-world: change recommendations for comments

---

config.json
exercises/bowling/bowling_test.go
exercises/bowling/cases_test.go
exercises/bowling/example.go
exercises/bowling/example_gen.go

Example solution modeled somewhat on http://butunclebob.com/ArticleS.UncleBob.TheBowlingGameKata

bowling: add exercise

---

.github/stale.yml

closes #611
the only change to the defaults I have made is to add `good first patch`
to the exemptions

add default .github/stale.yml

---

exercises/forth/.meta/gen.go
exercises/forth/cases_test.go
exercises/forth/forth_test.go

- Update generator:
Align template with latest canonical-data.json.
- Update test program:
Reference testGroups containing the generated test cases.
Annotate the FAIL output with test group name & test case description.
Add PASS output for successful cases.

forth: update generator

---

exercises/clock/.meta/gen.go
exercises/clock/cases_test.go

- Update generator:
Use .Header in generator template.
Align template with latest canonical-data.json.

clock: update generator

---

exercises/gigasecond/.meta/gen.go
exercises/gigasecond/cases_test.go
exercises/gigasecond/gigasecond_test.go

- Update generator:
Use .Header in generator template.
Align template with latest canonical-data.json.
Add test description to generated cases.
- Update test program:
Output test description.
Add PASS output for successful cases.

gigasecond: update generator

---

exercises/change/.meta/gen.go
exercises/change/cases_test.go

change: update generator

---

config.json

see #345
change difficulty
add topics

config.json: add info for pascals triangle

---

config.json

see #345
change difficulty
add topics

config.json: add info for series

---

config.json

see #345
change difficulty
add topics

config.json: add info for queen-attack

---

gen/gen.go

Update gen/gen.go package to give additional information
when an error occurs.
This change outputs an additional log output line to indicate
the context of the error, either during template Execute
or during the source Format step.
Also, when the error occurs during the source Format,
go ahead and output the generated source to the cases_test.go
file anyway with an extra line appended at the end which contains the
error message from the source Format.
Being able to examine the erroneous source text makes it easier
to understand the specific issue with the template/generator output.
Show either [SUCCESS] or [ERROR] output: /path/to/cases_test.go
in a log message after saving the generated source.
Four cases of generator run output (3 error types, and one success) are below:
>$ go run …

gen/gen.go: improve error support

---

exercises/bracket-push/.meta/gen.go
exercises/bracket-push/bracket_push_test.go
exercises/bracket-push/cases_test.go
exercises/bracket-push/example.go

For #605.
Generate test case array from the canonical-data.json.
Update example solution to pass all the tests.
Update test program.
Increment testVersion and targetTestVersion.

bracket-push: create test case generator

---

config.json

config.json: add topics to sum-of-multiples

---

exercises/atbash-cipher/.meta/gen.go
exercises/bob/.meta/gen.go
exercises/bowling/.meta/gen.go
exercises/bracket-push/.meta/gen.go
exercises/change/.meta/gen.go
exercises/clock/.meta/gen.go
exercises/connect/.meta/gen.go
exercises/custom-set/.meta/gen.go
exercises/forth/.meta/gen.go
exercises/gigasecond/.meta/gen.go
exercises/hamming/.meta/gen.go
exercises/largest-series-product/.meta/gen.go
exercises/leap/.meta/gen.go
exercises/luhn/.meta/gen.go
exercises/meetup/.meta/gen.go
exercises/phone-number/.meta/gen.go
exercises/raindrops/.meta/gen.go
exercises/rna-transcription/.meta/gen.go
exercises/roman-numerals/.meta/gen.go
exercises/scrabble-score/.meta/gen.go
exercises/transpose/.meta/gen.go
exercises/word-count/.meta/gen.go

gen.go: remove redundant build tags

---

exercises/clock/example_clock_test.go

The output of a single example test was quite overwhelming. Breaking the
example test into smaller tests makes any failure output easier to grok.
See https://github.com/exercism/xgo/pull/568#discussion_r117623204

clock: separate example tests

---

exercises/anagram/anagram_test.go
exercises/anagram/example.go

Response should return actual input.

anagram: Fix test case for case sensitivity

---

exercises/acronym/acronym.go

acronym: update testVersion in stub

Expected test version is now 3

---

config.json

config.json: add info for isogram

---

config.json

config.json: add info for error-handling

---

exercises/clock/.meta/gen.go
exercises/clock/cases_test.go
exercises/clock/clock_test.go

clock 1.0.1

---

config.json

config.json: add info for luhn

---

config.json

config.json: add info for crypto-square

---

config.json

config.json: add info for bank-account

---

exercises/bank-account/bank_account_test.go

Added a little more detail on the expected solution, concurrency, and not
allowing the balance to go below 0 on withdrawals.
Looking at the submitted solutions some users were not discovering Mutexes
on their own. Thought it may be helpful to add links to the godocs/tutorials
concering Mutexes if people have no idea where to start on the solution.

bank-account: more info about expected solution + mutex links

---

exercises/error-handling/common.go
exercises/error-handling/error_handling_test.go

Added more information describing the expected solution.
See #703

error-handling: Add lengthy description of expected solution

---

config.json

config.json: Add topics & difficulty for largest-series-product

---

config.json

config.json: add difficulty & topics for food-chain

---

config.json

config.json: Add topics & difficulty for circular-buffer

---

config.json

config.json: Add topics & difficulty for say

---

config.json

config.json: Add topics & difficulty for roman-numerals

---

config.json

config.json: Add topics & difficulty for rna-transcription

---

config.json

config.json: Add difficulty & topics for allergies

---

config.json

config.json: Add topics & difficulty for word-count

---

config.json

config.json: Add topics & difficulty for anagram

---

config.json

config.json: Add topics & difficulty for bracket-push

---

config.json

config.json: Add topics & difficulty for perfect-numbers

---

config.json

config.json: Add topics & difficulty to protein-translation

---

config.json

config.json: Add difficulty & topics for palindrome-products

---

config.json

config.json: Add difficulty & topics for sieve

---

config.json

config.json: add topics & difficulty for robot-name

---

config/maintainers.json

I've not contributed in a meaningful way to the Go track in a long time.
Thank you so much to all of you who have made this possible.

Make myself an alumnus

---

config.json

config.json: add topics & difficulty for forth

---

config.json

Added "Algorithms" due to the complexity of the scoring algorithm,
changed topics ordering to alphabetical.
See #345 & #731

config.json: modify topics & add difficulty for bowling

---

config.json

config.json: Add topics & difficulty for react

---

exercises/bowling/cases_test.go
exercises/forth/cases_test.go
exercises/forth/example.go
exercises/forth/forth_test.go
exercises/hamming/cases_test.go
exercises/phone-number/cases_test.go
exercises/phone-number/example.go
exercises/phone-number/phone_number_test.go
exercises/rna-transcription/cases_test.go
exercises/secret-handshake/cases_test.go

This PR commit series applies changes to 6 exercises after re-running
each test case generator to update cases_test.go.
It simply brings each one up-to-date with the x-common canonical-data.json files.

Update generated test cases - 6 exercises

---

config/maintainers.json

config/maintainers.json: add tleen information

---

config.json

config.json: Add difficulty & topics for phone-number

---

config.json

config.json: Add difficulty & topics for atbash-cipher

---

config.json

config.json: Add difficulty & topics for custom-set

---

config/maintainers.json

Add myself to the maintainers list

---

config.json

config.json: add topics & difficulty for diamond

---

config.json

Added "Mathematics" to the topics list since the solution involves
some mathematical thinking + operations. Set topics to be in
alphabetical order.
See #345 & #731

config.json: modify topics & add difficulty for change

---

exercises/hamming/hamming.go

I've looked at the history of the last change to this exercise. It
doesn't look like much was changed to expect a different implementation.
I've updated the version number to fix the exercise

Upping test version

---

config.json

config.json: Add topics & difficulty for ledger

---

config.json

config.json: Add topics & difficulty for variable-length-quantity

---

config.json

config.json: Add topics & difficulty for nth-prime

---

config.json

config.json: Add difficulty & topics for pig-latin

---

config.json

config.json: Add topics & difficulty for poker

---

config.json

config.json: Add topics & difficulty for ocr-numbers

---

config.json

config.json: Add topics & difficulty for beer-song

---

config.json

config.json: Add difficulty & topics for diffie-hellman

---

config.json

config.json: Add difficulty & topics for strain

---

config.json

config.json: Add difficulty & topics for prime-factors

---

config.json

config.json: Add topics & difficulty for grade-school

---

config.json

config.json: Add topics & difficulty for wordy

---

config.json

config.json: Add difficulty & topics for word-search

---

config.json

config.json: Add topics & difficulty for tournament

---

config.json

config.json: Add topics & difficulty for nucleotide-count

---

config.json

config.json: Add topics & difficulty for connect

---

config.json

config.json: Add difficulty & topics for all-your-base

---

config.json

config.json: Add topics & difficulty for minesweeper

---

config.json

config.json: Add topics & difficulty for robot-simulator

---

config.json

config.json: Add difficulty & topics for meetup

---

config.json

config.json: Add topics & difficulty for pov

---

config.json

config.json: Add topics & difficulty for paasio

---

config.json

config.json: Add topics & difficulty for kindergarten-garden

---

config.json

config.json: Add topics & difficulty for tree-building

---

config.json

config.json: Add topics & difficulty for saddle-points

---

config.json

config.json: Add topics & difficulty for simple-cipher

---

config.json

config.json: Add topics & difficulty for binary-search

---

config.json

config.json: Add topics & difficulty for binary-search-tree

---

config.json

It is pouring with rain outside and my kids are about to wake up, the
day is beginning, let's start it well. Closes #345 & closes #731.

config.json: Add topics & difficulty for matrix

---

config.json
docs/ABOUT.md

This adds a 'blurb' to the config file, and tweaks the `about` doc.
I really like the sentence in the about document that talks about how gophers like to describe the language. It feels very friendly and colloquial, and makes a great hook to pull people in to read more.
So I put that first, and then tweaked the second sentence simply for flow, so that it fit after the opening paragraph.
See https://github.com/exercism/discussions/issues/173
/cc @iHiD @ErikSchierboom

Update introductory copy

---

config/maintainers.json

The question came up a few days ago about whether alumni should be featured on the site, and I think the answer is yes. To give the design team an example to work with, and to encourage other alumni to submit their's, I'm adding mine here.

Add bio for kytrinyx entry in maintainer file

---

docs/ABOUT.md

Each sentence goes on its own line, with paragraphs separated by a blank line.
See https://github.com/exercism/meta/issues/84 for the full discussion. Bring popcorn.

Reformat the ABOUT doc per nextercism guidelines

---

config.json

[WIP] Restructure exercises

---

config.json
config/maintainers.json

We recently added a `fmt` command to configlet (https://github.com/exercism/configlet/commit/7cf90dbde6538fc38f0db2038dfd066a0cc34816) 
This is it's first sighting in the wild, I think.

Use configlet fmt to format configuration files

---

config/maintainers.json

It turns out, there was a perfectly good reason why my bio wasn't showing up :-)

Show kytrinyx's maintainer bio on the site

---

config.json

config.json: revert ordering

---

exercises/bob/bob_test.go
exercises/bob/example.go

bob: replace drivel with remark

---

config.json

* mark bob & gigasecond bonus exercises - See #828
* Identify first set of core exercises - See #829

[nextercism] update config.json

---

exercises/phone-number/.meta/description.md
exercises/phone-number/.meta/metadata.yml
exercises/phone-number/README.md

Document the expectation for implementing
a Format function, and the example output it should produce.
Closes #839.

phone-number: update README.md with Format

---

exercises/robot-name/.meta/hints.md
exercises/robot-name/bonus_example.go

This describes the bonus test and how to run it.
closes #832

robot-name: Add hints.md file

---

exercises/pangram/pangram_test.go

As mentioned on issue #872, this add two edge cases.

More test cases

---

config.json
exercises/run-length-encoding/README.md
exercises/run-length-encoding/example.go
exercises/run-length-encoding/run_length_encoding_test.go

This should cover all the previous change requests on my last pull request (#862)

[WIP] Adding run length encoding exercise

---

config.json

As per our conversation on #868.

pascals-triangle: update topics

---

config.json

queenattack: update topics

---

config.json

anagram: update topics

---

config.json

Add callbacks and interfaces as per #868.

react: update topics

---

config.json
exercises/collatz-conjecture/README.md
exercises/collatz-conjecture/collatz_conjecture_test.go
exercises/collatz-conjecture/example.go

Implement exercise collatz-conjecture.

Implement exercise collatz-conjecture

---

config/maintainers.json

I have a new job, and can't realistically commit to this project in the way I have been. So I have to hang up my spurs. 
I can't thank everyone involved enough.
:pray: @kytrinyx @tleen @leenipper @petertseng @ferhatelmas @nywilken

Update robphoenix in maintainers.json file

---

config.json
exercises/flatten-array/.meta/gen.go
exercises/flatten-array/README.md
exercises/flatten-array/cases_test.go
exercises/flatten-array/example.go
exercises/flatten-array/flatten_test.go

flatten-array: add exercise with test generator

---

exercises/poker/.meta/hints.md

Document what the input and output of `BestHand` should be.
Closes #853

poker: add a hints file

---

exercises/poker/README.md

The second half of #892, add the contents of the hints.md file to the
README for `poker`.

poker: Add hints.md to the README

---

exercises/sublist/.meta/gen.go

As suggested [here](https://github.com/exercism/go/pull/913#discussion_r147034310).

sublist: use relative import for generator

---

exercises/custom-set/cases_test.go

* set is not equal to larger set with same elements

custom-set: add new test

---

exercises/allergies/example.go

* remove unnecessary slice wrapping
* remove named return parameter since it's only one

allergies: make example solution more standard

---

exercises/accumulate/example.go

- deprecated, #823 will replace it but until that moment

accumulate: make it more standard

---

config.json
exercises/zebra-puzzle/.meta/hints.md
exercises/zebra-puzzle/README.md
exercises/zebra-puzzle/example.go
exercises/zebra-puzzle/zebra_puzzle_test.go

zebra-puzzle: implement exercise

---

exercises/wordy/.meta/gen.go
exercises/wordy/cases_test.go
exercises/wordy/wordy_test.go

wordy: create test case generator

---

exercises/nth-prime/.meta/gen.go
exercises/nth-prime/cases_test.go
exercises/nth-prime/nth_prime_test.go

Output FAIL and PASS in test output.
For #605.

nth-prime: add generator

---

exercises/binary-search/.meta/gen.go
exercises/binary-search/binary_search_test.go
exercises/binary-search/cases_test.go
exercises/binary-search/example.go

binary-search: add test generator

---

config.json
exercises/reverse-string/.meta/gen.go
exercises/reverse-string/README.md
exercises/reverse-string/cases_test.go
exercises/reverse-string/example.go
exercises/reverse-string/reverse_string_test.go

reverse-string: add exercise with generator and property testing

---

exercises/reverse-string/reverse_string_test.go

Given the numerous different ways a solution to this exercise could be implemented, I felt like a benchmark test would be appropriate here.
This fixes #973.

reverse-string: Implement Benchmark Test

---

config.json
exercises/dominoes/.meta/gen.go
exercises/dominoes/.meta/hints.md
exercises/dominoes/README.md
exercises/dominoes/cases_test.go
exercises/dominoes/dominoes_test.go
exercises/dominoes/example.go

dominoes: add exercise with generator

---

exercises/acronym/.meta/gen.go
exercises/acronym/cases_test.go

acronym: update generator to new input schema

---

exercises/bob/.meta/gen.go
exercises/bob/cases_test.go

bob: update generator for new input schema

---

config.json
exercises/alphametics/.meta/gen.go
exercises/alphametics/.meta/hints.md
exercises/alphametics/README.md
exercises/alphametics/alphametics_test.go
exercises/alphametics/cases_test.go
exercises/alphametics/example.go

alphametics: add exercise with generator

---

exercises/flatten-array/.meta/gen.go
exercises/flatten-array/cases_test.go

flatten-array: update generator to new input schema

---

config.json
exercises/simple-linked-list/README.md
exercises/simple-linked-list/example.go
exercises/simple-linked-list/linked_list_test.go

simple-linked-list: add exercise

---

exercises/sum-of-multiples/.meta/gen.go
exercises/sum-of-multiples/cases_test.go

sum-of-multiples: update generator to new input schema

---

exercises/bracket-push/.meta/gen.go
exercises/bracket-push/cases_test.go

bracket-push: changed problem specification input format 

---

exercises/bracket-push/.meta/gen.go
exercises/bracket-push/cases_test.go
exercises/dominoes/.meta/gen.go
exercises/dominoes/cases_test.go

problem specification updated to the new format ; I noticed in the upstream json some interesting comments on the exercise, so I put them in the generated test suite as Go comments

dominoes: input change

---

config.json
exercises/grep/.meta/gen.go
exercises/grep/.meta/hints.md
exercises/grep/README.md
exercises/grep/cases_test.go
exercises/grep/example.go
exercises/grep/grep_test.go

grep: add exercise with generator

---

exercises/acronym/cases_test.go
exercises/anagram/cases_test.go
exercises/hamming/.meta/gen.go
exercises/hamming/cases_test.go
exercises/largest-series-product/.meta/gen.go
exercises/largest-series-product/cases_test.go
exercises/leap/.meta/gen.go
exercises/leap/cases_test.go
exercises/nth-prime/.meta/gen.go
exercises/nth-prime/cases_test.go

fix to generators for the new problem specification input format

exercises: update several generators for problem specifications input change

---

exercises/phone-number/.meta/gen.go
exercises/phone-number/cases_test.go

phone-number: update generator to new input schema

---

exercises/pangram/.meta/gen.go
exercises/pangram/cases_test.go

updated generator for new json input format

pangram: fix generator for input change

---

config.json
exercises/rail-fence-cipher/.meta/gen.go
exercises/rail-fence-cipher/README.md
exercises/rail-fence-cipher/cases_test.go
exercises/rail-fence-cipher/example.go
exercises/rail-fence-cipher/rail_fence_cipher_test.go

rail-fence-cipher: add exercise with generator

---

exercises/two-bucket/.meta/hints.md
exercises/two-bucket/README.md
exercises/two-bucket/bonus_test.go
exercises/two-bucket/example.go
exercises/two-bucket/two_bucket_test.go

First commit corrects some minor mistakes in test program and example solution.
Second commit extends the exercise with a bonus part that returns an error
when a solution cannot be found for given inputs.

two-bucket: corrections plus bonus

---

config.json
exercises/rectangles/.meta/gen.go
exercises/rectangles/README.md
exercises/rectangles/cases_test.go
exercises/rectangles/example.go
exercises/rectangles/rectangles_test.go

rectangles: add exercise with generator

---

exercises/grains/.meta/gen.go
exercises/grains/cases_test.go

- input change
- unexport serialized type for "go vet" compliance

grains: update generator

---

config.json
exercises/proverb/.meta/gen.go
exercises/proverb/README.md
exercises/proverb/cases_test.go
exercises/proverb/example.go
exercises/proverb/proverb.go
exercises/proverb/proverb_test.go

Closed previous PR and opened a new one after comments

added proverb implementation in Go

---

config.json
exercises/scale-generator/.meta/gen.go
exercises/scale-generator/README.md
exercises/scale-generator/cases_test.go
exercises/scale-generator/example.go
exercises/scale-generator/scale_generator_test.go

I am not sure if I should also commit scale_generator.go stub file or if that is automatically generated.

implementation of scale generator in go

---

exercises/bowling/cases_test.go

Pick up two new test cases with generator
from updated canonical-data.json.

bowling: new test cases

---

exercises/dominoes/README.md
exercises/pig-latin/README.md
exercises/rectangles/README.md
exercises/two-bucket/README.md

Ran `configlet generate`` to update out-of-date READMEs.

exercises: regenerate READMEs

---

config.json
exercises/markdown/.meta/gen.go
exercises/markdown/README.md
exercises/markdown/cases_test.go
exercises/markdown/example.go
exercises/markdown/markdown.go
exercises/markdown/markdown_test.go

maybe still need some work; also not very clear how to write the new entry in config.json "unlocked_by" ?

proposal for markdown exercise

---

exercises/space-age/space_age_test.go

added a check for edge case NaN in the test

space-age: fix issue #1104

---

exercises/bracket-push/cases_test.go
exercises/isbn-verifier/cases_test.go
exercises/yacht/cases_test.go

Updates tests for bracket-push, isbn-verifier, and yacht
from the problem-specifications canonical-data.json.

Generator test case updates: bracket-push, isbn-verifier, and yacht

---

exercises/bracket-push/README.md

closes #1072
Description.md recently updated in exercism/problem-specifications
FYI, Configlet found about 6 other READMEs that need to be updated.

bracket-push: update README

---

exercises/parallel-letter-frequency/parallel_letter_frequency_test.go

This is a solution for issue #1114.

Modified the tests for parallel-letter-frequency

---

exercises/dominoes/.meta/gen.go
exercises/dominoes/cases_test.go

Update generator to output code which
agrees with "gofmt -s".

dominoes: clean up generated cases_test.go

---

exercises/nucleotide-count/nucleotide_count.go

nucleotide-count: remove Count method from nucleotide-count

---

exercises/armstrong-numbers/armstrong_test.go

armstrong-numbers: add benchmarks

---

exercises/protein-translation/protein_translation_detailed_test.go
exercises/protein-translation/protein_translation_test.go

Probably worth going through other challenges later and adding these across the board.

protein-translation: add in benchmark to test cases

---

exercises/book-store/cases_test.go
exercises/book-store/example.go

book-store: update example for new test case

---

exercises/isogram/cases_test.go
exercises/isogram/example.go

isogram: update example for new test case in problem specifications

---

exercises/difference-of-squares/difference_of_squares_test.go
exercises/difference-of-squares/example.go

Renamed Sums to sum in `sqOfSums`, `TestSquareOfSums`, `SquareOfSums` and `BenchmarkSquareOfSums`.

difference-of-squares: rename Sums to Sum

---

exercises/twelve-days/example.go
exercises/twelve-days/twelve_days_test.go

twelve-days: update to match specification

---

exercises/largest-series-product/.meta/gen.go
exercises/largest-series-product/cases_test.go

fixed generator to deal with latest upstream problem specifications

largest-series-product: update generator

---

exercises/say/.meta/gen.go
exercises/say/cases_test.go

say: fix generator to align for new upstream problem specifications

---

exercises/sum-of-multiples/cases_test.go
exercises/sum-of-multiples/example.go

update for latest change in test suite
fix issue #1204

sum-of-multiples: fix #1204

---

exercises/linked-list/.meta/description.md
exercises/linked-list/README.md

Added description.md with content of https://github.com/exklamationmark/exercism-go/blob/260d22bf57c9f1f6c5458818abcd4a8e777d2fd6/exercises/linked-list/README.md and generated README.md using configlet as described in #1203

Linked-List: Generated README.md

---

exercises/accumulate/.meta/description.md
exercises/accumulate/.meta/metadata.yml
exercises/accumulate/README.md

accumulate: Correct the readme

---

.travis.yml

.travis.yml: advance to 1.12.x

---

exercises/reverse-string/example.go
exercises/reverse-string/reverse_string_test.go

Renames `String()` to `Reverse()`.

reverse-string: rename func String to Reverse

---

exercises/luhn/cases_test.go

Updated to reflect latest canonical-data.json.

luhn: update non-ASCII test case

---

exercises/reverse-string/cases_test.go

Updated to reflect latest canonical-data.json.

reverse-string: add even-sized word test case

---

exercises/clock/clock_test.go

Fixes https://github.com/exercism/go/issues/1258

Tests for comparing clock after .Add() and .Subtract().

---

exercises/twelve-days/example.go
exercises/twelve-days/twelve_days_test.go

Eliminate trailing newline in twelve-days

Eliminate trailing newline in twelve-days

---

exercises/linked-list/.meta/description.md
exercises/linked-list/README.md
exercises/linked-list/linked_list_test.go

- fix description of `PushFront` and `PopFront`
- Add `NewList` to description
- Rename `Element` to `Node` in test cases API

linked-list: Update spec

---

.travis.yml
exercises/list-ops/listops_test.go

Bump golangci-lint to v1.21.0

---

.golangci.yml
.travis.yml
bin/test-without-stubs

Always lint before test and leverage golangci-lint to run

Simplify linting

---

config/maintainers.json

If you could please add me into the maintainers list I would be eternally grateful!

adding sebito91 as a maintainer

---

config/maintainers.json

For some reason bitfield was missed from this file.

Add bitfield as a maintainer

---

config/maintainers.json

Should not have marked this in the beginning, apologies!

small fix to remove alumnus flag from self

---

config/maintainers.json

In an email, tleen indicated no longer having time to be a maintainer.

maintainers: make tleen an alumnus

---

exercises/tournament/example.go

also, declare some function parameters more idiomatically.

tournament: use sort.Slice helper

---

exercises/list-ops/example.go

list_ops: get rid of convoluted Length implementation

---

config/maintainers.json

Add Michele Caci to go tracks' maintainers.json list

Update maintainers.json - add Michele Caci

---

bin/fetch-configlet

Handle changes in github api

---

config/maintainers.json

I would like to be added to maintainers list.

[Go] New maintainer 

---

exercises/parallel-letter-frequency/parallel_letter_frequency_test.go

The function `Frequency()` is defined in `parallel_letter_frequency.go` not `frequency.go`.

Fix name of file

---

.github/workflows/configlet.yml
.github/workflows/exercise-tests.yml
README.md
bin/fetch-golangci-lint
exercises/diamond/example.go

Make action functional #1364 
* fix badge links in readme
* fix a lint case from go1.15
* drop unsupported goos/arch pair
* small simplification where we don't need configuration

Fix action

---

.github/workflows/configlet.yml
config.json

Closes #1394. These are just a starting point - I welcome edits, suggestions, etc.

Added key features

---

exercises/practice/accumulate/accumulate_test.go

Hi.
This fixes the #1411 issue.
I also refactored the code in order to have less than 80 chars per line.

check for inplace replacement, fixes 1411

---

exercises/practice/linked-list/linked_list_test.go

prevent infinite loops as seen in #1255

---

exercises/practice/matrix/matrix_test.go

Matrix - better explanation, as per #1294

---

concepts/range-iteration/about.md
concepts/range-iteration/introduction.md
concepts/range-iteration/links.json
config.json
exercises/concept/chessboard/.docs/hints.md
exercises/concept/chessboard/.docs/instructions.md
exercises/concept/chessboard/.docs/introduction.md
exercises/concept/chessboard/.meta/config.json
exercises/concept/chessboard/.meta/design.md
exercises/concept/chessboard/.meta/exemplar.go
exercises/concept/chessboard/chessboard.go
exercises/concept/chessboard/chessboard_test.go

Hi everyone.
This is a PR for the range-iteration concept exercise.
I started from the Chessboard exercise in the Elixir track, but with some adjustments in order to show up all the Go nuances.
This is from #1381 
Any feedback will be very appreciated.
Thank you for considering my request.

Concept - range-iteration - Issue 1381

---

exercises/practice/largest-series-product/cases_test.go

Updated the error message for negative span.  Submitted for review

Error Message update for negative span

---

concepts/basics/.meta/config.json
config.json

_TL;DR; Add authors/contributors to a new `concepts/<slug>/.meta/config.json` to Concepts in the same way you have for Concept Exercises._
---
To properly attribute authorship/contributorship for an individual concept, each concept will have its own `.meta/config.json` file with `authors` and `contributors` keys like those for concept and practice exercises. We're also moving the concept's blurb from the track's `config.json` to the `.meta/config.json` file, also similar to concept and practice exercises.
See https://github.com/exercism/docs/pull/96/files for the update to the specification.
This PR adds a `.meta/config.json` file for all concepts found in the track's `config.json` file containing:
- A `blurb` key, which value is copied from the `config.json` file and subsequently removed …

🤖 Add .meta/config.json file for concepts

---

exercises/practice/hamming/.docs/instructions.append.md

The link to the leap readme led to a 404.

Fix broken leap link

---

config.json
exercises/concept/blackjack/.docs/introduction.md
exercises/concept/cars-assemble/.docs/introduction.md

Fixes https://github.com/exercism/go/issues/1482
CC @iHiD

Fix dependency cycle

---

exercises/concept/party-robot/go.mod
exercises/concept/party-robot/party_robot_test.go

None of the tests were executed or even compiled because `go.mod` did used the wrong module name.
I fixed the module name, tests, and test descriptions.

Fix party robot

---

exercises/concept/gross-store/.docs/instructions.md
exercises/concept/gross-store/gross_store.go

Add missing parameters to stub

---

exercises/concept/deep-thought/deep_thought.go
exercises/concept/deep-thought/deep_thought_test.go
exercises/concept/weather-forecast/weather_test.go
exercises/practice/binary/binary.go
exercises/practice/counter/counter.go
exercises/practice/hexadecimal/hexadecimal.go
exercises/practice/octal/octal.go
exercises/practice/trinary/trinary.go

#1485 - fix broken CI tests

---

exercises/concept/booking-up-for-beauty/.docs/instructions.md

booking-up-for-beauty: Fix doc having extra :00 in date

---

exercises/concept/need-for-speed/need_for_speed.go

Stop implementing NewCar in the stub

---

concepts/booleans/.meta/config.json
concepts/strings/.meta/config.json

Blurb proposal for concepts:
* booleans
* strings

Add concept blurb: booleans, strings

---

exercises/concept/party-robot/party_robot.go

Changes a "his" to a "their" (for a function that is not gender specific)

Neutralize a pronoun

---

concepts/comments/.meta/config.json
concepts/conditionals-if/.meta/config.json
concepts/conditionals-switch/.meta/config.json
concepts/constants/.meta/config.json
concepts/maps/.meta/config.json
concepts/methods/.meta/config.json
concepts/nil/.meta/config.json
concepts/numbers/.meta/config.json
concepts/range-iteration/.meta/config.json
concepts/slices/.meta/config.json
concepts/strings-package/.meta/config.json
concepts/structs/.meta/config.json
concepts/time/.meta/config.json
concepts/type-conversion/.meta/config.json
concepts/zero-values/.meta/config.json

Add missing concept blurbs

---

exercises/concept/need-for-speed/.meta/exemplar.go
exercises/concept/need-for-speed/need_for_speed.go

Hi,
Those comments are misleading as tests do not expect the battery to be drained.
(Sorry, I could not squash those two commits on github webui)
Fixes #1536

Need for speed misleading comments

---

concepts/numbers/about.md

numbers concept: fix empty about.md

---

concepts/numbers/introduction.md

numbers concept: cleanup introduction.md

---

exercises/concept/annalyns-infiltration/.docs/instructions.md

annalyns-infiltration: remove const and ; from instructions

---

concepts/basics/.meta/config.json
concepts/basics/about.md
concepts/basics/introduction.md
exercises/concept/lasagna/.docs/hints.md
exercises/concept/lasagna/.docs/instructions.md
exercises/concept/lasagna/.docs/introduction.md
exercises/concept/lasagna/.meta/config.json
exercises/concept/lasagna/.meta/exemplar.go
exercises/concept/lasagna/lasagna.go
exercises/concept/lasagna/lasagna_test.go

[Sept Sprint] lasagna: improve exercise to teach about constants

---

config.json

Add `the-farm` concept exercise slug

---

config.json

Add strings to prerequisites for elons-toys. (#1598)

---

config.json
exercises/concept/chessboard/.docs/introduction.md

I've had a crack at this. I also added methods as a prerequisite to this exercise as it uses them so
they should probably be covered first.

Try to explain non-struct types in the chessboard exercise (#1602).

---

exercises/concept/weather-forecast/.docs/hints.md
exercises/concept/weather-forecast/.docs/instructions.md
exercises/concept/weather-forecast/.meta/design.md
exercises/concept/weather-forecast/.meta/exemplar.go
exercises/concept/weather-forecast/weather.go

rename Log function as Forecast

---

exercises/concept/cars-assemble/cars_assemble.go

Remove implementation of `successRate`

---

concepts/conditionals-switch/.meta/config.json
concepts/conditionals-switch/about.md
concepts/conditionals-switch/introduction.md
concepts/conditionals-switch/links.json
exercises/concept/blackjack/.docs/introduction.md
exercises/concept/blackjack/.meta/config.json

Fixes #1556
Summary of the changes:
* I revamped the introduction of the concept and the introduction of the exercise as per the suggestions in #1556
* I also made the `about.md` of the concept to be more comprehensive
* More friendly link names for the concept

blackjack: streamline introduction

---

exercises/concept/weather-forecast/.docs/introduction.md
exercises/concept/weather-forecast/weather.go

Fixes remaining tasks #1582 #1578 in #1615
Closes #1582
Closes #1578 
Closes #1615

[Sept Sprint] Improve Weather Forecast

---

concepts/maps/introduction.md
config.json
exercises/concept/gross-store/.docs/introduction.md
exercises/concept/gross-store/.meta/config.json

Fixes https://github.com/exercism/go/issues/1621

[Sept Sprint] Gross Store improvements

---

concepts/methods/introduction.md

Corrected misspelled "reciever" typo.

Fix typo in introduction.md

---

config.json

Add `booleans` as a prereq for `card-tricks`

---

exercises/concept/card-tricks/.meta/exemplar.go
exercises/concept/card-tricks/card_tricks_test.go

Remove `nil` from `card-tricks`

---

exercises/concept/cars-assemble/.docs/introduction.md

Update the type conversion introduction

---

concepts/slices/introduction.md
exercises/concept/card-tricks/.docs/introduction.md

Fix some of the outstanding issues with the card-tricks concept exercise

---

concepts/functions/introduction.md
concepts/packages/.meta/config.json
concepts/packages/about.md
concepts/packages/introduction.md
concepts/packages/links.json
concepts/variables/introduction.md
config.json
exercises/concept/party-robot/.docs/introduction.md
exercises/concept/party-robot/.meta/config.json

Finish off new 'packages' concept (#1586)

---

exercises/concept/weather-forecast/.meta/exemplar.go
exercises/concept/weather-forecast/weather_test.go

weather forecast: fix failing tests

---

concepts/structs/about.md
concepts/structs/introduction.md
concepts/type-definitions/introduction.md
exercises/concept/need-for-speed/.docs/introduction.md

fixes https://github.com/exercism/go/issues/1589

docs: improve need for speed intro

---

exercises/concept/need-for-speed/.docs/instructions.md
exercises/concept/need-for-speed/need_for_speed.go

Fixes https://github.com/exercism/go/issues/1590

fix: remove struct and add TODO

---

exercises/concept/party-robot/.docs/introduction.md

Noticed while learning, cheers

docs: fix typo Sprinf > Sprintf

---

concepts/arithmetic-operators/.meta/config.json
concepts/arithmetic-operators/about.md
concepts/arithmetic-operators/introduction.md
concepts/arithmetic-operators/links.json
config.json
exercises/concept/cars-assemble/.docs/introduction.md

Add `arithmetic-operators` as a concept for `cars-assemble`

---

concepts/comparison/.meta/config.json
concepts/comparison/about.md
concepts/comparison/introduction.md
concepts/comparison/links.json
config.json

Add `comparison` concept

---

config.json

I think this is the last piece of work required on party-robot.
Fixes #1585. Fixes #1624

Make party-robot depend on numbers as well as strings.

---

concepts/string-formatting/about.md
concepts/string-formatting/introduction.md
exercises/concept/party-robot/.docs/introduction.md

Update the string formatting examples to fix bug and be clearer

---

exercises/practice/nth-prime/nth_prime.go

Noticed nth prime task does not have a function stub so added it

nth prime: added a function skeleton

---

concepts/booleans/introduction.md

Should just be about booleans, not about conditionals, switch statements etc).

Cleanup the introduction for the booleans concept

---

concepts/constants/introduction.md

Intro looks good to me and isn't actually a direct copy of the exercise.

Remove TODO notice.

---

concepts/conditionals-if/about.md
concepts/conditionals-if/introduction.md
exercises/concept/cars-assemble/.docs/introduction.md

Now covers the correct material for the related exercise.
No longer mentions switch which is covered elsewhere

Fix the introduction to the conditionals-if concept.

---

concepts/type-conversion/.meta/config.json
concepts/type-conversion/about.md
concepts/type-conversion/introduction.md
concepts/type-conversion/links.json

Fill in `type-conversion` concept docs

---

exercises/concept/the-farm/.docs/hints.md
exercises/concept/the-farm/.docs/instructions.md
exercises/concept/the-farm/.meta/exemplar.go
exercises/concept/the-farm/the_farm.go
exercises/concept/the-farm/the_farm_test.go

Also
- changed the tasks slightly to not only use a specific error, but also to return a specific error.
- change the test structure so that it uses the current style of table-driven tests
Fixes #1639

Add tasks to `the-farm` introduction

---

exercises/concept/cars-assemble/.docs/hints.md
exercises/concept/cars-assemble/.docs/instructions.md
exercises/concept/cars-assemble/.meta/exemplar.go
exercises/concept/cars-assemble/cars_assemble.go
exercises/concept/cars-assemble/cars_assemble_test.go

`cars-assemble`: add a task to implement `SuccessRate` and add hints

---

exercises/concept/party-robot/.docs/hints.md

* Add hints for each task
* Replace string concatenation with link to documentation

Improve party-robot hints.md (#1588)

---

exercises/concept/cars-assemble/.docs/introduction.md

`cars-assemble`: simplify the type conversion intro

---

exercises/concept/card-tricks/.docs/instructions.md

Add out-of-bounds to `card-tricks` instructions

---

exercises/concept/cars-assemble/.docs/hints.md

This hint is based on my own struggles with this exercise. I am not 100% sure if what I wrote is true, it's just my interpretation of the error that running the code produced.

Add a hint to `cars-assemble` task 2 about casting

---

exercises/concept/cars-assemble/.docs/hints.md

Fixes #1577 after commits ece3804 and 6f5fee57 mostle took care of this already.

Add some basic hints to cars-assemble.

---

exercises/concept/election-day/election_day_test.go

election-day: Fix TestNewElectionResult

---

exercises/concept/lasagna-master/.docs/hints.md

- Fixes a missing link to the range iteration concept
- Adds a link for the `len` built-in function

lasagna-master: fix missing link and add a new one on hints

---

config.json
exercises/concept/booking-up-for-beauty/.meta/design.md

Fixes https://github.com/exercism/go/issues/1560

booking-up-for-beauty: add booleans to prerequisites

---

concepts/interfaces/.meta/config.json
concepts/interfaces/about.md
concepts/interfaces/introduction.md
concepts/interfaces/links.json

Fill out the `interfaces` concept

---

concepts/packages/about.md
concepts/packages/introduction.md
concepts/structs/about.md
exercises/concept/party-robot/.docs/introduction.md

Update party robot introduction

---

concepts/conditionals-if/about.md
concepts/conditionals-if/introduction.md
exercises/concept/cars-assemble/.docs/hints.md
exercises/concept/cars-assemble/.docs/instructions.md
exercises/concept/cars-assemble/.docs/introduction.md
exercises/concept/cars-assemble/.meta/exemplar.go
exercises/concept/cars-assemble/cars_assemble.go
exercises/concept/cars-assemble/cars_assemble_test.go

cars-assemble: explain and use the `if expression; condition { }` syntax

---

exercises/practice/triangle/triangle_test.go

Fixes #1371
Also part of #1477
This makes this exercise to be in line with https://github.com/exercism/problem-specifications/issues/202

triangle: remove degenerate triangle test cases

---

exercises/practice/hamming/.docs/instructions.md

Fix instructions for this problem to suggest returning an error.

---

concepts/methods/about.md
concepts/methods/introduction.md

Docs(concept-methods): update code block to have correct formatting

---

concepts/basics/about.md
concepts/basics/introduction.md
exercises/concept/lasagna/.docs/hints.md
exercises/concept/lasagna/.docs/instructions.md
exercises/concept/lasagna/.docs/introduction.md
exercises/concept/lasagna/.meta/config.json
exercises/concept/lasagna/lasagna.go

Cleanups for Lasagna exercise and basics concept from feedback.

---

exercises/concept/annalyns-infiltration/.docs/instructions.md

Fix instruction "styling" for Annalyns Infiltration: Changing Actions (Fast attack, spy ..) to have italic font

annalyns-infiltration: use italic font for actions

---

exercises/practice/atbash-cipher/atbash_cipher_test.go

Wrapped `%s` with single quotes `'%s'`.
Fixes #1920

Added quotes to strings

---

config.json
exercises/practice/atbash-cipher/atbash_cipher_test.go

Deprecate exercise accumulate

---

exercises/practice/bank-account/.meta/example.go

This is causing CI jobs to fail because of [this check](https://go-critic.com/overview#exposedSyncMutex-ref).

Fix embedded mutex in `bank-account` example

---

.github/workflows/exercise-tests.yml

Fixes #1931
(solution was provided on Slack: https://exercism-team.slack.com/archives/CAQP7JL3T/p1635966104179200?thread_ts=1635963649.178800&cid=CAQP7JL3T)
The CI failure is unrelated and should be fixed in another PR. But the great thing about that failure is that is demonstrates that this fix is working:

Fix Windows CI issue

---

exercises/practice/phone-number/.docs/instructions.append.md
exercises/practice/phone-number/.docs/instructions.md

This is for #1925
This is to sync the instructions.md to back up to the problem specification.

phone-number: move go specific instruction to instructions.append.md (#1925)

---

exercises/concept/elons-toys/elons_toys_test.go
exercises/concept/need-for-speed/need_for_speed_test.go

There was no test case to see if the car could be driven if the battery was below the batteryDrain percentage. Added this test case to both the Elon's-Toys and Need for Speed exercises.

Elons toys & Need for Speed

---

exercises/practice/grains/.meta/example.go

Changing the variable name in example to make it consistent with the main exercise

Changing the variable name to number

---

docs/TESTS.md

For the absolute beginners which are not familiar with go test benchmarking, some basic explanations might help to quickly understand test results.

Explain --bench and --benchmem results by example

---

config.json
exercises/concept/vehicle-purchase/.docs/hints.md
exercises/concept/vehicle-purchase/.docs/instructions.md
exercises/concept/vehicle-purchase/.docs/introduction.md
exercises/concept/vehicle-purchase/.meta/config.json
exercises/concept/vehicle-purchase/.meta/design.md
exercises/concept/vehicle-purchase/.meta/exemplar.go
exercises/concept/vehicle-purchase/go.mod
exercises/concept/vehicle-purchase/vehicle_purchase.go
exercises/concept/vehicle-purchase/vehicle_purchase_test.go

Exercise covers `conditional-if` and `comparison` concepts and is based on the [Javascript](https://github.com/exercism/javascript/tree/main/exercises/concept/vehicle-purchase) version.

Add concept exercise "vehicle-purchase" (#1934)

---

exercises/practice/error-handling/.docs/instructions.md
exercises/practice/error-handling/error_handling_test.go

Fixes #1967
I think it is a nice thing to check.

error-handling: ensure `Close` is called only once

---

exercises/practice/protein-translation/.meta/example.go
exercises/practice/protein-translation/protein_translation_test.go

Non-zero values returned wit non-zero errors

---

exercises/practice/list-ops/.meta/example.go
exercises/practice/list-ops/list_ops.go
exercises/practice/list-ops/list_ops_test.go

Fixed #1968.
Along with this fix, I also fixed the Foldl argument. I apologize if this is superfluous.

List Ops: undefined func

---

concepts/errors/introduction.md
config.json
exercises/concept/the-farm/.docs/hints.md
exercises/concept/the-farm/.docs/instructions.md
exercises/concept/the-farm/.docs/introduction.md
exercises/concept/the-farm/.meta/config.json
exercises/concept/the-farm/.meta/exemplar.go
exercises/concept/the-farm/the_farm.go
exercises/concept/the-farm/the_farm_test.go
exercises/concept/the-farm/the_farm_types.go

the-farm: teach about interfaces

---

exercises/practice/pythagorean-triplet/.docs/instructions.append.md
exercises/practice/pythagorean-triplet/pythagorean_triplet.go

Pythagorean triplets exercise could use more detailed explanation

---

exercises/concept/the-farm/the_farm_test.go

Added a test for negative fodder with ScaleError, which should result in a "Negative Fodder" error.

Add test to the_farm.go

---

concepts/errors/about.md
concepts/errors/introduction.md

Concept Errors: Add missing references to documentation

---

config.json
exercises/concept/lasagna-master/.meta/design.md

Add missing prerequisite for-loops for Lasagna Master

---

concepts/errors/about.md
concepts/errors/introduction.md
exercises/concept/the-farm/.docs/introduction.md

Fixed a minor typo on the concept description

Fixed typo in Errors concept and the farm exercise

---

exercises/concept/sorting-room/sorting_room_test.go

Fixes #2016 
Please have a look and let me know if this is what was required

Integer Test case added

---

exercises/practice/tree-building/.meta/config.json

The exercise is about implementing a tree building algorithm from scratch, not refactoring an existing one.

tree-building: Fix exercise description

---

exercises/practice/atbash-cipher/.docs/instructions.md

Hi, reviewers/maintainers,
According to the discussion in #2020 , I created a PR in the problem spec repo.
The changes now have been accepted in exercism/problem-specifications#1899.
So I would like to sync it back to Go track with this new PR here. :)
Thanks,
jasonwucj

Atbash Cipher: Refine the exercise description

---

exercises/practice/minesweeper/minesweeper.go

This type is already defined in the file board.go

Do not define to Board type here.

---

exercises/concept/lasagna-master/.docs/introduction.md

Capitalized the language name

---

exercises/concept/the-farm/the_farm_test.go

added test case for negative amount with non-scale error #2011

---

concepts/maps/about.md
concepts/maps/introduction.md
exercises/concept/gross-store/.docs/introduction.md

go --> Go
language --> languages

 Capitalized the language name & typo fix 

---

exercises/practice/linked-list/.meta/example.go

Simplified Linked List Reverse
The new implementation only iterates over the list once and it's easier to understand (IMO)
Feel free to suggest improvements or reject the change.

Simplified Linked List Reverse

---

exercises/practice/run-length-encoding/run_length_encoding_test.go

Add benchmarks for `run-length-encoding` exercise

---

exercises/concept/elons-toys/.docs/instructions.md
exercises/concept/elons-toys/.docs/introduction.md
exercises/concept/elons-toys/elons_toys_test.go
exercises/concept/the-farm/the_farm_test.go

FIxes: #2047
1. Text changed to "...will receive a copy..."
2. fmt.Println is used to display a message
3. The order of the tests has been changed

elons-toys: minor tweaks

---

concepts/basics/about.md
exercises/concept/lasagna/.docs/introduction.md

Replace CamelCase with PascalCase

---

README.md
exercises/concept/lasagna-master/.docs/hints.md
exercises/concept/lasagna-master/.docs/instructions.md
exercises/concept/lasagna-master/.meta/config.json
exercises/concept/lasagna-master/.meta/exemplar.go
exercises/concept/lasagna-master/lasagna_master_test.go

Fix #2036
1. Update to README.md to install golint
2. Update AddSecretIngredient tests to update myList instead of returning 
3. Update exemplar, instructions and hints

Lasagna Master: Improve task 3 (AddSecretIngredient)

---

README.md

This was originally part of https://github.com/exercism/go/pull/2057

Add linter installation steps to README

---

exercises/concept/election-day/.docs/introduction.md

The function is named `incrementPeterAge` (not `addPeterAge`).

Reference correct function name

---

exercises/concept/need-for-speed/need_for_speed_test.go

need-for-speed: Add test cases for car with positive initial distance

---

config.json

Similar to #1565, the exemplar for interest-is-interesting uses a for loop, so should have for-loops as a prerequisite.

interest-is-interesting: added for-loop prerequisite 

---

exercises/concept/sorting-room/.docs/instructions.md
exercises/concept/sorting-room/sorting_room_test.go

Sorting room instructions, Section 2. 
- Fix 12 to 12.0 in sample output.

Sorting room instructions and testcase

---

exercises/concept/the-farm/.docs/instructions.md

Clarify instructions

---

exercises/concept/blackjack/.docs/hints.md
exercises/concept/blackjack/.docs/instructions.md
exercises/concept/blackjack/.meta/config.json
exercises/concept/blackjack/.meta/exemplar.go
exercises/concept/blackjack/blackjack.go
exercises/concept/blackjack/blackjack_test.go

Fixes #1731
* Replaced functions `LargeHand`, `SmallHand` and `IsBlackJack` with a single function `FirstTurn` that is to be implemented by the students
* Removed `IsBlackJack` tests
* Adapted hints and instructions accordingly
* Simplified sample solution

Overhaul of BlackJack concept exercise

---

exercises/practice/robot-name/robot_name_test.go

Simple commit to fix a single typo.

Updated robot_name_test.go to fix a one word typo.

---

exercises/practice/binary-search-tree/.meta/config.json
exercises/practice/binary-search-tree/.meta/example.go
exercises/practice/binary-search-tree/binary_search_tree.go
exercises/practice/binary-search-tree/binary_search_tree_test.go

Resolves #2113
Replaced two map functions with one SortedData() function
Updated tests and example accordingly
Renamed type SearchTreeData to BinarySearchTree and changed file names accordingly
Changed testing to a table-driven approach and added a SortedData() benchmark
Removed some generic comments from binary_search_tree.go

Binary-search-tree #2113

---

exercises/concept/expenses/.docs/instructions.md

`Total` should be `TotalByPeriod`
Closes #2149

Docs(`expenses`): correct `Total` function name in `instructions.md`

---

config.json

Fixes #2172
Changed difficulty to 4. Same as Robot Name and Perfect Numbers.

 Tree Building: Exercise should be labeled as medium not easy #2172 

---

exercises/concept/election-day/.meta/exemplar.go
exercises/concept/election-day/election_day.go

election-day: fix typo in NewVoteCounter comment

---

exercises/concept/expenses/.docs/instructions.md

Made clarification to the 3rd task in the instructions.

docs(expenses): clarify instructions

---

config.json
exercises/concept/expenses/.meta/design.md

At this point in the syllabus, error-creation has not yet been
introduced!

Add instructions to create errors

---

exercises/concept/blackjack/.docs/instructions.md

Clarify blackjack instructions

---

exercises/concept/lasagna/.docs/instructions.md

Changed Output to arrow in:
Gopher's Gorgeous Lasagna 
Fixes #2194
For easy tracking #2202

Changed "Output" to "=>" in: Gopher's Gorgeous Lasagna (Fixes #2194)

---

concepts/functions/about.md
concepts/functions/introduction.md
exercises/concept/lasagna-master/.docs/instructions.md
exercises/concept/lasagna-master/.docs/introduction.md

Fixes #2181
This PR addresses [#2181](https://github.com/exercism/go/issues/2181) and adds more educational information on `function` to help students complete the [Lasagna Master challege](https://exercism.org/tracks/go/exercises/lasagna-master).
- I added a clarification on `argument` vs `parameter` since previous authors have used both terms without explanation.
- I added modified pointer-related content to function concept's `about.md` but not `introduction.md`.

Issue #2181: Improve functions introduction

---

exercises/practice/tree-building/tree_building_test.go

failureTestCases: one root node and has parent

Tree Building: add test case

---

exercises/practice/linked-list/.docs/instructions.append.md
exercises/practice/linked-list/.meta/example.go
exercises/practice/linked-list/cases_test.go
exercises/practice/linked-list/linked_list.go

Hi,
this should fix #2219.
Adapted the task according to the comment https://github.com/exercism/go/issues/2219#issuecomment-1139120968 .

Improve Linked List

---

exercises/practice/linked-list/.meta/config.json

This change was missed in https://github.com/exercism/go/pull/2229

Add eldorandev to contributers of linked-list task

---

exercises/concept/meteorology/.docs/hints.md
exercises/concept/meteorology/.docs/instructions.md

The description of the return format doesn't match the tests or the examples below. I think windSpeed and windDirection should be in reverse order.

Switch windSpeed and windDirection

---

concepts/time/links.json

Add link as discussed here: https://github.com/exercism/go/issues/2243

time: add link from go-by-example: time formatting / parsing

---

exercises/practice/luhn/.meta/config.json
exercises/practice/luhn/.meta/tests.toml
exercises/practice/luhn/cases_test.go

Hey, I regenerated the test-cases because of the newly added test-cases in the problem specification 
Details:
* https://github.com/exercism/problem-specifications/pull/2056
* https://github.com/exercism/problem-specifications/issues/2054

regenerated test-cases

---

README.md

Hey, I have adjusted the documentation about generating test cases
Closes #2252

Update of the "generating test cases" section of the readme

---

exercises/concept/booking-up-for-beauty/.docs/instructions.md
exercises/concept/card-tricks/.docs/introduction.md
exercises/concept/election-day/.docs/instructions.md
exercises/concept/elons-toys/.docs/instructions.md
exercises/concept/interest-is-interesting/.docs/instructions.md
exercises/concept/party-robot/.docs/instructions.md
exercises/concept/savings-account/.docs/instructions.md
exercises/concept/vehicle-purchase/.docs/instructions.md
exercises/concept/welcome-to-tech-palace/.docs/instructions.md

Related to #2202 edited and added "=>" instead of "Output:" according to specifications in issue description
Signed-off-by: Manna Kong <mkong@redhat.com>

Fixed #2202 edited and added "=>" instead of "Output:

---

exercises/practice/bank-account/.docs/instructions.append.md

Currently, the bank-account task [doesn't have instructions](https://exercism.org/tracks/go/exercises/bank-account) for functions' implementation, so a student should browse the test code to learn the requirements. This PR adds the instructions

bank-account: added instructions for function implementation

---

exercises/practice/parallel-letter-frequency/.docs/instructions.append.md

parallel-letter-frequency: remove redandunt link, add more

---

exercises/practice/bank-account/.docs/instructions.append.md

bank-account: fix links formatting

---

exercises/practice/kindergarten-garden/kindergarten_garden_test.go
exercises/practice/matrix/matrix_test.go

Hey @junedev, here the PR, I hope the message indicates that the problem is not the student code. Basically this error only occurs in two cases:
* student changes the input of the test
* contributor changes the input and wants to make a PR-->should fail, as configlet should fail as the example-solution does not pass, as this case fails
Closes #1911

changed t.Skip to t.Fatalf if input of test is invalid

---

exercises/concept/chessboard/chessboard_test.go

added new test-cases to exercise chessboard

---

exercises/concept/election-day/election_day_test.go

Fixes #2281 
This is my contribution to address the issue.
Added two additional test cases to test the given solution more thoroughly.

Add extra test cases for IncrementVoteCount in election_day

---

exercises/concept/weather-forecast/.docs/instructions.md

This change is purely cosmetic, and there is no open issue requesting it.
It's not strictly necessary.
The weather forecast story had a few turns of phrase that felt a little
bit clunky.
I've tweaked the wording to flow a little bit better.
I also took the opportunity to replace a few exclamation marks with
periods to tone down the enthusiasm a wee bit.

Tweak weather forecast story for flow

---

exercises/concept/meteorology/.docs/instructions.md
exercises/concept/meteorology/.meta/config.json

meteorology: improved formatting of instructions

---

exercises/practice/error-handling/.docs/instructions.md

I would like propose to quote class names in instruction for readability.

Quote class names

---

README.md

added instructions how to add a new exercise generator

---

exercises/practice/diamond/.meta/example.go
exercises/practice/diamond/diamond_test.go

diamond: removed expected \n from last line

---

exercises/practice/allergies/.meta/config.json
exercises/practice/allergies/.meta/gen.go
exercises/practice/allergies/.meta/tests.toml
exercises/practice/allergies/allergies_test.go
exercises/practice/allergies/cases_test.go

Hey, here I also adjusted the tests a bit as the inputs seem to have changed
One of #2302

allergies: updated exercise generator to new test generator

---

exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/armstrong-numbers/.meta/gen.go
exercises/practice/armstrong-numbers/armstrong_numbers_test.go
exercises/practice/armstrong-numbers/cases_test.go

armstrong-numbers: updated exercise generator to new test generator

---

exercises/practice/binary-search/.meta/config.json
exercises/practice/binary-search/.meta/gen.go
exercises/practice/binary-search/binary_search_test.go
exercises/practice/binary-search/cases_test.go

binary-search: updated exercise generator to new test generator

---

exercises/practice/clock/.meta/config.json
exercises/practice/clock/.meta/gen.go
exercises/practice/clock/cases_test.go
exercises/practice/clock/clock_test.go

clock: updated exercise generator to new test generator

---

exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/collatz-conjecture/.meta/example.go
exercises/practice/collatz-conjecture/.meta/gen.go
exercises/practice/collatz-conjecture/.meta/tests.toml
exercises/practice/collatz-conjecture/cases_test.go
exercises/practice/collatz-conjecture/collatz_conjecture_test.go

collatz-conjecture: updated exercise generator to new test generator

---

exercises/practice/connect/.meta/config.json
exercises/practice/connect/.meta/gen.go
exercises/practice/connect/cases_test.go
exercises/practice/connect/connect_test.go

connect: updated exercise generator to new test generator

---

exercises/practice/custom-set/.meta/config.json
exercises/practice/custom-set/.meta/gen.go
exercises/practice/custom-set/cases_test.go
exercises/practice/custom-set/custom_set_test.go
gen/gen.go

custom-set: updated exercise generator to new test generator

---

exercises/practice/darts/.docs/instructions.md
exercises/practice/darts/.meta/config.json
exercises/practice/darts/.meta/gen.go
exercises/practice/darts/cases_test.go
exercises/practice/darts/darts_test.go

darts: updated exercise generator to new test generator

---

exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.meta/config.json
exercises/practice/largest-series-product/.meta/gen.go
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/cases_test.go
exercises/practice/largest-series-product/largest_series_product_test.go

largest-series-product: updated exercise generator to new test generator

---

exercises/practice/dominoes/.meta/config.json
exercises/practice/dominoes/.meta/gen.go
exercises/practice/dominoes/cases_test.go
exercises/practice/dominoes/dominoes_test.go
gen/gen.go

dominoes: updated exercise generator to new test generator

---

exercises/practice/flatten-array/.meta/config.json
exercises/practice/flatten-array/.meta/gen.go
exercises/practice/flatten-array/.meta/tests.toml
exercises/practice/flatten-array/cases_test.go
exercises/practice/flatten-array/flatten_array_test.go

flatten-array: updated exercise generator to new test generator

---

exercises/practice/gigasecond/.meta/config.json
exercises/practice/gigasecond/.meta/gen.go
exercises/practice/gigasecond/cases_test.go
exercises/practice/gigasecond/gigasecond_test.go

gigasecond: updated exercise generator to new test generator

---

exercises/practice/isbn-verifier/.docs/instructions.md
exercises/practice/isbn-verifier/.meta/config.json
exercises/practice/isbn-verifier/.meta/gen.go
exercises/practice/isbn-verifier/.meta/tests.toml
exercises/practice/isbn-verifier/cases_test.go
exercises/practice/isbn-verifier/isbn_verifier_test.go

isbn-verifier: updated exercise generator to new test generator

---

exercises/concept/census/.docs/instructions.md
exercises/concept/meteorology/.docs/instructions.md

Made a few concept code example to follow the standard format

---

exercises/practice/isogram/.meta/config.json
exercises/practice/isogram/.meta/gen.go
exercises/practice/isogram/.meta/tests.toml
exercises/practice/isogram/cases_test.go
exercises/practice/isogram/isogram_test.go

isogram: updated exercise generator to new test generator

---

exercises/practice/leap/.meta/config.json
exercises/practice/leap/.meta/gen.go
exercises/practice/leap/cases_test.go
exercises/practice/leap/leap_test.go

leap: updated exercise generator to new test generator

---

exercises/practice/matching-brackets/.meta/config.json
exercises/practice/matching-brackets/.meta/gen.go
exercises/practice/matching-brackets/.meta/tests.toml
exercises/practice/matching-brackets/cases_test.go
exercises/practice/matching-brackets/matching_brackets_test.go

matching-brackets: updated exercise generator to new test generator

---

exercises/practice/meetup/.docs/instructions.md
exercises/practice/meetup/.meta/config.json
exercises/practice/meetup/.meta/gen.go
exercises/practice/meetup/cases_test.go
exercises/practice/meetup/meetup.go
exercises/practice/meetup/meetup_test.go

meetup: updated exercise generator to new test generator

---

exercises/practice/nth-prime/.meta/config.json
exercises/practice/nth-prime/.meta/gen.go
exercises/practice/nth-prime/cases_test.go
exercises/practice/nth-prime/nth_prime_test.go

nth-prime: updated exercise generator to new test generator

---

exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/nucleotide-count/.meta/gen.go
exercises/practice/nucleotide-count/cases_test.go
exercises/practice/nucleotide-count/nucleotide_count_test.go

nucldeotide-count: updated exercise generator to new test generator

---

exercises/practice/pangram/.docs/instructions.md
exercises/practice/pangram/.meta/config.json
exercises/practice/pangram/.meta/gen.go
exercises/practice/pangram/.meta/tests.toml
exercises/practice/pangram/cases_test.go
exercises/practice/pangram/pangram_test.go

pangram: updated exercise generator to new test generator

---

exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/perfect-numbers/.meta/example.go
exercises/practice/perfect-numbers/.meta/gen.go
exercises/practice/perfect-numbers/cases_test.go
exercises/practice/perfect-numbers/perfect_numbers_test.go

perfect-numbers: updated exercise generator to new test generator

---

exercises/practice/pig-latin/.meta/config.json
exercises/practice/pig-latin/.meta/gen.go
exercises/practice/pig-latin/cases_test.go
exercises/practice/pig-latin/pig_latin_test.go

pig-latin: updated exercise generator to new test generator

---

exercises/practice/poker/.meta/config.json
exercises/practice/poker/.meta/gen.go
exercises/practice/poker/.meta/tests.toml
exercises/practice/poker/cases_test.go
exercises/practice/poker/poker_test.go

poker: updated exercise generator to new test generator

---

exercises/practice/prime-factors/.meta/config.json
exercises/practice/prime-factors/.meta/gen.go
exercises/practice/prime-factors/.meta/tests.toml
exercises/practice/prime-factors/cases_test.go
exercises/practice/prime-factors/prime_factors_test.go

prime-factors: updated exercise generator to new test generator

---

exercises/practice/proverb/.meta/config.json
exercises/practice/proverb/.meta/gen.go
exercises/practice/proverb/cases_test.go
exercises/practice/proverb/proverb_test.go

proverb: updated exercise generator to new test generator

---

exercises/practice/rail-fence-cipher/.meta/config.json
exercises/practice/rail-fence-cipher/.meta/gen.go
exercises/practice/rail-fence-cipher/cases_test.go
exercises/practice/rail-fence-cipher/rail_fence_cipher_test.go

rail-fence-cipher: updated exercise generator to new test generator

---

exercises/practice/hamming/.meta/config.json
exercises/practice/hamming/.meta/gen.go
exercises/practice/hamming/.meta/tests.toml
exercises/practice/hamming/cases_test.go
exercises/practice/hamming/hamming_test.go

hamming: updated exercise generator to new test generator

---

exercises/practice/raindrops/.meta/config.json
exercises/practice/raindrops/.meta/gen.go
exercises/practice/raindrops/cases_test.go
exercises/practice/raindrops/raindrops_test.go

raindrops: updated exercise generator to new test generator

---

exercises/practice/reverse-string/.meta/config.json
exercises/practice/reverse-string/.meta/gen.go
exercises/practice/reverse-string/cases_test.go
exercises/practice/reverse-string/reverse_string_test.go

reverse-string: updated exercise generator to new test generator

---

exercises/practice/rna-transcription/.meta/config.json
exercises/practice/rna-transcription/.meta/gen.go
exercises/practice/rna-transcription/cases_test.go
exercises/practice/rna-transcription/rna_transcription_test.go

rna-transcription: updated exercise generator to new test generator

---

exercises/practice/roman-numerals/.docs/instructions.md
exercises/practice/roman-numerals/.meta/config.json
exercises/practice/roman-numerals/.meta/gen.go
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/cases_test.go
exercises/practice/roman-numerals/roman_numerals_test.go

roman-numerals: updated exercise generator to new test generator

---

exercises/concept/need-for-speed/.docs/hints.md
exercises/concept/need-for-speed/.docs/instructions.md
exercises/concept/need-for-speed/.meta/exemplar.go
exercises/concept/need-for-speed/need_for_speed.go

Some small fixes. These are my first times using the pull-request-based way of working, please let me know how I can do it better!

Small fixes to need-for-speed exercise

---

exercises/practice/run-length-encoding/.meta/config.json
exercises/practice/run-length-encoding/.meta/gen.go
exercises/practice/run-length-encoding/cases_test.go
exercises/practice/run-length-encoding/run_length_encoding_test.go

run-length-encoding: updated exercise generator to new test generator

---

exercises/practice/say/.meta/config.json
exercises/practice/say/.meta/gen.go
exercises/practice/say/cases_test.go
exercises/practice/say/say_test.go

say: updated exercise generator to new test generator

---

exercises/practice/space-age/.docs/instructions.append.md
exercises/practice/space-age/.meta/config.json
exercises/practice/space-age/.meta/example.go
exercises/practice/space-age/.meta/gen.go
exercises/practice/space-age/.meta/tests.toml
exercises/practice/space-age/cases_test.go
exercises/practice/space-age/space_age_test.go

space-age: updated exercise generator to new test generator

---

exercises/practice/sum-of-multiples/.meta/config.json
exercises/practice/sum-of-multiples/.meta/gen.go
exercises/practice/sum-of-multiples/cases_test.go
exercises/practice/sum-of-multiples/sum_of_multiples_test.go

sum-of-multiples: updated exercise generator to new test generator

---

exercises/practice/yacht/.docs/instructions.md
exercises/practice/yacht/.meta/config.json
exercises/practice/yacht/.meta/gen.go
exercises/practice/yacht/yacht_test.go

yacht: updated exercise generator to new test generator

---

concepts/range-iteration/about.md
concepts/range-iteration/introduction.md
exercises/concept/chessboard/.docs/introduction.md

Sequence seemed incorrect. Made appropriate changes.

Changes to iterating map output.

---

config.json

Hey, I would suggest to change the difficulty of `proverb` to 3, as the exercise seems to be `easy` instead of `medium` for me

proverb: adjusted difficulty to 3

---

exercises/practice/beer-song/.meta/config.json
exercises/practice/beer-song/beer_song_test.go

Hey, I adjusted the tests of `beer-song` to be using subtests (`t.Run`), adjusted the output a bit, to be easier understandable and I also removed the compile time type check of the error
Related #2098

beer-song: adjusted tests

---

exercises/practice/variable-length-quantity/variable_length_quantity.go

Hey, I fixed the text to match the func name

variable-length-quantity: fixed text

---

exercises/concept/card-tricks/.docs/instructions.md

Fix to hopefully render the link properly in the admonition.
Closes #2401

[Card Tricks] Fix link in instructions.md

---

exercises/practice/word-count/.docs/instructions.md

Hey, I used ./bin/run-generators to update all exercises with generators

updated all exercises with generators

---

exercises/concept/need-for-speed/.docs/hints.md

Need For Speed | Added Formula for Calculating Race Distance and Battery Drain Rate

---

exercises/concept/animal-magic/animal_magic_test.go
exercises/practice/bowling/bowling_test.go

added usage of subtests for exercise bowling

---

exercises/practice/armstrong-numbers/armstrong_numbers_test.go
exercises/practice/gigasecond/gigasecond_test.go

Hey, I think I have found the problem for #2450
Closes #2450

fixed failure of tests

---

exercises/practice/two-bucket/bonus_test.go
exercises/practice/two-bucket/two_bucket_test.go

Hey, when updating everything for the generators I seem to have destroyed the bonus test case for two-bucket. Should be fixed now
One of #2098

fixed bonus tests

---

exercises/concept/lasagna-master/.docs/instructions.md

Tracks / Go / Exercises / Lasagna Master / Updated instructions.md

---

exercises/practice/pythagorean-triplet/.meta/config.json
exercises/practice/pythagorean-triplet/pythagorean_triplet_test.go

added usage of subtests for pythagorean-triplet

---

exercises/practice/spiral-matrix/.meta/config.json
exercises/practice/spiral-matrix/spiral_matrix_test.go

added usage of subtests for spiral-matrix

---

exercises/practice/strain/.meta/config.json
exercises/practice/strain/strain_test.go

usage of subtests for strain

---

exercises/practice/tournament/.meta/config.json
exercises/practice/tournament/tournament_test.go

added usage of subtests for tournament

---

exercises/practice/twelve-days/.meta/config.json
exercises/practice/twelve-days/twelve_days_test.go

added usage of subtests for twelve_days

---

exercises/practice/anagram/.meta/gen.go
exercises/practice/anagram/anagram_test.go
exercises/practice/anagram/cases_test.go

Closes #1451.
A test case was added to ensure that the solution works for non-ascii anagrams.

Add test case for non-ascii anagrams

---

exercises/concept/elons-toys/.docs/introduction.md

Updated code block with main function so that code executes locally

update code block for direct execution

---

exercises/practice/triangle/.meta/config.json
exercises/practice/triangle/triangle_test.go

added usage of subtests for triangle

---

exercises/practice/ocr-numbers/.meta/config.json
exercises/practice/ocr-numbers/ocr_numbers_test.go

added usage of subtests and added descriptions for ocr-numbers

---

exercises/practice/palindrome-products/.meta/config.json
exercises/practice/palindrome-products/palindrome_products_test.go

added usage of subtests for palindrome-products

---

exercises/practice/pascals-triangle/.meta/config.json
exercises/practice/pascals-triangle/pascals_triangle_test.go

added usage of subtests for exercise pascals-triangle

---

exercises/practice/series/.meta/config.json
exercises/practice/series/asktoomuch_test.go
exercises/practice/series/first_test.go
exercises/practice/series/series_test.go

added usage of subtests for series

---

exercises/practice/rotational-cipher/.meta/config.json
exercises/practice/rotational-cipher/rotational_cipher_test.go

added usage of subtests for rotational cipher

---

exercises/practice/triangle/triangle_test.go

Triangle: fix KindsNotEqual test case

---

exercises/practice/say/.meta/tests.toml
exercises/practice/say/cases_test.go

For the say exercise  - add new test cases which were recently introduced in the problem-specifications repo.
Fixes #2508

Say: implement new tests

---

exercises/concept/meteorology/.docs/instructions.md

Fix a typo in the last task's title ("MetData")

---

README.md

Remove references to gitter and refer forum instead.

Remove gitter references and use forum

---

exercises/practice/matrix/.meta/example.go
exercises/practice/matrix/matrix.go
exercises/practice/matrix/matrix_test.go

A minor change to the test file allows all methods to use a value receiver. This should allow for simpler solutions since students don't need to deal with pointers within their functions.
It is probably possible to change BenchmarkNew to use either a pointer or value (as all other tests are capable of this) but I didn't want to screw anything up so I went with the simplest change.

Update function signatures provided in matrix exercise

---

exercises/practice/error-handling/.docs/instructions.md

change argument name to 'opener'

Bring instruction into line with stub file

---

exercises/concept/the-farm/the_farm_test.go

the-farm: check "negative fodder" error precedence

---

concepts/methods/about.md
concepts/methods/introduction.md
exercises/concept/elons-toys/.docs/introduction.md

Sorry for creating a new pull request. Still kind of new to them, I hope I did this one correctly. I checked all the files mentioned, and updated all of them.

Remove whitespace in front of exclamation point

---

README.md

This fixes #2528
The link of the config file wad dead.

Update the Link of config.json in README

---

concepts/time/about.md
concepts/time/introduction.md
exercises/concept/booking-up-for-beauty/.docs/introduction.md

I have added some example about how parsing and formatting time works. Also added details for create custom layout for time.
Fixes #2491

Update concept about how parsing/formatting time works

---

exercises/practice/leap/.approaches/boolean-chain/content.md
exercises/practice/leap/.approaches/boolean-chain/snippet.txt
exercises/practice/leap/.approaches/config.json
exercises/practice/leap/.approaches/introduction.md
exercises/practice/leap/.approaches/max-two-checks/content.md
exercises/practice/leap/.approaches/max-two-checks/snippet.txt
exercises/practice/leap/.approaches/time-addition/content.md
exercises/practice/leap/.approaches/time-addition/snippet.txt
exercises/practice/leap/.approaches/time-yearday/content.md
exercises/practice/leap/.approaches/time-yearday/snippet.txt
exercises/practice/leap/.articles/config.json
exercises/practice/leap/.articles/performance/content.md
exercises/practice/leap/.articles/performance/snippet.md

Leap approaches

---

exercises/practice/grains/.approaches/bit-shifting/content.md
exercises/practice/grains/.approaches/bit-shifting/snippet.txt
exercises/practice/grains/.approaches/config.json
exercises/practice/grains/.approaches/introduction.md
exercises/practice/grains/.approaches/math-pow-big-exponentiation/content.md
exercises/practice/grains/.approaches/math-pow-big-exponentiation/snippet.txt
exercises/practice/grains/.articles/config.json
exercises/practice/grains/.articles/performance/content.md
exercises/practice/grains/.articles/performance/snippet.md

Grains approaches

---

exercises/practice/isogram/.approaches/bitfield/content.md
exercises/practice/isogram/.approaches/bitfield/snippet.txt
exercises/practice/isogram/.approaches/config.json
exercises/practice/isogram/.approaches/introduction.md
exercises/practice/isogram/.approaches/map/content.md
exercises/practice/isogram/.approaches/map/snippet.txt
exercises/practice/isogram/.approaches/strings-count/content.md
exercises/practice/isogram/.approaches/strings-count/snippet.txt
exercises/practice/isogram/.articles/config.json
exercises/practice/isogram/.articles/performance/content.md
exercises/practice/isogram/.articles/performance/snippet.md

Isogram approaches

---

exercises/practice/hamming/.approaches/config.json
exercises/practice/hamming/.approaches/introduction.md
exercises/practice/hamming/.approaches/iterate-bytes/content.md
exercises/practice/hamming/.approaches/iterate-bytes/snippet.txt
exercises/practice/hamming/.approaches/iterate-runes/content.md
exercises/practice/hamming/.approaches/iterate-runes/snippet.txt
exercises/practice/hamming/.articles/config.json
exercises/practice/hamming/.articles/performance/content.md
exercises/practice/hamming/.articles/performance/snippet.md

Hamming approaches

---

exercises/practice/nucleotide-count/.approaches/config.json
exercises/practice/nucleotide-count/.approaches/if-with-short-statement/content.md
exercises/practice/nucleotide-count/.approaches/if-with-short-statement/snippet.txt
exercises/practice/nucleotide-count/.approaches/introduction.md
exercises/practice/nucleotide-count/.approaches/switch-statement/content.md
exercises/practice/nucleotide-count/.approaches/switch-statement/snippet.txt
exercises/practice/nucleotide-count/.articles/config.json
exercises/practice/nucleotide-count/.articles/performance/content.md
exercises/practice/nucleotide-count/.articles/performance/snippet.md

Approaches for Nucleotide Count.

Nucleotide count approaches

---

exercises/practice/clock/.approaches/clock-as-int/content.md
exercises/practice/clock/.approaches/clock-as-int/snippet.txt
exercises/practice/clock/.approaches/clock-as-struct/content.md
exercises/practice/clock/.approaches/clock-as-struct/snippet.txt
exercises/practice/clock/.approaches/config.json
exercises/practice/clock/.approaches/introduction.md
exercises/practice/clock/.articles/config.json
exercises/practice/clock/.articles/performance/content.md
exercises/practice/clock/.articles/performance/snippet.md

Clock approaches

---

exercises/practice/robot-name/.approaches/config.json
exercises/practice/robot-name/.approaches/introduction.md
exercises/practice/robot-name/.approaches/shuffle/content.md
exercises/practice/robot-name/.approaches/shuffle/snippet.txt

Robot Name approach

---

exercises/practice/isbn-verifier/.approaches/config.json
exercises/practice/isbn-verifier/.approaches/introduction.md
exercises/practice/isbn-verifier/.approaches/iterate-bytes/content.md
exercises/practice/isbn-verifier/.approaches/iterate-bytes/snippet.txt
exercises/practice/isbn-verifier/.approaches/iterate-runes/content.md
exercises/practice/isbn-verifier/.approaches/iterate-runes/snippet.txt
exercises/practice/isbn-verifier/.articles/config.json
exercises/practice/isbn-verifier/.articles/performance/content.md
exercises/practice/isbn-verifier/.articles/performance/snippet.md

Approaches for ISBN Verifier.
Typo in the branch name, but it seems okay.

ISBN Verifier approaches

---

exercises/practice/rna-transcription/.approaches/config.json
exercises/practice/rna-transcription/.approaches/introduction.md
exercises/practice/rna-transcription/.approaches/map-function/content.md
exercises/practice/rna-transcription/.approaches/map-function/snippet.txt
exercises/practice/rna-transcription/.approaches/map-object/content.md
exercises/practice/rna-transcription/.approaches/map-object/snippet.txt
exercises/practice/rna-transcription/.approaches/switch/content.md
exercises/practice/rna-transcription/.approaches/switch/snippet.txt
exercises/practice/rna-transcription/.articles/config.json
exercises/practice/rna-transcription/.articles/performance/content.md
exercises/practice/rna-transcription/.articles/performance/snippet.md

Approaches for RNA Transcription

RNA Transcription approaches

---

exercises/practice/scrabble-score/.approaches/config.json
exercises/practice/scrabble-score/.approaches/introduction.md
exercises/practice/scrabble-score/.approaches/map/content.md
exercises/practice/scrabble-score/.approaches/map/snippet.txt
exercises/practice/scrabble-score/.approaches/switch-on-runes/content.md
exercises/practice/scrabble-score/.approaches/switch-on-runes/snippet.txt
exercises/practice/scrabble-score/.approaches/switch-on-strings/content.md
exercises/practice/scrabble-score/.approaches/switch-on-strings/snippet.txt
exercises/practice/scrabble-score/.articles/config.json
exercises/practice/scrabble-score/.articles/performance/content.md
exercises/practice/scrabble-score/.articles/performance/snippet.md

Approaches for Scrabble Score.

Scrabble score approaches

---

concepts/interfaces/about.md
concepts/interfaces/introduction.md
exercises/concept/airport-robot/.docs/introduction.md

Fix typos in introduction.md

---

exercises/concept/airport-robot/.meta/config.json

The icon might not be perfect but better than nothing. Since Tai is not on the project anymore, we don't know when we would get one otherwise.
https://github.com/exercism/website-icons/blob/main/exercises/squeaky-clean.svg

Set icon for airport robot

---

exercises/concept/election-day/.meta/config.json

Setting the flag did not work for lasanga master, I want to try this exercise that I have not started yet to see whether there is an issue with the changed config not being picked up by the test runner.

Enable task ids for election day

---

concepts/interfaces/about.md
concepts/interfaces/introduction.md
exercises/concept/airport-robot/.docs/instructions.md
exercises/concept/airport-robot/.docs/introduction.md

- Fixes some errors Grammarly reported
- Creates a link in the footnote of `about.md`

Small fixes to Airport Robot

---

exercises/practice/leap/leap.go

The func didn't had the parameter name , So I added that for convenience.

Updated the parameter in the the fucntion.

---

exercises/concept/vehicle-purchase/.docs/instructions.md

Gave example of NeedsLicense function when implemented for vehicle type truck.

Added extra example of NeedsLicense function.

---

concepts/time/about.md
concepts/time/introduction.md
exercises/concept/booking-up-for-beauty/.docs/introduction.md

Suggested in #2600 
The fork for the original PR doesn't exist anymore so it's impossible to update that PR by pushing to the original branch.

Fix typo in time concept

---

exercises/practice/sieve/.approaches/config.json
exercises/practice/sieve/.approaches/introduction.md
exercises/practice/sieve/.approaches/slice-of-bools/content.md
exercises/practice/sieve/.approaches/slice-of-bools/snippet.txt

Sieve Approach

---

exercises/concept/airport-robot/.meta/config.json

Ran `configlet fmt` on the repo.

Format files with `configlet fmt`

---

exercises/practice/secret-handshake/.approaches/config.json
exercises/practice/secret-handshake/.approaches/introduction.md
exercises/practice/secret-handshake/.approaches/slice-indexes/content.md
exercises/practice/secret-handshake/.approaches/slice-indexes/snippet.txt

Secret Handshake approach

---

exercises/practice/simple-linked-list/.approaches/config.json
exercises/practice/simple-linked-list/.approaches/introduction.md
exercises/practice/simple-linked-list/.approaches/keep-track-of-size/content.md
exercises/practice/simple-linked-list/.approaches/keep-track-of-size/snippet.txt

Approach for Simple Linked List

Simple Linked List approach

---

exercises/practice/binary-search/.approaches/config.json
exercises/practice/binary-search/.approaches/introduction.md
exercises/practice/binary-search/.approaches/loop-with-switch/content.md
exercises/practice/binary-search/.approaches/loop-with-switch/snippet.txt

Binary Search approach

---

exercises/concept/elons-toys/elons_toys.go
exercises/concept/lasagna-master/lasagna_master.go

This is for the two concept exercises where the stub does not contain the functions already: the student needs to create them before the code can compile.

Add hints to the exercise stub to guide the student.

---

exercises/concept/annalyns-infiltration/.meta/config.json
exercises/concept/cars-assemble/.meta/config.json
exercises/concept/lasagna/.meta/config.json
exercises/concept/welcome-to-tech-palace/.meta/config.json

Part of https://github.com/exercism/go/issues/2634

Enable test runner v3 UI for early concept exercises

---

config.json

Following the discussion in: https://forum.exercism.org/t/are-go-practice-exercises-ordered/4464
This makes the order of the exercises make a little more sense.
Also tweaked the difficulty of some exercises according to my experience in the track, hopefully making the difficulty rating more consistent.

Reorder exercises by difficulty

---

exercises/practice/linked-list/.meta/example.go
exercises/practice/linked-list/linked_list.go
exercises/practice/parallel-letter-frequency/.meta/example.go
exercises/practice/parallel-letter-frequency/parallel_letter_frequency.go
exercises/practice/simple-linked-list/.meta/example.go
exercises/practice/simple-linked-list/simple_linked_list.go

As seen on [Isaac's stream](https://www.twitch.tv/videos/1769178812) :)

Improve parameters names in some functions

---

exercises/concept/airport-robot/.meta/config.json
exercises/concept/airport-robot/airport_robot_test.go
exercises/concept/animal-magic/.meta/config.json
exercises/concept/bird-watcher/.meta/config.json
exercises/concept/bird-watcher/bird_watcher_test.go
exercises/concept/blackjack/.meta/config.json
exercises/concept/booking-up-for-beauty/.meta/config.json
exercises/concept/card-tricks/.meta/config.json
exercises/concept/census/.meta/config.json
exercises/concept/chessboard/.meta/config.json
exercises/concept/election-day/.meta/config.json
exercises/concept/elons-toys/.meta/config.json
exercises/concept/expenses/.meta/config.json
exercises/concept/expenses/expenses_test.go
exercises/concept/gross-store/.meta/config.json
exercises/concept/interest-is-interesting/.meta/config.json
exercises/concept/lasagna-master/.meta/config.json
exercises/concept/logs-logs-logs/.meta/config.json
exercises/concept/meteorology/.meta/config.json
exercises/concept/need-for-speed/.meta/config.json
exercises/concept/parsing-log-files/.meta/config.json
exercises/concept/party-robot/.meta/config.json
exercises/concept/savings-account/.meta/config.json
exercises/concept/sorting-room/.meta/config.json
exercises/concept/vehicle-purchase/.meta/config.json
exercises/concept/weather-forecast/.meta/config.json

I went through all concept exercises to check whether they need manual task id assignment or not.

enable v3 test runner UI for remaining exercises (where it makes sense)

---

exercises/practice/grains/.docs/instructions.md

This removes the bonus section and last two paragraphs about optimizing for speed/readability and sharing thoughts/comments.

Sync grains docs.

---

exercises/practice/grade-school/.docs/instructions.md

This removes the bonus section and last two paragraphs about protecting internal data from external changes and sharing thoughts/comments.

Sync grade-school docs.

---

exercises/practice/wordy/.docs/instructions.md

This removes the bonus section about handling exponents.

Sync wordy docs.

---

exercises/concept/election-day/.docs/instructions.md
exercises/concept/election-day/election_result.go

Single word change, but now it fits with godoc :)

Fix godoc comment variable name

---

concepts/error-wrapping/.meta/config.json
concepts/error-wrapping/about.md
concepts/error-wrapping/introduction.md
concepts/error-wrapping/links.json
config.json

Part of the last task in https://github.com/exercism/go/issues/2492 .

Concept: Error Wrapping

---

exercises/practice/resistor-color/resistor_color.go

PR relates to [forum thread](https://forum.exercism.org/t/improvement-of-colors-comment-in-resistor-color/7821), created in order to unify comments in this exercise

Update function comment resistor_color.go

---

exercises/concept/vehicle-purchase/vehicle_purchase_test.go

fix `TestCalculateResellPrice` test names

remove double percent signs

---

docs/RESOURCES.md

Update resources page as suggested by this [blog post](https://forum.exercism.org/t/broken-link-tracks-go-resources/8746).
In addition to the suggestions in the post, other links were revisited and converted to https and/or to more up-to-date pages.

Update resources page
